import { createElement } from 'react';
import { Loader2, Sparkles } from 'lucide-react';
import MiniLesson from '../MiniLesson';
import { usePyodide } from '../../contexts/PyodideContext';

export default function GutenbergLevel3() {
  const { load: loadPyodide, ready: pyReady, state: pyState, loadProgress } = usePyodide();
  const loading = pyState === 'loading';

  const miniLessons = [
    {
      title: 'Network effects — Metcalfe\'s law applied to the printing ecosystem',
      concept: `A single printing press is useful. Two presses in different cities are more than twice as useful — because they can exchange and reprint each other's works. This is **Metcalfe's law**: the value of a network grows as the **square** of the number of nodes.

**V = k x N²**

Where N is the number of connected nodes (presses, booksellers, readers) and k is a proportionality constant. With 10 presses, the network has potential value proportional to 100. With 100 presses, it jumps to 10,000.

This explains the explosive growth of printing: each new press made every existing press more valuable (more titles to reprint, more markets to sell into, more readers demanding books). The network created a **positive feedback loop** — more presses led to more readers, which justified more presses.

By 1500 (just 50 years after Gutenberg), there were over 1,000 presses across 250 European cities, producing an estimated 20 million volumes. The network effect turned a single innovation into a continent-wide revolution.

📚 *A network effect (or network externality) occurs when a product or service becomes more valuable as more people use it. Telephones, the internet, and social media all exhibit network effects — each new user increases the value for every existing user.*`,
      analogy: 'Imagine a fax machine. One fax machine is useless — who do you fax? Two machines can communicate — useful. A hundred machines form a network where any machine can reach any other. The value isn\'t in the machine itself but in the connections. Printing presses worked the same way: each new press expanded what every other press could offer.',
      storyConnection: 'Gutenberg\'s press in Mainz was valuable on its own. But when his trained workers dispersed across Europe — Sweynheym and Pannartz to Rome, Caxton to London, Koberger to Nuremberg — they created a network. A book printed in Venice could be reprinted in Paris within months. The network, not the individual press, transformed civilisation.',
      checkQuestion: 'In 1460, there were roughly 10 presses in Europe. By 1480, there were about 100. According to Metcalfe\'s law, by what factor did the network\'s value increase?',
      checkAnswer: 'Value is proportional to N². At 10 presses: V ~ 100. At 100 presses: V ~ 10,000. The factor is 10,000/100 = 100x. A 10x increase in presses produced a 100x increase in network value — explaining why the printing revolution accelerated so dramatically in the late 1400s.',
      codeIntro: 'Model the growth of the European printing network and the value generated by Metcalfe\'s law.',
      code: `import numpy as np

def metcalfe_value(n_nodes, k=1.0):
    """Network value proportional to N squared."""
    return k * n_nodes ** 2

def logistic_growth(t, capacity, rate, midpoint):
    """Logistic S-curve for network adoption."""
    return capacity / (1 + np.exp(-rate * (t - midpoint)))

# Historical printing press growth (approximate)
years = np.arange(1450, 1550)
press_counts = logistic_growth(years, capacity=1200, rate=0.12, midpoint=1485)

print("=== European Printing Network Growth ===")
print(f"{'Year':<8} {'Presses':>8} {'Cities':>8} {'Network Value':>14} {'Titles/Year':>12}")
print("-" * 52)

for y in [1450, 1455, 1460, 1470, 1480, 1490, 1500, 1510, 1520, 1540]:
    idx = y - 1450
    n = max(1, int(press_counts[idx]))
    cities = max(1, int(n * 0.25))  # roughly 1 city per 4 presses
    value = metcalfe_value(n)
    titles = int(n * 3.5)  # each press produces ~3-4 titles/year
    print(f"{y:<8} {n:>7} {cities:>7} {value:>13,} {titles:>11,}")

# Compare linear vs network growth
print("\\n=== Linear vs Network Value ===")
print("If presses had no network effects (value = N):")
for n in [10, 50, 100, 500, 1000]:
    linear = n
    network = metcalfe_value(n)
    ratio = network / linear
    print(f"  {n:>4} presses: linear={linear:>6,}  network={network:>10,}  ratio={ratio:>6.0f}x")

# Reed's law: group-forming networks scale as 2^N
print("\\n=== Beyond Metcalfe: Reed's Law ===")
print("If presses form specialised sub-networks (theology, science, law):")
for n in [5, 10, 15, 20, 25]:
    metcalfe = n ** 2
    reed = min(2 ** n, 10**9)  # cap for display
    print(f"  {n:>2} presses: Metcalfe={metcalfe:>8,}  Reed={reed:>12,}")

print("\\nReed's law grows so fast it becomes unrealistic beyond ~25 nodes.")
print("In practice, not all possible sub-groups form — real network value")
print("falls between Metcalfe (N^2) and Reed (2^N).")`,
      challenge: 'Not all connections are equal — a press in Venice (major trade hub) connects to more cities than one in a small town. Modify the model to weight nodes by their connectivity (degree). A "weighted Metcalfe" model: V = sum of (degree_i x degree_j) for all pairs. How does this change the value curve?',
      successHint: 'Metcalfe\'s law explains why platforms like the internet, social media, and app stores grow explosively. You modelled the same dynamics for the 15th-century printing network. The mathematics of network effects is the foundation of modern platform economics — from Facebook to Uber to Bitcoin.',
    },
    {
      title: 'Font design mathematics — Bezier curves and letterforms',
      concept: `Every letter you see on screen is defined by **Bezier curves** — smooth, mathematically precise curves specified by a few control points. A quadratic Bezier curve uses 3 points; a cubic Bezier uses 4:

**B(t) = (1-t)³P₀ + 3(1-t)²tP₁ + 3(1-t)t²P₂ + t³P₃**

Where t ranges from 0 to 1, P₀ is the start, P₃ is the end, and P₁, P₂ are control points that "pull" the curve without touching it.

Bezier curves have beautiful mathematical properties: they always start at P₀ and end at P₃, they're tangent to the control polygon at the endpoints, and they lie entirely within the convex hull of the control points. These properties make them ideal for typography — designers can intuitively shape letters by dragging control points.

Modern fonts (TrueType, OpenType) are collections of Bezier curves. A single character like 'g' might use 30-50 control points. A complete font with all characters, ligatures, and symbols can require 10,000+ control points — each placed with sub-pixel precision.

📚 *Pierre Bezier developed these curves at Renault in the 1960s for designing car bodies. Paul de Casteljau independently developed the same mathematics at Citroen. Today, Bezier curves are used in every vector graphics application: fonts, SVG, Illustrator, CAD.*`,
      analogy: 'Imagine bending a flexible metal strip. You pin the two ends in place (P₀ and P₃), then push the middle with your fingers at two points (P₁ and P₂). The strip curves smoothly toward your fingers without touching them — that\'s exactly how Bezier control points work. Moving a finger changes the curve\'s shape without breaking its smoothness.',
      storyConnection: 'Gutenberg didn\'t have Bezier curves — he carved each letter by hand into steel punches, which were hammered into copper matrices, which were used to cast lead type. The shapes he created (the textura blackletter of the 42-line Bible) are now preserved digitally as Bezier curves in modern recreations of his typeface.',
      checkQuestion: 'A cubic Bezier has control points P₀=(0,0), P₁=(0,1), P₂=(1,1), P₃=(1,0). What point does the curve pass through at t=0.5?',
      checkAnswer: 'B(0.5) = (0.5)³(0,0) + 3(0.5)²(0.5)(0,1) + 3(0.5)(0.5)²(1,1) + (0.5)³(1,0) = 0.125(0,0) + 0.375(0,1) + 0.375(1,1) + 0.125(1,0) = (0+0+0.375+0.125, 0+0.375+0.375+0) = (0.5, 0.75). The curve passes through the midpoint horizontally but is pulled upward by the control points.',
      codeIntro: 'Generate Bezier curves for letter shapes and explore how control point placement affects typography.',
      code: `import numpy as np

def cubic_bezier(p0, p1, p2, p3, n_points=50):
    """Evaluate a cubic Bezier curve at n_points."""
    t = np.linspace(0, 1, n_points)
    x = ((1-t)**3 * p0[0] + 3*(1-t)**2*t * p1[0] +
         3*(1-t)*t**2 * p2[0] + t**3 * p3[0])
    y = ((1-t)**3 * p0[1] + 3*(1-t)**2*t * p1[1] +
         3*(1-t)*t**2 * p2[1] + t**3 * p3[1])
    return x, y

def curve_length(x, y):
    """Approximate arc length of a curve."""
    dx = np.diff(x)
    dy = np.diff(y)
    return np.sum(np.sqrt(dx**2 + dy**2))

def curvature(x, y):
    """Approximate curvature at each point."""
    dx = np.gradient(x)
    dy = np.gradient(y)
    ddx = np.gradient(dx)
    ddy = np.gradient(dy)
    num = np.abs(dx * ddy - dy * ddx)
    den = (dx**2 + dy**2)**1.5
    return np.where(den > 1e-10, num / den, 0)

# Define a simplified letter 'S' using two cubic Bezier segments
# Top half of S
s_top = [(0.7, 1.0), (0.9, 0.85), (0.1, 0.65), (0.3, 0.5)]
# Bottom half of S
s_bot = [(0.3, 0.5), (0.5, 0.35), (1.0, 0.15), (0.3, 0.0)]

x1, y1 = cubic_bezier(*s_top)
x2, y2 = cubic_bezier(*s_bot)

print("=== Bezier Curve Analysis: Letter 'S' ===")
print(f"Top segment: {len(x1)} points, length = {curve_length(x1, y1):.3f}")
print(f"Bottom segment: {len(x2)} points, length = {curve_length(x2, y2):.3f}")

k1 = curvature(x1, y1)
k2 = curvature(x2, y2)
print(f"Top max curvature: {np.max(k1):.2f} (at the tightest bend)")
print(f"Bottom max curvature: {np.max(k2):.2f}")

# ASCII rendering of the curve
print("\\n=== ASCII Render ===")
grid = [[' ' for _ in range(40)] for _ in range(20)]
for x, y in zip(np.concatenate([x1, x2]), np.concatenate([y1, y2])):
    col = int(x * 35) + 2
    row = 19 - int(y * 18)
    if 0 <= row < 20 and 0 <= col < 40:
        grid[row][col] = '#'
for row in grid:
    print('  ' + ''.join(row))

# Compare font styles: different control points = different aesthetics
print("\\n=== Font Style Comparison ===")
styles = {
    "Serif (Gutenberg-style)": [(0, 0), (0, 0.8), (1.0, 0.8), (1.0, 0)],
    "Sans-serif (modern)":     [(0, 0), (0.1, 0.9), (0.9, 0.9), (1.0, 0)],
    "Italic (slanted)":        [(0.1, 0), (0.05, 0.8), (1.1, 0.8), (1.0, 0)],
    "Bold (wider curves)":     [(0, 0), (-0.2, 1.0), (1.2, 1.0), (1.0, 0)],
}

for name, pts in styles.items():
    x, y = cubic_bezier(*pts)
    length = curve_length(x, y)
    max_k = np.max(curvature(x, y))
    print(f"  {name:<28} length={length:.3f}  max curvature={max_k:.2f}")

print("\\nMore curvature = tighter bends = more ink needed = bolder appearance")
print("Gutenberg's textura had very high curvature — dense, dark letterforms")`,
      challenge: 'Design the letter "O" using 4 cubic Bezier segments (one per quadrant). Each segment should connect smoothly to the next (tangent continuity: the direction at the end of one segment matches the start of the next). Calculate the total curve length and verify it approximates the circumference of an ellipse.',
      successHint: 'You just explored the mathematics behind every font on every screen in the world. Bezier curves — developed for car design — became the universal language of digital typography. Every time you read text on a screen, you\'re looking at thousands of Bezier curves rendered in real time.',
    },
    {
      title: 'Print quality — ink viscosity and surface tension',
      concept: `Getting a crisp printed letter requires precise control of **ink physics**. Two properties dominate:

1. **Viscosity** (resistance to flow): Too thin and the ink runs, blurring letters. Too thick and it won't transfer from type to paper. Measured in Pa.s (pascal-seconds).

2. **Surface tension** (tendency to minimise surface area): Determines whether ink spreads into paper fibres (wetting) or beads up on the surface. Measured in mN/m (millinewtons per metre).

The **Weber number** (We) relates inertia to surface tension: We = rho v² L / sigma. At low We, surface tension dominates (ink stays as droplets). At high We, inertia wins (ink splashes and splatters).

The **capillary number** (Ca) relates viscosity to surface tension: Ca = mu v / sigma. It determines how ink penetrates paper pores — high Ca means viscous flow dominates (ink stays on the surface); low Ca means capillary action pulls ink deep into the paper (feathering).

Gutenberg's ink was revolutionary: a varnish-based formula (linseed oil + lampblack) with much higher viscosity than the water-based inks used for woodblock printing. This higher viscosity gave sharp edges and prevented feathering.

📚 *Dimensionless numbers (Weber, capillary, Reynolds) are ratios of competing physical effects. They tell you which physics dominates in a given situation without needing to solve the full equations.*`,
      analogy: 'Think of painting with watercolour vs oil paint. Watercolour (low viscosity, low surface tension) soaks into paper immediately, spreading and feathering. Oil paint (high viscosity) sits on the surface exactly where you put it. Gutenberg\'s switch from water-based to oil-based ink is exactly this difference — and it made crisp printing possible.',
      storyConnection: 'Gutenberg\'s ink recipe was one of his most closely guarded secrets. While Chinese and Korean printers used water-based inks that worked well on soft paper pressed by rubbing, Gutenberg needed ink that would transfer under the enormous pressure of a screw press onto stiff European rag paper without smearing or feathering. His linseed oil varnish with lampblack solved this — and his exact recipe is still debated by historians.',
      checkQuestion: 'Ink A has viscosity 0.1 Pa.s and surface tension 30 mN/m. Ink B has viscosity 1.0 Pa.s and surface tension 40 mN/m. At a transfer speed of 0.5 m/s, which ink has a higher capillary number (less feathering)?',
      checkAnswer: 'Ca = mu v / sigma. Ink A: Ca = 0.1 x 0.5 / 0.030 = 1.67. Ink B: Ca = 1.0 x 0.5 / 0.040 = 12.5. Ink B has a much higher Ca — viscous forces dominate over capillary forces, meaning the ink resists being pulled into paper fibres. Less feathering, crisper edges. This is why Gutenberg used thick, oil-based ink.',
      codeIntro: 'Model ink transfer physics and predict print quality based on viscosity and surface tension.',
      code: `import numpy as np

def capillary_number(viscosity, velocity, surface_tension):
    """Ca = mu * v / sigma. Higher Ca = less feathering."""
    return viscosity * velocity / surface_tension

def weber_number(density, velocity, length, surface_tension):
    """We = rho * v^2 * L / sigma. Higher We = more splashing."""
    return density * velocity**2 * length / surface_tension

def ink_spread(viscosity, surface_tension, paper_porosity, time_ms):
    """
    Washburn equation: penetration depth of ink into paper.
    depth = sqrt(sigma * r * cos(theta) * t / (2 * mu))
    """
    r_pore = paper_porosity * 1e-6  # pore radius in metres
    theta = 0.6  # contact angle factor
    t_sec = time_ms / 1000
    depth = np.sqrt(surface_tension * r_pore * theta * t_sec / (2 * viscosity))
    return depth * 1000  # convert to mm

# Compare historical ink formulations
inks = [
    {"name": "Chinese water ink",    "visc": 0.01, "st": 0.045, "density": 1050},
    {"name": "Medieval iron gall",   "visc": 0.05, "st": 0.040, "density": 1100},
    {"name": "Gutenberg oil ink",    "visc": 1.5,  "st": 0.032, "density": 1150},
    {"name": "Modern offset ink",    "visc": 5.0,  "st": 0.035, "density": 1200},
    {"name": "Inkjet (modern)",      "visc": 0.003,"st": 0.028, "density": 1020},
]

transfer_velocity = 0.3  # m/s — speed of platen contact
letter_size = 0.003       # 3mm — typical letter feature size

print("=== Ink Physics Comparison ===")
print(f"{'Ink Type':<24} {'Visc (Pa.s)':>11} {'ST (mN/m)':>10} {'Ca':>8} {'We':>8} {'Quality':>10}")
print("-" * 73)

for ink in inks:
    ca = capillary_number(ink["visc"], transfer_velocity, ink["st"])
    we = weber_number(ink["density"], transfer_velocity, letter_size, ink["st"])

    if ca > 5 and we < 10:
        quality = "CRISP"
    elif ca > 1 and we < 50:
        quality = "GOOD"
    elif ca < 0.5:
        quality = "FEATHERED"
    else:
        quality = "SPLATTERED"

    print(f"{ink['name']:<24} {ink['visc']:>9.3f} {ink['st']*1000:>8.1f} {ca:>8.2f} {we:>8.2f} {quality:>10}")

# Ink penetration depth over time
print("\\n=== Ink Penetration into Paper (mm) ===")
paper_porosity = 10  # micrometres — typical rag paper
times_ms = [1, 5, 10, 50, 100, 500]

header = f"{'Ink Type':<24}" + "".join(f"{t:>6}ms" for t in times_ms)
print(header)
print("-" * len(header))

for ink in inks:
    depths = [ink_spread(ink["visc"], ink["st"], paper_porosity, t) for t in times_ms]
    row = f"{ink['name']:<24}" + "".join(f"{d:>6.3f}" for d in depths)
    print(row)

print("\\nGutenberg's oil ink penetrated slowly — giving sharp edges.")
print("Water-based inks penetrate deeply and quickly — causing feathering.")
print("Modern inkjet uses surfactants to control spread precisely.")`,
      challenge: 'Paper quality matters too. Model three papers: smooth vellum (porosity 2 um), rag paper (10 um), and cheap pulp (25 um). For Gutenberg\'s oil ink, calculate the penetration depth at 10 ms on each paper. Which paper gives the crispest print? Why did Gutenberg print some copies on vellum and others on paper?',
      successHint: 'You modelled the fluid dynamics of ink transfer — the same physics used to design modern inkjet printers, offset presses, and 3D printing nozzles. The interplay of viscosity, surface tension, and capillary action determines print quality in every printing technology, from Gutenberg to your desktop printer.',
    },
    {
      title: 'Censorship vs distribution — adversarial game theory',
      concept: `Printing created a new conflict: **authorities** wanted to control information, while **printers** wanted to distribute it (and profit). This is an **adversarial game** — two players with opposing objectives making strategic decisions.

The **censor** chooses: which books to ban, how many inspectors to deploy, what penalties to impose. The **printer** chooses: what to print, where to print, how to distribute, whether to use pseudonyms or secret presses.

In game theory, a **Nash equilibrium** is a state where neither player can improve their outcome by changing strategy alone. In the censorship game, the equilibrium depends on the **cost ratio**: how expensive is enforcement vs how profitable is distribution?

If enforcement is cheap relative to printing profits, censorship is effective (few banned books circulate). If enforcement is expensive (large territory, many presses, easy smuggling), censorship fails — banned books circulate freely.

Historically, printing made censorship dramatically more expensive: before printing, controlling a few scriptoria controlled all book production. After printing, controlling thousands of independent presses across hundreds of cities was nearly impossible.

📚 *Game theory studies strategic interactions — situations where your best move depends on what the other player does. Nash equilibrium (John Nash, 1950) is the central concept: a stable state where no player benefits from changing strategy unilaterally.*`,
      analogy: 'Think of a game of cat and mouse. The cat (censor) patrols certain corridors. The mouse (printer) chooses a path. If the cat covers all corridors, the mouse is caught — but the cat is exhausted. If the mouse picks one random path, the cat can\'t cover everything. The equilibrium is a mix of strategies — both sides randomise, and some mice always get through.',
      storyConnection: 'The Catholic Church established the Index Librorum Prohibitorum (List of Prohibited Books) in 1559 — banning works by Galileo, Copernicus, Descartes, and others. But the Index was largely ineffective: printers in Protestant countries, or in Venice (which defied papal authority), simply printed banned books and smuggled them across borders. The cost of enforcement exceeded the Church\'s resources.',
      checkQuestion: 'A censor can inspect 10 presses per month. There are 100 presses in the region, and 5 are printing banned material. If the censor inspects randomly, what is the probability of catching a violator in one month?',
      checkAnswer: 'Each inspection has a 5/100 = 5% chance of catching a violator. Over 10 inspections: P(at least one catch) = 1 - (0.95)^10 = 1 - 0.599 = 0.401 or about 40%. The violators have a 60% chance of escaping detection each month. At this rate, censorship is leaky — most banned material gets through.',
      codeIntro: 'Model the censorship vs distribution game and find the Nash equilibrium for different cost ratios.',
      code: `import numpy as np

def censorship_game(n_presses, n_inspectors, n_violators,
                    fine_per_catch, profit_per_book, cost_per_inspector):
    """
    Model the censorship vs distribution game.
    Returns payoffs for both censor and printer.
    """
    # Probability of catching each violator
    p_inspect = min(n_inspectors / n_presses, 1.0)
    p_catch = 1 - (1 - p_inspect) ** 1  # per violator per month

    expected_catches = n_violators * p_catch
    expected_escapes = n_violators * (1 - p_catch)

    # Censor payoff: fines collected minus inspection costs
    censor_payoff = expected_catches * fine_per_catch - n_inspectors * cost_per_inspector

    # Printer payoff: profit from uncaught books minus fines when caught
    printer_payoff = expected_escapes * profit_per_book - expected_catches * fine_per_catch

    return {
        "p_catch": p_catch,
        "expected_catches": expected_catches,
        "censor_payoff": censor_payoff,
        "printer_payoff": printer_payoff,
    }

# Historical scenario: Europe circa 1550
print("=== Censorship vs Distribution Game ===")
print("Setting: 100 presses, 8 printing banned material\\n")

n_presses = 100
n_violators = 8
fine = 500        # guilders per catch
profit = 200      # guilders per banned book produced
inspector_cost = 50  # guilders per inspector per month

print(f"{'Inspectors':>11} {'P(catch)':>9} {'Catches':>8} {'Escapes':>8} {'Censor $':>9} {'Printer $':>10}")
print("-" * 57)

for n_insp in [5, 10, 20, 30, 50, 75, 100]:
    result = censorship_game(n_presses, n_insp, n_violators,
                             fine, profit, inspector_cost)
    escapes = n_violators - result["expected_catches"]
    print(f"{n_insp:>10} {result['p_catch']:>8.1%} {result['expected_catches']:>7.1f} "
          f"{escapes:>7.1f} {result['censor_payoff']:>8.0f} {result['printer_payoff']:>9.0f}")

# Find Nash equilibrium: where censor's marginal gain = marginal cost
print("\\n=== Finding Nash Equilibrium ===")
best_censor = -float('inf')
eq_inspectors = 0
for n_insp in range(1, n_presses + 1):
    result = censorship_game(n_presses, n_insp, n_violators,
                             fine, profit, inspector_cost)
    if result["censor_payoff"] > best_censor:
        best_censor = result["censor_payoff"]
        eq_inspectors = n_insp

eq_result = censorship_game(n_presses, eq_inspectors, n_violators,
                            fine, profit, inspector_cost)
print(f"Optimal inspectors: {eq_inspectors}")
print(f"Censor payoff: {eq_result['censor_payoff']:.0f} guilders")
print(f"Catch rate: {eq_result['p_catch']:.1%}")
print(f"Books that escape: {n_violators - eq_result['expected_catches']:.1f} per month")

# How network growth defeats censorship
print("\\n=== Network Growth vs Censorship Capacity ===")
for era, n_press, n_viol in [
    ("1460 (early)", 20, 2),
    ("1480 (growth)", 100, 10),
    ("1500 (mature)", 1000, 80),
    ("1520 (Reformation)", 2000, 300),
]:
    result = censorship_game(n_press, 30, n_viol, fine, profit, inspector_cost)
    escape_pct = (1 - result["p_catch"]) * 100
    print(f"  {era:<24} {n_press:>5} presses, {n_viol:>3} violators: "
          f"{escape_pct:.0f}% escape, censor payoff: {result['censor_payoff']:.0f}")

print("\\nAs the network grew, censorship became a losing game —")
print("the cost of enforcement grew faster than the ability to fund it.")`,
      challenge: 'Add a "smuggling" option: printers can pay a cost to move operations to a different jurisdiction (beyond the censor\'s reach). How does the availability of "exit" change the equilibrium? This models why Geneva, Amsterdam, and Venice became printing capitals — they offered jurisdictional escape from censorship.',
      successHint: 'You modelled a real adversarial game with historical consequences. The same game-theoretic framework applies to modern content moderation (platforms vs policy violations), copyright enforcement (studios vs piracy), and cybersecurity (defenders vs attackers). The economics of enforcement vs distribution haven\'t changed since Gutenberg.',
    },
    {
      title: 'Comparative media economics — scroll, codex, print, digital',
      concept: `Each information technology has a different **cost structure** — the relationship between fixed costs, marginal costs, distribution costs, and speed. Comparing these reveals why each technology displaced its predecessor.

| Medium | Fixed Cost | Marginal Cost | Distribution | Speed |
|--------|-----------|---------------|--------------|-------|
| Oral | None | Time per telling | Walking speed | 1x |
| Scroll | Scribe setup | High per copy | Ship/caravan | 10x |
| Codex (bound book) | Scribe setup | High per copy | Ship/caravan | 10x |
| Printed book | Very high | Very low | Ship/caravan | 1000x |
| Digital | Medium | Zero | Light speed | 10^9x |

The key transitions are: (1) **scroll to codex** — random access (you can flip to any page instead of unrolling), (2) **codex to print** — marginal cost collapse (copies become cheap), (3) **print to digital** — distribution cost collapse (copies travel at light speed for free).

Each transition created a **disruption**: the new technology didn't just improve on the old one — it changed the economics so fundamentally that entire industries and social structures reorganised around it.

📚 *A disruptive technology doesn't just do the same thing better — it changes the cost structure so radically that new use cases become possible. Printing didn't just make existing books cheaper; it made pamphlets, newspapers, and textbooks possible for the first time.*`,
      analogy: 'Compare sending a letter by horse messenger (scroll era), by postal service (codex era), by telegraph (print era), and by email (digital era). Each jump didn\'t just make the same message faster — it enabled entirely new types of communication. You don\'t send a tweet by horse messenger, and you don\'t publish a newspaper orally.',
      storyConnection: 'Gutenberg\'s Bible was a codex — but produced by print technology. The combination of the codex format (random access, compact, durable) with the printing process (cheap copies) created the modern book. Neither innovation alone would have changed the world — it was the combination that mattered.',
      checkQuestion: 'A scribe produces 1 codex per 6 months. A press produces 500 per 6 months after 3 months of setup. Over 5 years, how many copies does each produce?',
      checkAnswer: 'Scribe: 10 copies (1 per 6 months x 10 half-years). Press: setup takes first 3 months, then 4.5 years of production = 9 half-years x 500 = 4,500 copies. The press produces 450x more copies. But the scribe can start immediately with zero setup — for a single copy, the scribe is faster and cheaper.',
      codeIntro: 'Model the economics of four information technologies across history and identify the disruption thresholds.',
      code: `import numpy as np

class MediaTechnology:
    def __init__(self, name, fixed_cost, marginal_cost, setup_months,
                 copies_per_month, dist_cost_per_km, speed_km_per_day):
        self.name = name
        self.fixed = fixed_cost
        self.marginal = marginal_cost
        self.setup = setup_months
        self.rate = copies_per_month
        self.dist_cost = dist_cost_per_km
        self.speed = speed_km_per_day

    def total_cost(self, n_copies, months_available):
        """Total cost to produce n copies within given time."""
        usable_months = max(0, months_available - self.setup)
        max_copies = int(usable_months * self.rate)
        if max_copies < n_copies:
            return float('inf')  # can't produce enough
        return self.fixed + n_copies * self.marginal

    def time_to_reach(self, audience_size, dist_km=1000):
        """Months to reach audience of given size at given distance."""
        production_months = audience_size / max(self.rate, 0.01) + self.setup
        transit_days = dist_km / self.speed
        return production_months + transit_days / 30

media = [
    MediaTechnology("Oral tradition",    0,    5,   0, 30,    0.1,  30),
    MediaTechnology("Scroll (scribal)",  20,  25,   1,  2,    0.5,  50),
    MediaTechnology("Codex (scribal)",   30,  20,   1,  2,    0.5,  50),
    MediaTechnology("Printed book",     500,   2,   3, 300,   0.5,  50),
    MediaTechnology("Digital (modern)",  100,  0.001, 0.1, 1e6, 0.0001, 3e5),
]

# Cost comparison at different scales
print("=== Total Cost by Production Volume (guilders) ===")
volumes = [1, 10, 50, 100, 500, 1000, 10000]
print(f"{'Technology':<22}" + "".join(f"{v:>8}" for v in volumes))
print("-" * (22 + 8 * len(volumes)))

for m in media:
    costs = []
    for v in volumes:
        c = m.total_cost(v, 60)  # 5 years available
        costs.append(f"{c:>7.0f}" if c < 1e6 else "    inf")
    print(f"{m.name:<22}" + "".join(f"{c:>8}" for c in costs))

# Average cost per copy
print("\\n=== Average Cost Per Copy ===")
print(f"{'Technology':<22}" + "".join(f"{v:>8}" for v in volumes))
print("-" * (22 + 8 * len(volumes)))

for m in media:
    avgs = []
    for v in volumes:
        c = m.total_cost(v, 60)
        avg = c / v if c < 1e6 else float('inf')
        avgs.append(f"{avg:>7.1f}" if avg < 1000 else "    inf")
    print(f"{m.name:<22}" + "".join(f"{a:>8}" for a in avgs))

# Time to reach 1000 people at different distances
print("\\n=== Months to Reach 1,000 Readers ===")
distances = [100, 500, 1000, 5000]
print(f"{'Technology':<22}" + "".join(f"{d:>7}km" for d in distances))
print("-" * (22 + 9 * len(distances)))

for m in media:
    times = [m.time_to_reach(1000, d) for d in distances]
    row = f"{m.name:<22}"
    for t in times:
        if t < 1:
            row += f"{'<1 mo':>9}"
        elif t < 120:
            row += f"{t:>7.0f}mo"
        else:
            row += f"{t/12:>6.0f}yr "
    print(row)

# Disruption index: how much cheaper/faster than predecessor
print("\\n=== Disruption Index (vs predecessor) ===")
for i in range(1, len(media)):
    prev = media[i-1]
    curr = media[i]
    cost_ratio = prev.total_cost(100, 60) / max(curr.total_cost(100, 60), 0.01)
    speed_ratio = curr.speed / max(prev.speed, 0.01)
    print(f"  {prev.name} -> {curr.name}:")
    print(f"    Cost at 100 copies: {cost_ratio:.1f}x cheaper")
    print(f"    Distribution speed: {speed_ratio:.0f}x faster")`,
      challenge: 'Add a "search cost" dimension — how easy is it to find a specific piece of information? Scrolls require linear search (read from start). Codices have indices (random access). Printed books have standardised page numbers. Digital has full-text search. Model the time to find a specific passage in a 500-page work across each technology.',
      successHint: 'You built a comparative model of information technology economics spanning 3,000 years. The pattern repeats: each disruption collapses a different cost (production, distribution, search) and enables new use cases that the old technology couldn\'t support. Understanding this pattern helps predict which technologies will be disruptive next.',
    },
  ];

  return (
    <div>
      <div className="flex items-center gap-3 mb-6">
        <div className="flex items-center gap-2 bg-rose-100 dark:bg-rose-900/30 text-rose-700 dark:text-rose-300 px-4 py-2 rounded-full text-sm font-semibold">
          <Sparkles className="w-4 h-4" /> Level 3: Engineer
        </div>
        <span className="text-sm text-gray-500 dark:text-gray-400">Network effects, typography mathematics, and media economics</span>
      </div>

      {!pyReady && (
        <div className="mb-8 bg-gray-50 dark:bg-gray-800 rounded-xl p-6 text-center">
          <p className="text-gray-600 dark:text-gray-300 mb-4">
            Level 3 covers network effects, Bezier curves, ink physics, game theory of censorship, and comparative media economics.
          </p>
          <button onClick={loadPyodide} disabled={loading}
            className="inline-flex items-center gap-2 bg-rose-600 hover:bg-rose-700 disabled:opacity-50 text-white px-6 py-3 rounded-xl font-semibold transition-colors">
            {loading ? (<><Loader2 className="w-5 h-5 animate-spin" /> {loadProgress}</>) : (<><Sparkles className="w-5 h-5" /> Load Python</>)}
          </button>
        </div>
      )}

      <div className="space-y-8">
        {miniLessons.map((lesson, i) => (
          <MiniLesson
            key={i}
            id={`L3-${i + 1}`}
            number={i + 1}
            title={lesson.title}
            concept={lesson.concept}
            analogy={lesson.analogy}
            storyConnection={lesson.storyConnection}
            checkQuestion={lesson.checkQuestion}
            checkAnswer={lesson.checkAnswer}
            codeIntro={lesson.codeIntro}
            code={lesson.code}
            challenge={lesson.challenge}
            successHint={lesson.successHint}
          />
        ))}
      </div>
    </div>
  );
}
