import { useState, useRef, useCallback } from 'react';
import { Loader2, Sparkles } from 'lucide-react';
import MiniLesson from '../MiniLesson';
import { usePyodide } from '../../contexts/PyodideContext';

export default function HawkBlueLevel1() {
  const { pyodideRef, load: loadPyodide, ready: pyReady, state: pyState, loadProgress } = usePyodide();
  const loading = pyState === 'loading';

  const miniLessons = [
    {
      title: 'The four forces of flight',
      concept: `Every flying object — bird, airplane, or drone — is subject to exactly four forces:

1. **Lift** (upward): generated by wings deflecting air downward
2. **Weight** (downward): gravity pulling the object toward Earth (\`W = m × g\`)
3. **Thrust** (forward): engine power or wing flapping
4. **Drag** (backward): air resistance opposing motion

For steady, level flight: Lift = Weight AND Thrust = Drag

For gliding (no thrust): the bird descends slowly, converting altitude (potential energy) into forward motion to overcome drag. The **glide ratio** tells how far it goes horizontally for each meter of altitude lost.

📚 *In Python, we store the four forces as variables and calculate balance conditions. The \`if/else\` statement lets us check whether forces are balanced.*`,
      analogy: 'The four forces are like a tug of war in two directions. Lift vs Weight is the vertical contest — if lift wins, you climb; if weight wins, you descend. Thrust vs Drag is the horizontal contest — if thrust wins, you speed up; if drag wins, you slow down. Steady flight is a perfect tie in both directions.',
      storyConnection: 'The hawks soaring over Phawngpui (Blue Mountain) in Mizoram are masters of the four forces. They rarely flap their wings — instead, they exploit rising air currents (thermals) for lift and adjust their wing shape to minimize drag. They achieve flight with almost zero thrust, using gravity and thermals alone.',
      checkQuestion: 'A hawk weighs 1.5 kg. In steady gliding flight, what is the lift force?',
      checkAnswer: 'In steady flight, Lift = Weight = m × g = 1.5 × 9.81 = 14.7 N (Newtons). The wings must deflect enough air downward to create exactly this much upward force. If lift exceeds weight even slightly, the hawk climbs; if it falls short, the hawk descends.',
      codeIntro: 'Calculate the four forces for different flight conditions of a hawk over Blue Mountain.',
      code: `# Four forces of flight for a Phawngpui hawk

mass = 1.5       # kg (typical hawk)
g = 9.81         # m/s² (gravitational acceleration)
weight = mass * g

print("FOUR FORCES OF HAWK FLIGHT")
print("=" * 50)
print(f"Hawk mass: {mass} kg")
print(f"Weight: {weight:.1f} N")
print()

# Different flight conditions
conditions = [
    ("Level gliding", weight, weight * 0.05, 0, weight * 0.05),
    ("Climbing in thermal", weight * 1.3, weight, 0, weight * 0.04),
    ("Diving on prey", weight * 0.3, weight, 0, weight * 0.3),
    ("Flapping flight", weight, weight, weight * 0.06, weight * 0.06),
    ("Hovering (kestrel)", weight, weight, 0, 0),
]

print(f"{'Condition':<22} {'Lift':>7} {'Weight':>7} {'Thrust':>7} {'Drag':>7} {'Vertical':>10} {'Horizontal':>10}")
print("-" * 75)

for name, lift, w, thrust, drag in conditions:
    vert = "climbing" if lift > w * 1.01 else "descending" if lift < w * 0.99 else "level"
    horiz = "accel" if thrust > drag * 1.01 else "decel" if thrust < drag * 0.99 else "constant"
    print(f"{name:<22} {lift:>7.1f} {w:>7.1f} {thrust:>7.2f} {drag:>7.2f} {vert:>10} {horiz:>10}")

# Glide ratio calculation
print(f"\
Glide Ratio Calculation:")
for speed in [10, 15, 20, 25]:
    # Simplified drag model
    drag = 0.5 * 1.225 * speed**2 * 0.02 * 0.3  # rho * v² * Cd * A
    glide_angle = drag / weight  # radians (small angle)
    glide_ratio = 1 / glide_angle
    sink_rate = speed * glide_angle

    print(f"  Speed {speed} m/s: drag={drag:.2f}N, "
          f"glide ratio={glide_ratio:.0f}:1, "
          f"sink rate={sink_rate:.2f} m/s")`,
      challenge: 'A hawk spots prey 500 meters away and 100 meters below. What minimum glide ratio does it need to reach the prey without flapping? If its glide ratio is 15:1, can it make it?',
      successHint: 'You learned the four forces of flight — the framework for understanding everything from paper airplanes to jetliners. The hawk over Blue Mountain demonstrates that flight does not require engines — just the right balance of forces.',
    },
    {
      title: 'Thermals — invisible elevators in the sky',
      concept: `A **thermal** is a column of rising warm air. The sun heats the ground unevenly — dark rocks, bare soil, and asphalt absorb more heat than forests or water. The heated air rises because it is less dense than surrounding cooler air.

Thermal properties:
- **Diameter**: 100-500 meters
- **Vertical speed**: 1-5 m/s (up to 10 m/s in strong thermals)
- **Height**: from ground level to 1000-3000 meters
- **Shape**: roughly cylindrical with a warm core and cooler edges

The buoyancy force driving a thermal:
\`F_buoyancy = ρ_ambient × g × V × (T_thermal - T_ambient) / T_ambient\`

Hawks detect thermals by feel (turbulence at the thermal edge) and by watching other birds circling in the column.

📚 *We model temperature differences to calculate buoyancy. The key insight is that a few degrees of temperature difference creates enough lift to carry a heavy bird upward.*`,
      analogy: 'A thermal is like an invisible escalator in the sky. The warm ground heats the air, which rises like a bubble in water. Hawks step onto this escalator and ride it upward without flapping — gaining altitude for free. When the escalator ends (the thermal dissipates), the hawk glides to the next one.',
      storyConnection: 'Blue Mountain (Phawngpui) at 2,157 meters creates complex thermal patterns. The steep slopes heat unevenly — south-facing slopes get more sun and generate stronger thermals. Hawks riding these thermals can be seen circling in tight spirals, gaining hundreds of meters of altitude without a single wing flap.',
      checkQuestion: 'If a thermal rises at 3 m/s and a hawk sinks at 1 m/s (in still air), what is the hawk\'s net climb rate inside the thermal?',
      checkAnswer: 'Net climb rate = thermal rise rate - sink rate = 3 - 1 = 2 m/s. In one minute, the hawk gains 120 meters of altitude. In a strong thermal (5 m/s), the climb rate would be 4 m/s = 240 meters per minute. This is why hawks can soar for hours without flapping.',
      codeIntro: 'Model thermal formation and calculate the lift available to hawks at different altitudes.',
      code: `# Thermal model for Blue Mountain (Phawngpui)

import math

base_altitude = 2000  # meters (near summit)
T_ground = 25         # °C ground temperature
lapse_rate = 6.5      # °C per 1000m (temperature decreases with altitude)

print("THERMAL MODEL — PHAWNGPUI (BLUE MOUNTAIN)")
print("=" * 55)

# Temperature at different altitudes
print("\
Ambient temperature profile:")
for alt in range(0, 2500, 250):
    T = T_ground - lapse_rate * alt / 1000
    print(f"  {alt:5d}m: {T:5.1f}°C")

# Thermal strength at different ground temperatures
print("\
Thermal strength vs ground heating:")
print(f"{'Surface ΔT':>10} {'Rise speed':>11} {'Hawk climb':>11} {'Alt gain/min':>13}")
print("-" * 50)

for delta_T in [1, 2, 3, 5, 8, 10]:
    # Thermal rise rate from buoyancy
    T_ambient = T_ground - lapse_rate * 0.5  # at 500m AGL
    T_ambient_K = T_ambient + 273.15
    # Rise rate ≈ sqrt(2 * g * h * ΔT / T_ambient) simplified
    rise_rate = 0.8 * math.sqrt(9.81 * 500 * delta_T / T_ambient_K)

    hawk_sink = 1.0  # m/s in still air
    hawk_climb = rise_rate - hawk_sink
    alt_per_min = hawk_climb * 60

    status = "Soaring!" if hawk_climb > 0 else "Sinking"
    print(f"{delta_T:>8}°C {rise_rate:>10.1f} m/s {hawk_climb:>10.1f} m/s {alt_per_min:>10.0f} m {status}")

# Daily thermal cycle
print("\
Daily thermal cycle:")
hours = range(6, 19)
for hour in hours:
    # Sun angle drives ground heating
    sun_angle = max(0, math.sin(math.pi * (hour - 6) / 12))
    ground_heating = 8 * sun_angle  # max ΔT = 8°C at noon
    thermal_strength = 0.8 * math.sqrt(max(9.81 * 500 * ground_heating / 300, 0.01))
    bar = "█" * int(thermal_strength * 5)
    label = "BEST" if 10 <= hour <= 14 else ""
    print(f"  {hour:02d}:00  ΔT={ground_heating:4.1f}°C  Rise={thermal_strength:4.1f} m/s  {bar} {label}")`,
      challenge: 'Blue Mountain has both sun-facing (south) and shaded (north) slopes. Model the thermal difference: south slopes get 2x the solar heating. When during the day is the difference greatest? This asymmetry creates the complex soaring patterns hawks exploit.',
      successHint: 'You modeled thermal formation — the invisible energy source that makes soaring flight possible. Understanding thermals explains why hawks circle, why glider pilots seek dark patches of ground, and why Blue Mountain is a raptor highway during spring migration.',
    },
    {
      title: 'Wing shape and the lift equation',
      concept: `Lift is generated by the wing\'s **airfoil** shape. The fundamental equation:

\`L = ½ × ρ × v² × S × C_L\`

Where:
- ρ = air density (1.225 kg/m³ at sea level)
- v = airspeed (m/s)
- S = wing area (m²)
- C_L = lift coefficient (depends on angle of attack and wing shape)

The **angle of attack** (α) is the angle between the wing and the airflow:
- 0° to ~12°: C_L increases roughly linearly
- ~12° to 15°: C_L reaches maximum
- Above 15°: **stall** — lift drops suddenly as airflow separates from the wing

Hawks have **slotted wingtips** (separated primary feathers) that reduce drag and delay stall — a feature copied by modern aircraft as winglets.

📚 *We calculate lift for different speeds and angles using the lift equation. Plotting lift vs speed reveals the flight envelope — the range of conditions where flight is possible.*`,
      analogy: 'An airfoil works like your hand out a car window. Tilt your hand slightly upward (angle of attack) and the wind pushes it up (lift). Tilt too much and the air stops flowing smoothly over the top — your hand flutters chaotically (stall). The hawk\'s wing is the perfectly optimized version of your hand.',
      storyConnection: 'Hawks adjust their wing shape continuously during flight. Spreading wings wide (high area, high lift) for slow soaring in thermals. Tucking wings back (low area, low drag) for fast gliding between thermals. Fanning tail feathers for fine pitch control. Every feather is an aerodynamic surface.',
      checkQuestion: 'Why must a hawk fly faster to maintain lift at higher altitudes where air is thinner?',
      checkAnswer: 'From L = ½ρv²SC_L, if ρ decreases (thinner air), v² must increase to keep the same lift. At Blue Mountain\'s summit (2,157 m), air density is about 78% of sea level. The hawk must fly about 13% faster to generate the same lift. This is why takeoffs and landings at high altitude are more challenging.',
      codeIntro: 'Calculate lift at different speeds and altitudes for a hawk over Blue Mountain.',
      code: `# Lift calculations for a Phawngpui hawk

rho_sea = 1.225      # kg/m³ (sea level air density)
wing_area = 0.25     # m² (typical hawk)
mass = 1.5           # kg
weight = mass * 9.81 # N

# Air density at altitude
def air_density(altitude_m):
    """Simple atmospheric model."""
    return rho_sea * (1 - 2.26e-5 * altitude_m)**5.26

def lift_coeff(alpha_deg):
    """Simplified lift coefficient model."""
    if alpha_deg < 0:
        return 0.1 * alpha_deg / 5
    elif alpha_deg <= 12:
        return 0.1 + 0.1 * alpha_deg  # linear region
    elif alpha_deg <= 16:
        return 1.3 - 0.05 * (alpha_deg - 12)  # near stall
    else:
        return 0.5  # post-stall (sharp drop)

print("HAWK AERODYNAMICS — BLUE MOUNTAIN")
print("=" * 55)

# Lift vs speed at different altitudes
print("\
Minimum speed for level flight:")
for alt in [0, 500, 1000, 1500, 2000]:
    rho = air_density(alt)
    CL_max = 1.3
    v_min = (2 * weight / (rho * wing_area * CL_max))**0.5
    print(f"  {alt:5d}m (ρ={rho:.3f}): v_min = {v_min:.1f} m/s ({v_min*3.6:.0f} km/h)")

# Lift coefficient vs angle of attack
print("\
Lift coefficient vs angle of attack:")
for alpha in range(-4, 20, 2):
    CL = lift_coeff(alpha)
    bar = "█" * int(max(CL, 0) * 20)
    status = " ← STALL!" if alpha > 14 else " ← MAX LIFT" if alpha == 12 else ""
    print(f"  α={alpha:>3}°: C_L = {CL:5.2f}  {bar}{status}")

# Speed for minimum sink rate (best soaring speed)
print("\
Optimal soaring speeds at summit altitude:")
rho = air_density(2000)
for CL in [0.5, 0.8, 1.0, 1.3]:
    v = (2 * weight / (rho * wing_area * CL))**0.5
    # Drag roughly proportional to v² * (CD_0 + CL²/(pi*AR*e))
    AR = 7  # aspect ratio
    CD = 0.02 + CL**2 / (3.14159 * AR * 0.85)
    drag = 0.5 * rho * v**2 * wing_area * CD
    sink_rate = drag * v / weight  # simplified
    print(f"  C_L={CL:.1f}: v={v:.1f} m/s, drag={drag:.2f}N, sink={sink_rate:.2f} m/s")`,
      challenge: 'Calculate the "best glide speed" — the speed that maximizes horizontal distance per meter of altitude lost. This is when L/D (lift-to-drag ratio) is maximum. At what speed and angle of attack does the hawk glide farthest?',
      successHint: 'You applied the lift equation to real hawk flight. This same equation designs every wing on every aircraft. The hawks over Blue Mountain are natural aerodynamicists — millions of years of evolution have optimized their wings far beyond what human engineers achieved in the first century of flight.',
    },
    {
      title: 'Drag — the cost of moving through air',
      concept: `**Drag** is the aerodynamic resistance to motion. For a bird, total drag has two main components:

1. **Parasitic drag** (form + skin friction): increases with speed squared
   \`D_parasitic = ½ × ρ × v² × S_wet × C_D0\`

2. **Induced drag** (cost of generating lift): decreases with speed
   \`D_induced = 2 × W² / (ρ × v² × π × b² × e)\`
   Where b = wingspan and e = span efficiency factor

Total drag: \`D_total = D_parasitic + D_induced\`

The **drag polar** plots C_L vs C_D, revealing the wing\'s efficiency. The maximum L/D ratio occurs where total drag is minimum — this is the **best glide point**.

📚 *The two drag components have opposite trends: parasitic increases with speed, induced decreases. Their sum creates a U-shaped curve with a clear minimum.*`,
      analogy: 'Parasitic drag is like wading through water — the faster you go, the harder the water pushes back. Induced drag is like the wake a boat leaves — at low speed, you push a lot of water aside to stay afloat. At high speed, your hull planes and the wake shrinks. Total drag is minimized at an intermediate speed, just fast enough to reduce the wake without creating too much splash.',
      storyConnection: 'Hawks soaring over Blue Mountain fly at exactly the speed that minimizes total drag — the speed where parasitic and induced drag are equal. Flying slower would increase induced drag (wings at high angle of attack). Flying faster would increase parasitic drag. Evolution has optimized their instinctive speed selection.',
      checkQuestion: 'Why does induced drag decrease with speed?',
      checkAnswer: 'At higher speed, the wing generates the required lift at a lower angle of attack (less C_L needed). Lower C_L means less downwash behind the wing, which means less induced drag. Think of it this way: a fast-moving wing barely needs to deflect the air; a slow-moving wing must deflect it strongly, creating a larger wake (induced drag).',
      codeIntro: 'Plot the drag components and find the optimal glide speed for a hawk.',
      code: `# Drag analysis for hawk flight

mass = 1.5           # kg
weight = mass * 9.81 # N
rho = 1.1            # kg/m³ (at ~1500m altitude)
S = 0.25             # m² wing area
b = 1.2              # m wingspan
e = 0.85             # span efficiency
CD0 = 0.02           # parasitic drag coefficient

speeds = []
d_parasitic = []
d_induced = []
d_total = []
ld_ratios = []

for v_10 in range(50, 301):  # 5 to 30 m/s
    v = v_10 / 10
    q = 0.5 * rho * v**2  # dynamic pressure

    dp = q * S * CD0
    di = weight**2 / (q * 3.14159 * b**2 * e)
    dt = dp + di

    CL = weight / (q * S)
    CD = CD0 + CL**2 / (3.14159 * b**2 / S * e)
    ld = CL / CD

    speeds.append(v)
    d_parasitic.append(dp)
    d_induced.append(di)
    d_total.append(dt)
    ld_ratios.append(ld)

# Find optimal speeds
min_drag_idx = d_total.index(min(d_total))
max_ld_idx = ld_ratios.index(max(ld_ratios))

print("HAWK DRAG ANALYSIS")
print("=" * 55)
print(f"\
Best glide speed: {speeds[max_ld_idx]:.1f} m/s ({speeds[max_ld_idx]*3.6:.0f} km/h)")
print(f"Maximum L/D ratio: {max(ld_ratios):.1f}")
print(f"Minimum drag speed: {speeds[min_drag_idx]:.1f} m/s")
print(f"Minimum drag force: {min(d_total):.2f} N")

# Glide ratio = L/D
glide_ratio = max(ld_ratios)
print(f"\
Glide ratio: {glide_ratio:.0f}:1")
print(f"From 1000m height, the hawk can glide {glide_ratio:.0f} km!")
print(f"Sink rate at best glide: {weight / (max(ld_ratios) * mass):.2f} m/s")

print(f"\
Drag breakdown at key speeds:")
print(f"{'Speed':>6} {'Parasitic':>10} {'Induced':>10} {'Total':>10} {'L/D':>6}")
print("-" * 45)
for i in range(0, len(speeds), 25):
    print(f"{speeds[i]:>5.1f}  {d_parasitic[i]:>10.2f} {d_induced[i]:>10.2f} {d_total[i]:>10.2f} {ld_ratios[i]:>6.1f}")`,
      challenge: 'Hawks can change their wingspan by tucking their wings. Model a "tucked" configuration (wingspan 0.8m, area 0.15m², CD0=0.015) vs "spread" (1.2m, 0.25m², CD0=0.025). Which is better for fast travel? Which for slow soaring?',
      successHint: 'You analyzed drag components and found the optimal flight speed — the same analysis used to design every glider and commercial aircraft. The U-shaped drag curve is one of the most important results in aerodynamics, and hawks have been exploiting it for millions of years.',
    },
    {
      title: 'Glide ratio and cross-country flight',
      concept: `The **glide ratio** (L/D) determines how far a bird can travel from a given height:

\`Horizontal distance = Height × Glide ratio\`

For cross-country flight (traveling long distances), the strategy is:
1. **Circle in a thermal** to gain altitude (climbing phase)
2. **Glide toward the next thermal** (cruise phase)
3. Repeat

The **average cross-country speed** depends on:
- Thermal strength (climb rate)
- Glide ratio (distance per meter of altitude)
- Time spent circling vs gliding

The **MacCready theory** determines optimal glide speed: fly faster than best-glide-speed in strong thermals (you can afford to lose altitude faster because the next climb will be strong).

📚 *We calculate cross-country performance by combining climb rates and glide ratios. Simple arithmetic reveals the surprisingly efficient long-distance travel of soaring birds.*`,
      analogy: 'Cross-country soaring is like driving a car that refuels at specific gas stations (thermals). Between stations, you can drive economically (slow, best mileage) or fast (lower mileage but faster overall if the next station is guaranteed). The MacCready speed is the optimal driving speed given the expected distance to the next station.',
      storyConnection: 'Hawks migrating over the hills of Mizoram use the Blue Mountain thermals as stepping stones. They climb in one thermal, glide to the next, and repeat — covering hundreds of kilometers per day without flapping. The valleys between mountains are "blue holes" (no thermals) that hawks must cross using their glide ratio alone.',
      checkQuestion: 'A hawk climbs at 3 m/s for 5 minutes (gaining 900 m), then glides at 15:1 ratio. How far can it travel before it needs another thermal?',
      checkAnswer: 'Horizontal distance = 900 m × 15 = 13,500 m = 13.5 km. If glide speed is 15 m/s, glide time = 900/1.0 ÷ 1 = 900 seconds = 15 minutes (at 1 m/s sink rate). Total time for one thermal-glide cycle: 5 + 15 = 20 minutes for 13.5 km. Average speed = 13.5 × 3 = 40.5 km/h.',
      codeIntro: 'Calculate cross-country performance for hawks migrating over Mizoram\'s mountains.',
      code: `# Cross-country soaring performance

glide_ratio = 15     # typical hawk
sink_rate = 1.0      # m/s at best glide
glide_speed = 15     # m/s at best glide

print("CROSS-COUNTRY SOARING — MIZORAM MIGRATION")
print("=" * 55)

# Scenario: hawk migrating across Mizoram (200 km)
total_distance = 200  # km

thermal_strengths = [1.5, 2.5, 3.5, 5.0]

print(f"\
Migration distance: {total_distance} km")
print(f"Glide ratio: {glide_ratio}:1, Sink rate: {sink_rate} m/s")
print()
print(f"{'Thermal':>8} {'Climb':>6} {'Alt/cycle':>10} {'Dist/cycle':>10} {'Cycles':>7} {'Time':>8}")
print(f"{'(m/s)':>8} {'(m/s)':>6} {'(m)':>10} {'(km)':>10} {'needed':>7} {'(hours)':>8}")
print("-" * 55)

for w in thermal_strengths:
    net_climb = w - sink_rate  # net climb in thermal (still sinking)
    circle_time = 300          # 5 minutes circling
    alt_gained = net_climb * circle_time  # meters

    glide_distance = alt_gained * glide_ratio / 1000  # km
    glide_time = alt_gained / sink_rate                # seconds

    cycle_distance = glide_distance
    cycle_time = circle_time + glide_time  # seconds

    n_cycles = total_distance / cycle_distance
    total_time = n_cycles * cycle_time / 3600  # hours
    avg_speed = total_distance / total_time     # km/h

    print(f"{w:>8.1f} {net_climb:>6.1f} {alt_gained:>10.0f} {cycle_distance:>10.1f} {n_cycles:>7.0f} {total_time:>8.1f}")

# Daily migration budget
print("\
Daily migration budget (8 hours of usable thermals):")
for w in thermal_strengths:
    net_climb = w - sink_rate
    daily_km = (w - sink_rate) * 300 * glide_ratio / 1000 * (8 * 3600 / (300 + (w - sink_rate) * 300 * glide_ratio / (sink_rate * 1000) * 1000 / glide_speed))

    # Simplified
    cycle_dist = net_climb * 300 * glide_ratio / 1000
    cycle_time = 300 + net_climb * 300 / sink_rate
    daily = cycle_dist * (8 * 3600 / cycle_time)
    print(f"  Thermals at {w} m/s: ~{daily:.0f} km/day")

# Energy comparison: gliding vs flapping
flap_speed = 12  # m/s
flap_power = 15  # watts (measured for hawks)
print(f"\
Energy comparison for {total_distance}km:")
flap_time = total_distance * 1000 / flap_speed / 3600
flap_energy = flap_power * flap_time * 3600 / 1000
print(f"  Flapping: {flap_time:.1f} hours, {flap_energy:.0f} kJ of energy")
print(f"  Soaring:  ~0 kJ of muscular energy (gravity + thermals do the work)")
print(f"  Energy savings: ~99%!")`,
      challenge: 'The MacCready theory says to fly faster than best-glide-speed when thermals are strong. Calculate the optimal inter-thermal speed for different thermal strengths. At what thermal strength does it become worth flying 20% faster than best glide?',
      successHint: 'You calculated cross-country soaring performance — the same analysis used by competitive glider pilots. Hawks travel hundreds of kilometers per day using essentially zero energy. This remarkable efficiency explains why soaring birds dominate long-distance migration routes.',
    },
  ];

  return (
    <div>
      <div className="flex items-center gap-3 mb-6">
        <div className="flex items-center gap-2 bg-emerald-100 dark:bg-emerald-900/30 text-emerald-700 dark:text-emerald-300 px-4 py-2 rounded-full text-sm font-semibold">
          <Sparkles className="w-4 h-4" /> Level 1: Explorer
        </div>
        <span className="text-sm text-gray-500 dark:text-gray-400">Aerodynamics & Soaring Flight</span>
      </div>
      {!pyReady && (
        <div className="mb-8 bg-gray-50 dark:bg-gray-800 rounded-xl p-6 text-center">
          <p className="text-gray-600 dark:text-gray-300 mb-4">These exercises use Python. Click to start.</p>
          <button onClick={loadPyodide} disabled={loading} className="inline-flex items-center gap-2 bg-emerald-600 hover:bg-emerald-700 disabled:bg-gray-500 text-white px-6 py-3 rounded-full font-semibold transition-colors">
            {loading ? (<><Loader2 className="w-5 h-5 animate-spin" />{loadProgress}</>) : (<><Sparkles className="w-5 h-5" />Load Python</>)}
          </button>
        </div>
      )}
      <div className="space-y-8">
        {miniLessons.map((lesson, i) => (
          <MiniLesson key={i} id={`L1-${i + 1}`} number={i + 1}
            title={lesson.title} concept={lesson.concept} analogy={lesson.analogy}
            storyConnection={lesson.storyConnection} checkQuestion={lesson.checkQuestion}
            checkAnswer={lesson.checkAnswer} codeIntro={lesson.codeIntro}
            code={lesson.code} challenge={lesson.challenge} successHint={lesson.successHint} />
        ))}
      </div>
    </div>
  );
}
