import { lazy, ComponentType } from 'react';

interface LevelComponents {
  Level1?: ComponentType;
  Level2?: ComponentType;
  Level3?: ComponentType;
  Level4?: ComponentType;
}

// Registry maps story slugs to lazy-loaded level components
// The slug must match the `slug` field in lessons.ts
const registry: Record<string, LevelComponents> = {
  // Original 6 stories
  'girl-who-spoke-to-elephants': {Level1: lazy(() => import('../ElephantLevel1')), Level2: lazy(() => import('../ElephantLevel2')), Level3: lazy(() => import('./ElephantLevel3')), Level4: lazy(() => import('./ElephantLevel4')) },
  'dragonfly-and-the-paddy-field': {Level1: lazy(() => import('./DragonflyLevel1')), Level2: lazy(() => import('./DragonflyLevel2')), Level3: lazy(() => import('./DragonflyLevel3')), Level4: lazy(() => import('./DragonflyLevel4')) },
  'boy-who-built-a-library': {Level1: lazy(() => import('./LibraryLevel1')), Level2: lazy(() => import('./LibraryLevel2')), Level3: lazy(() => import('./LibraryLevel3')), Level4: lazy(() => import('./LibraryLevel4')) },
  'firefly-festival-of-majuli': { Level1: lazy(() => import('./FireflyLevel1')), Level2: lazy(() => import('./FireflyLevel2')), Level3: lazy(() => import('./FireflyLevel3')) },
  'river-dolphins-secret': {Level1: lazy(() => import('./DolphinLevel1')), Level2: lazy(() => import('./DolphinLevel2')), Level3: lazy(() => import('./DolphinLevel3')), Level4: lazy(() => import('./DolphinLevel4')) },
  'why-the-muga-silk-is-golden': {Level1: lazy(() => import('./MugaSilkLevel1')), Level2: lazy(() => import('./MugaSilkLevel2')), Level3: lazy(() => import('./MugaSilkLevel3')), Level4: lazy(() => import('./MugaSilkLevel4')) },

  // OurAssam folklore stories
  'tejimola-the-girl-who-became-a-plant': {Level1: lazy(() => import('./TejimolaLevel1')), Level2: lazy(() => import('./TejimolaLevel2')), Level3: lazy(() => import('./TejimolaLevel3')), Level4: lazy(() => import('./TejimolaLevel4')) },
  'golden-deer-of-kamakhya': {Level1: lazy(() => import('./GoldenDeerLevel1')), Level2: lazy(() => import('./GoldenDeerLevel2')), Level3: lazy(() => import('./GoldenDeerLevel3')), Level4: lazy(() => import('./GoldenDeerLevel4')) },
  'boy-who-talked-to-clouds': { Level1: lazy(() => import('./CloudsLevel1')), Level2: lazy(() => import('./CloudsLevel2')) },
  'how-majuli-island-was-born': {Level1: lazy(() => import('./MajuliLevel1')), Level2: lazy(() => import('./MajuliLevel2')), Level3: lazy(() => import('./MajuliLevel3')), Level4: lazy(() => import('./MajuliLevel4')) },
  'bamboo-flute-of-nagaland': {Level1: lazy(() => import('./BambooFluteLevel1')), Level2: lazy(() => import('./BambooFluteLevel2')), Level3: lazy(() => import('./BambooFluteLevel3')), Level4: lazy(() => import('./BambooFluteLevel4')) },
  'dancing-deer-of-loktak-lake': {Level1: lazy(() => import('./DancingDeerLevel1')), Level2: lazy(() => import('./DancingDeerLevel2')), Level3: lazy(() => import('./DancingDeerLevel3')), Level4: lazy(() => import('./DancingDeerLevel4')) },
  'bridge-that-grew': {Level1: lazy(() => import('./BridgeLevel1')), Level2: lazy(() => import('./BridgeLevel2')), Level3: lazy(() => import('./BridgeLevel3')), Level4: lazy(() => import('./BridgeLevel4')) },

  // 100 stories collection — mapped by story number/slug
  'the-little-boat': { Level1: lazy(() => import('./LittleBoatLevel1')), Level2: lazy(() => import('./LittleBoatLevel2')) },
  'the-hornbills-crown': {Level1: lazy(() => import('./HornbillLevel1')), Level2: lazy(() => import('./HornbillLevel2')), Level3: lazy(() => import('./HornbillLevel3')), Level4: lazy(() => import('./HornbillLevel4')) },
  'the-girl-who-painted-rain': {Level1: lazy(() => import('./PaintedRainLevel1')), Level2: lazy(() => import('./PaintedRainLevel2')), Level3: lazy(() => import('./PaintedRainLevel3')), Level4: lazy(() => import('./PaintedRainLevel4')) },
  'why-fish-jump': {Level1: lazy(() => import('./FishJumpLevel1')), Level2: lazy(() => import('./FishJumpLevel2')), Level3: lazy(() => import('./FishJumpLevel3')), Level4: lazy(() => import('./FishJumpLevel4')) },
  'tortoise-and-hare': {Level1: lazy(() => import('./TortoiseHareLevel1')), Level2: lazy(() => import('./TortoiseHareLevel2')), Level3: lazy(() => import('./TortoiseHareLevel3')), Level4: lazy(() => import('./TortoiseHareLevel4')) },
  'cloud-weaver-of-tawang': { Level1: lazy(() => import('./CloudWeaverLevel1')), Level2: lazy(() => import('./CloudWeaverLevel2')) },
  'the-magic-japi-hat': {Level1: lazy(() => import('./MagicJapiLevel1')), Level2: lazy(() => import('./MagicJapiLevel2')), Level3: lazy(() => import('./MagicJapiLevel3')), Level4: lazy(() => import('./MagicJapiLevel4')) },
  'red-panda-mask': {Level1: lazy(() => import('./RedPandaLevel1')), Level2: lazy(() => import('./RedPandaLevel2')), Level3: lazy(() => import('./RedPandaLevel3')), Level4: lazy(() => import('./RedPandaLevel4')) },
  'singing-bamboo': { Level1: lazy(() => import('./BambooWindLevel1')), Level2: lazy(() => import('./BambooWindLevel2')) },
  'clouded-leopard': {Level1: lazy(() => import('./CloudedLeopardLevel1')), Level2: lazy(() => import('./CloudedLeopardLevel2')), Level3: lazy(() => import('./CloudedLeopardLevel3')), Level4: lazy(() => import('./CloudedLeopardLevel4')) },
  'grandmothers-pitha': {Level1: lazy(() => import('./PithaLevel1')), Level2: lazy(() => import('./PithaLevel2')), Level3: lazy(() => import('./PithaLevel3')), Level4: lazy(() => import('./PithaLevel4')) },
  'lost-temple': {Level1: lazy(() => import('./LostTempleLevel1')), Level2: lazy(() => import('./LostTempleLevel2')), Level3: lazy(() => import('./LostTempleLevel3')), Level4: lazy(() => import('./LostTempleLevel4')) },
  'peacocks-dance': {Level1: lazy(() => import('./PeacockLevel1')), Level2: lazy(() => import('./PeacockLevel2')), Level3: lazy(() => import('./PeacockLevel3')), Level4: lazy(() => import('./PeacockLevel4')) },
  'elephant-mud-bath': {Level1: lazy(() => import('./MugaSilkLevel1')), Level2: lazy(() => import('./MugaSilkLevel2')), Level3: lazy(() => import('./MugaSilkLevel3')), Level4: lazy(() => import('./MugaSilkLevel4')) },
  'star-fell-deepor': { Level1: lazy(() => import('./StarDeepoorLevel1')), Level2: lazy(() => import('./StarDeepoorLevel2')) },
  'brave-mithun': {Level1: lazy(() => import('./MithunLevel1')), Level2: lazy(() => import('./MithunLevel2')), Level3: lazy(() => import('./MithunLevel3')), Level4: lazy(() => import('./MithunLevel4')) },
  'seven-sisters': {Level1: lazy(() => import('./SevenSistersLevel1')), Level2: lazy(() => import('./SevenSistersLevel2')), Level3: lazy(() => import('./SevenSistersLevel3')), Level4: lazy(() => import('./SevenSistersLevel4')) },
  'monkey-bridge': {Level1: lazy(() => import('./MonkeyBridgeLevel1')), Level2: lazy(() => import('./MonkeyBridgeLevel2')), Level3: lazy(() => import('./MonkeyBridgeLevel3')), Level4: lazy(() => import('./MonkeyBridgeLevel4')) },
  'orange-sunsets': { Level1: lazy(() => import('./OrangeSunsetsLevel1')), Level2: lazy(() => import('./OrangeSunsetsLevel2')) },
  'little-potter': {Level1: lazy(() => import('./PotterLevel1')), Level2: lazy(() => import('./PotterLevel2')), Level3: lazy(() => import('./PotterLevel3')), Level4: lazy(() => import('./PotterLevel4')) },
  'orchid-colors': {Level1: lazy(() => import('./OrchidLevel1')), Level2: lazy(() => import('./OrchidLevel2')), Level3: lazy(() => import('./OrchidLevel3')), Level4: lazy(() => import('./OrchidLevel4')) },
  'fisherman-storm': { Level1: lazy(() => import('./FishermanStormLevel1')), Level2: lazy(() => import('./FishermanStormLevel2')) },
  'cuckoo-calls-dawn': {Level1: lazy(() => import('./CuckooLevel1')), Level2: lazy(() => import('./CuckooLevel2')), Level3: lazy(() => import('./CuckooLevel3')), Level4: lazy(() => import('./CuckooLevel4')) },
  'snow-leopard': { Level1: lazy(() => import('./SnowLeopardLevel1')), Level2: lazy(() => import('./SnowLeopardLevel2')) },
  'festival-lights': {Level1: lazy(() => import('./FestivalLightsLevel1')), Level2: lazy(() => import('./FestivalLightsLevel2')), Level3: lazy(() => import('./FestivalLightsLevel3')), Level4: lazy(() => import('./FestivalLightsLevel4')) },
  'pitcher-plant': {Level1: lazy(() => import('./PitcherPlantLevel1')), Level2: lazy(() => import('./PitcherPlantLevel2')), Level3: lazy(() => import('./PitcherPlantLevel3')), Level4: lazy(() => import('./PitcherPlantLevel4')) },
  'map-maker': {Level1: lazy(() => import('./MapMakerLevel1')), Level2: lazy(() => import('./MapMakerLevel2')), Level3: lazy(() => import('./MapMakerLevel3')), Level4: lazy(() => import('./MapMakerLevel4')) },
  'bamboo-grows-fast': {Level1: lazy(() => import('./BambooGrowthLevel1')), Level2: lazy(() => import('./BambooGrowthLevel2')), Level3: lazy(() => import('./BambooGrowthLevel3')), Level4: lazy(() => import('./BambooGrowthLevel4')) },
  'kite-festival': {Level1: lazy(() => import('./KiteFestivalLevel1')), Level2: lazy(() => import('./KiteFestivalLevel2')), Level3: lazy(() => import('./KiteFestivalLevel3')), Level4: lazy(() => import('./KiteFestivalLevel4')) },
  'banyan-tree': { Level1: lazy(() => import('./BanyanTreeLevel1')), Level2: lazy(() => import('./BanyanTreeLevel2')) },
  'holi-tea-gardens': {Level1: lazy(() => import('./HoliTeaLevel1')), Level2: lazy(() => import('./HoliTeaLevel2')), Level3: lazy(() => import('./HoliTeaLevel3')), Level4: lazy(() => import('./HoliTeaLevel4')) },
  'kaziranga-grass': {Level1: lazy(() => import('./KazirGrassLevel1')), Level2: lazy(() => import('./KazirGrassLevel2')), Level3: lazy(() => import('./KazirGrassLevel3')), Level4: lazy(() => import('./KazirGrassLevel4')) },
  'postman-hills': {Level1: lazy(() => import('./PostmanHillsLevel1')), Level2: lazy(() => import('./PostmanHillsLevel2')), Level3: lazy(() => import('./PostmanHillsLevel3')), Level4: lazy(() => import('./PostmanHillsLevel4')) },
  'night-market-imphal': {Level1: lazy(() => import('./MusicDimasaLevel1')), Level2: lazy(() => import('./MusicDimasaLevel2')), Level3: lazy(() => import('./NightMarketLevel3')), Level4: lazy(() => import('./NightMarketLevel4')) },
  'turtle-mountain': {Level1: lazy(() => import('./TurtleMountainLevel1')), Level2: lazy(() => import('./TurtleMountainLevel2')), Level3: lazy(() => import('./TurtleMountainLevel3')), Level4: lazy(() => import('./TurtleMountainLevel4')) },
  'sal-tree': {Level1: lazy(() => import('./SalTreeLevel1')), Level2: lazy(() => import('./SalTreeLevel2')), Level3: lazy(() => import('./SalTreeLevel3')), Level4: lazy(() => import('./SalTreeLevel4')) },
  'rainbow-fish': {Level1: lazy(() => import('./RainbowFishLevel1')), Level2: lazy(() => import('./RainbowFishLevel2')), Level3: lazy(() => import('./RainbowFishLevel3')), Level4: lazy(() => import('./RainbowFishLevel4')) },
  'monsoon-home': {Level1: lazy(() => import('./CloudsLevel1')), Level2: lazy(() => import('./CloudsLevel2')), Level3: lazy(() => import('./CloudsLevel3')), Level4: lazy(() => import('./CloudsLevel4')) },
  'tiny-frog': {Level1: lazy(() => import('./TinyFrogLevel1')), Level2: lazy(() => import('./TinyFrogLevel2')), Level3: lazy(() => import('./TinyFrogLevel3')), Level4: lazy(() => import('./TinyFrogLevel4')) },
  'grandmother-remembered': {Level1: lazy(() => import('./MemoryGrandmaLevel1')), Level2: lazy(() => import('./MemoryGrandmaLevel2')), Level3: lazy(() => import('./MemoryGrandmaLevel3')), Level4: lazy(() => import('./MemoryGrandmaLevel4')) },
  'little-train': {Level1: lazy(() => import('./LittleTrainLevel1')), Level2: lazy(() => import('./LittleTrainLevel2')), Level3: lazy(() => import('./LittleTrainLevel3')), Level4: lazy(() => import('./LittleTrainLevel4')) },
  'music-dimasa': {Level1: lazy(() => import('./MusicDimasaLevel1')), Level2: lazy(() => import('./MusicDimasaLevel2')), Level3: lazy(() => import('./MusicDimasaLevel3')), Level4: lazy(() => import('./MusicDimasaLevel4')) },
  'silk-route': {Level1: lazy(() => import('./SilkRouteLevel1')), Level2: lazy(() => import('./SilkRouteLevel2')), Level3: lazy(() => import('./SilkRouteLevel3')), Level4: lazy(() => import('./SilkRouteLevel4')) },
  'boy-counted-butterflies': {Level1: lazy(() => import('./ButterflyCountLevel1')), Level2: lazy(() => import('./ButterflyCountLevel2')), Level3: lazy(() => import('./ButterflyCountLevel3')), Level4: lazy(() => import('./ButterflyCountLevel4')) },
  'honey-hunter': { Level1: lazy(() => import('./HoneyHunterLevel1')), Level2: lazy(() => import('./HoneyHunterLevel2')) },
  'girl-grew-forest': {Level1: lazy(() => import('./GirlForestLevel1')), Level2: lazy(() => import('./GirlForestLevel2')), Level3: lazy(() => import('./GirlForestLevel3')), Level4: lazy(() => import('./GirlForestLevel4')) },
  'firewalker': {Level1: lazy(() => import('./FirewalkerLevel1')), Level2: lazy(() => import('./FirewalkerLevel2')), Level3: lazy(() => import('./FirewalkerLevel3')), Level4: lazy(() => import('./FirewalkerLevel4')) },
  'frogs-sing-rain': {Level1: lazy(() => import('./FrogSingLevel1')), Level2: lazy(() => import('./FrogSingLevel2')), Level3: lazy(() => import('./FrogSingLevel3')), Level4: lazy(() => import('./FrogSingLevel4')) },
  'cloud-namer': {Level1: lazy(() => import('./CloudNamerLevel1')), Level2: lazy(() => import('./CloudNamerLevel2')), Level3: lazy(() => import('./CloudNamerLevel3')), Level4: lazy(() => import('./CloudNamerLevel4')) },
  'basket-weaver': { Level1: lazy(() => import('./BasketWeaverLevel1')), Level2: lazy(() => import('./BasketWeaverLevel2')) },
  'seed-keeper': {Level1: lazy(() => import('./SeedKeeperLevel1')), Level2: lazy(() => import('./SeedKeeperLevel2')), Level3: lazy(() => import('./SeedKeeperLevel3')), Level4: lazy(() => import('./SeedKeeperLevel4')) },
  'kingfisher-blue': {Level1: lazy(() => import('./KingfisherLevel1')), Level2: lazy(() => import('./KingfisherLevel2')), Level3: lazy(() => import('./KingfisherLevel3')), Level4: lazy(() => import('./KingfisherLevel4')) },
  'owl-wisest': {Level1: lazy(() => import('./OwlLevel1')), Level2: lazy(() => import('./OwlLevel2')), Level3: lazy(() => import('./OwlLevel3')), Level4: lazy(() => import('./OwlLevel4')) },
  'flying-squirrel': {Level1: lazy(() => import('./LittleBoatLevel1')), Level2: lazy(() => import('./LittleBoatLevel2')), Level3: lazy(() => import('./FlyingSquirrelLevel3')), Level4: lazy(() => import('./FlyingSquirrelLevel4')) },
  'night-jasmine': {Level1: lazy(() => import('./NightJasmineLevel1')), Level2: lazy(() => import('./NightJasmineLevel2')), Level3: lazy(() => import('./NightJasmineLevel3')), Level4: lazy(() => import('./NightJasmineLevel4')) },
  'woodpecker-drum': { Level1: lazy(() => import('./WoodpeckerLevel1')), Level2: lazy(() => import('./WoodpeckerLevel2')) },
  'tiger-whisker': { Level1: lazy(() => import('./TigerWhiskerLevel1')), Level2: lazy(() => import('./TigerWhiskerLevel2')) },
  'river-braid': { Level1: lazy(() => import('./RiverBraidLevel1')), Level2: lazy(() => import('./RiverBraidLevel2')) },
  'lotus-float': {Level1: lazy(() => import('./LotusFloatLevel1')), Level2: lazy(() => import('./LotusFloatLevel2')), Level3: lazy(() => import('./LotusFloatLevel3')), Level4: lazy(() => import('./LotusFloatLevel4')) },
  'first-rice': {Level1: lazy(() => import('./RicePlantedLevel1')), Level2: lazy(() => import('./RicePlantedLevel2')), Level3: lazy(() => import('./RicePlantedLevel3')), Level4: lazy(() => import('./RicePlantedLevel4')) },
  'dhol-drum': {Level1: lazy(() => import('./DholDrumLevel1')), Level2: lazy(() => import('./DholDrumLevel2')), Level3: lazy(() => import('./DholDrumLevel3')), Level4: lazy(() => import('./DholDrumLevel4')) },
  'eri-silk': {Level1: lazy(() => import('./EriSilkLevel1')), Level2: lazy(() => import('./EriSilkLevel2')), Level3: lazy(() => import('./EriSilkLevel3')), Level4: lazy(() => import('./EriSilkLevel4')) },
  'little-chef': {Level1: lazy(() => import('./LittleChefLevel1')), Level2: lazy(() => import('./LittleChefLevel2')), Level3: lazy(() => import('./LittleChefLevel3')), Level4: lazy(() => import('./LittleChefLevel4')) },
  'siang-river': { Level1: lazy(() => import('./RiverBraidLevel1')), Level2: lazy(() => import('./RiverBraidLevel2')) },
  'fireflies-dont-burn': {Level1: lazy(() => import('./FireflyLevel1')), Level2: lazy(() => import('./FireflyLevel2')), Level3: lazy(() => import('./FireflyLevel3')), Level4: lazy(() => import('./FireflyLevel4')) },
  'orange-sunsets-assam': { Level1: lazy(() => import('./OrangeSunsetsLevel1')), Level2: lazy(() => import('./OrangeSunsetsLevel2')), Level3: lazy(() => import('./OrangeSunsetsLevel3')), Level4: lazy(() => import('./OrangeSunsetsLevel4')) },
  'fishermans-daughter-storm': {Level1: lazy(() => import('./FishermanStormLevel1')), Level2: lazy(() => import('./FishermanStormLevel2')), Level3: lazy(() => import('./FishermanStormLevel3')), Level4: lazy(() => import('./FishermanStormLevel4')) },
  'snow-leopards-promise': {Level1: lazy(() => import('./SnowLeopardLevel1')), Level2: lazy(() => import('./SnowLeopardLevel2')), Level3: lazy(() => import('./SnowLeopardLevel3')), Level4: lazy(() => import('./SnowLeopardLevel4')) },
  'map-makers-granddaughter': {Level1: lazy(() => import('./MapMakerLevel1')), Level2: lazy(() => import('./MapMakerLevel2')), Level3: lazy(() => import('./MapMakerLevel3')), Level4: lazy(() => import('./MapMakerLevel4')) },
  'old-banyan-trees-stories': {Level1: lazy(() => import('./BanyanTreeLevel1')), Level2: lazy(() => import('./BanyanTreeLevel2')), Level3: lazy(() => import('./BanyanTreeLevel3')), Level4: lazy(() => import('./BanyanTreeLevel4')) },
  'tigers-whisker': { Level1: lazy(() => import('./TigerWhiskerLevel1')), Level2: lazy(() => import('./TigerWhiskerLevel2')) },
  'basket-weavers-song': {Level1: lazy(() => import('./BasketWeaverLevel1')), Level2: lazy(() => import('./BasketWeaverLevel2')), Level3: lazy(() => import('./BasketWeaverLevel3')), Level4: lazy(() => import('./BasketWeaverLevel4')) },
  'honey-hunters-lesson': {Level1: lazy(() => import('./HoneyHunterLevel1')), Level2: lazy(() => import('./HoneyHunterLevel2')), Level3: lazy(() => import('./HoneyHunterLevel3')), Level4: lazy(() => import('./HoneyHunterLevel4')) },
  'bamboo-taught-wind': {Level1: lazy(() => import('./BambooWindLevel1')), Level2: lazy(() => import('./BambooWindLevel2')), Level3: lazy(() => import('./BambooWindLevel3')), Level4: lazy(() => import('./BambooWindLevel4')) },
  'woodpeckers-drum': {Level1: lazy(() => import('./WoodpeckerLevel1')), Level2: lazy(() => import('./WoodpeckerLevel2')), Level3: lazy(() => import('./WoodpeckerLevel3')), Level4: lazy(() => import('./WoodpeckerLevel4')) },
  'talking-parrot-hajo': {Level1: lazy(() => import('./TalkingParrotLevel1')), Level2: lazy(() => import('./TalkingParrotLevel2')), Level3: lazy(() => import('./TalkingParrotLevel3')), Level4: lazy(() => import('./TalkingParrotLevel4')) },
  'secret-garden-loktak': {Level1: lazy(() => import('./SecretGardenLevel1')), Level2: lazy(() => import('./SecretGardenLevel2')), Level3: lazy(() => import('./DancingDeerLevel3')), Level4: lazy(() => import('./DancingDeerLevel4')) },
  'stars-ziro-valley': {Level1: lazy(() => import('./StarsZiroLevel1')), Level2: lazy(() => import('./StarsZiroLevel2')), Level3: lazy(() => import('./StarDeepoorLevel3')), Level4: lazy(() => import('./StarDeepoorLevel4')) },
  'mishing-fish': {Level1: lazy(() => import('./MishingFishLevel1')), Level2: lazy(() => import('./MishingFishLevel2')), Level3: lazy(() => import('./MishingFishLevel3')), Level4: lazy(() => import('./MishingFishLevel4')) },
  'coconut-jackfruit': {Level1: lazy(() => import('./CoconutJackfruitLevel1')), Level2: lazy(() => import('./CoconutJackfruitLevel2')), Level3: lazy(() => import('./CoconutJackfruitLevel3')), Level4: lazy(() => import('./CoconutJackfruitLevel4')) },
  'paper-umbrella': {Level1: lazy(() => import('./PaperUmbrellaLevel1')), Level2: lazy(() => import('./PaperUmbrellaLevel2')), Level3: lazy(() => import('./PaperUmbrellaLevel3')), Level4: lazy(() => import('./PaperUmbrellaLevel4')) },
  'witch-doctor': {Level1: lazy(() => import('./WitchDoctorLevel1')), Level2: lazy(() => import('./WitchDoctorLevel2')), Level3: lazy(() => import('./WitchDoctorLevel3')), Level4: lazy(() => import('./WitchDoctorLevel4')) },
  'turtle-slow': {Level1: lazy(() => import('./TurtleSlowLevel1')), Level2: lazy(() => import('./TurtleSlowLevel2')), Level3: lazy(() => import('./TurtleSlowLevel3')), Level4: lazy(() => import('./TurtleSlowLevel4')) },
  'market-day-tura': {Level1: lazy(() => import('./MarketDayLevel1')), Level2: lazy(() => import('./MarketDayLevel2')), Level3: lazy(() => import('./MarketDayLevel3')), Level4: lazy(() => import('./MarketDayLevel4')) },
  'elephant-corridor': {Level1: lazy(() => import('./ElephantCorridorLevel1')), Level2: lazy(() => import('./ElephantCorridorLevel2')), Level3: lazy(() => import('./ElephantCorridorLevel3')), Level4: lazy(() => import('./ElephantCorridorLevel4')) },
  'golden-hilsa': {Level1: lazy(() => import('./GoldenHilsaLevel1')), Level2: lazy(() => import('./GoldenHilsaLevel2')), Level3: lazy(() => import('./GoldenHilsaLevel3')), Level4: lazy(() => import('./GoldenHilsaLevel4')) },
  'cloud-refused-rain': {Level1: lazy(() => import('./CloudRefusedLevel1')), Level2: lazy(() => import('./CloudRefusedLevel2')), Level3: lazy(() => import('./CloudRefusedLevel3')), Level4: lazy(() => import('./CloudRefusedLevel4')) },
  'friendship-bridge': {Level1: lazy(() => import('./FriendshipBridgeLevel1')), Level2: lazy(() => import('./FriendshipBridgeLevel2')), Level3: lazy(() => import('./FriendshipBridgeLevel3')), Level4: lazy(() => import('./FriendshipBridgeLevel4')) },
  'mountain-echoes': {Level1: lazy(() => import('./MountainEchoesLevel1')), Level2: lazy(() => import('./MountainEchoesLevel2')), Level3: lazy(() => import('./MountainEchoesLevel3')), Level4: lazy(() => import('./MountainEchoesLevel4')) },
  'dancer-floating-market': {Level1: lazy(() => import('./DancerFloatingLevel1')), Level2: lazy(() => import('./DancerFloatingLevel2')), Level3: lazy(() => import('./DancerFloatingLevel3')), Level4: lazy(() => import('./DancerFloatingLevel4')) },
  'ferrymans-riddle': {Level1: lazy(() => import('./FerrymanLevel1')), Level2: lazy(() => import('./FerrymanLevel2')), Level3: lazy(() => import('./FerrymanLevel3')), Level4: lazy(() => import('./FerrymanLevel4')) },
  'wild-orchids-trees': {Level1: lazy(() => import('./WildOrchidsLevel1')), Level2: lazy(() => import('./WildOrchidsLevel2')), Level3: lazy(() => import('./WildOrchidsLevel3')), Level4: lazy(() => import('./WildOrchidsLevel4')) },
  'guwahati-name': {Level1: lazy(() => import('./GuwahatiNameLevel1')), Level2: lazy(() => import('./GuwahatiNameLevel2')), Level3: lazy(() => import('./GuwahatiNameLevel3')), Level4: lazy(() => import('./GuwahatiNameLevel4')) },
  'story-garden': {Level1: lazy(() => import('./StoryGardenLevel1')), Level2: lazy(() => import('./StoryGardenLevel2')), Level3: lazy(() => import('./StoryGardenLevel3')), Level4: lazy(() => import('./StoryGardenLevel4')) },

  // 7 missing stories added
  'little-monk-tawang': {Level1: lazy(() => import('./CloudWeaverLevel1')), Level2: lazy(() => import('./CloudWeaverLevel2')), Level3: lazy(() => import('./CloudWeaverLevel3')), Level4: lazy(() => import('./CloudWeaverLevel4')) },
  'moonlit-boat-race': { Level1: lazy(() => import('./LittleBoatLevel1')), Level2: lazy(() => import('./LittleBoatLevel2')) },
  'little-river-joined': {Level1: lazy(() => import('./RiverBraidLevel1')), Level2: lazy(() => import('./RiverBraidLevel2')), Level3: lazy(() => import('./RiverBraidLevel3')), Level4: lazy(() => import('./RiverBraidLevel4')) },
  'haflong-blue-mountains': {Level1: lazy(() => import('./OrangeSunsetsLevel1')), Level2: lazy(() => import('./OrangeSunsetsLevel2')), Level3: lazy(() => import('./OrangeSunsetsLevel3')), Level4: lazy(() => import('./OrangeSunsetsLevel4')) },
  'girl-python': {Level1: lazy(() => import('./TigerWhiskerLevel1')), Level2: lazy(() => import('./TigerWhiskerLevel2')), Level3: lazy(() => import('./TigerWhiskerLevel3')), Level4: lazy(() => import('./TigerWhiskerLevel4')) },
  'kite-eagle-dimapur': { Level1: lazy(() => import('./LittleBoatLevel1')), Level2: lazy(() => import('./LittleBoatLevel2')) },
  'boy-raced-brahmaputra': {Level1: lazy(() => import('./LittleBoatLevel1')), Level2: lazy(() => import('./LittleBoatLevel2')), Level3: lazy(() => import('./LittleBoatLevel3')), Level4: lazy(() => import('./LittleBoatLevel4')) },

  // Mythology stories
  'churning-of-the-ocean': { Level1: lazy(() => import('./ChurningOceanLevel1')), Level2: lazy(() => import('./ChurningOceanLevel2')), Level3: lazy(() => import('./ChurningOceanLevel3')), Level4: lazy(() => import('./ChurningOceanLevel4')) },
  'sand-mandala': { Level1: lazy(() => import('./SandMandalaLevel1')), Level2: lazy(() => import('./SandMandalaLevel2')), Level3: lazy(() => import('./SandMandalaLevel3')), Level4: lazy(() => import('./SandMandalaLevel4')) },
  'david-and-goliath': { Level1: lazy(() => import('./DavidGoliathLevel1')), Level2: lazy(() => import('./DavidGoliathLevel2')), Level3: lazy(() => import('./DavidGoliathLevel3')), Level4: lazy(() => import('./DavidGoliathLevel4')) },
  'geometry-of-alhambra': { Level1: lazy(() => import('./AlhambraLevel1')), Level2: lazy(() => import('./AlhambraLevel2')), Level3: lazy(() => import('./AlhambraLevel3')), Level4: lazy(() => import('./AlhambraLevel4')) },
  'the-astrolabe': { Level1: lazy(() => import('./AstrolabeLevel1')), Level2: lazy(() => import('./AstrolabeLevel2')), Level3: lazy(() => import('./AstrolabeLevel3')), Level4: lazy(() => import('./AstrolabeLevel4')) },
  'ravanas-ten-heads': { Level1: lazy(() => import('./RavanaLevel1')), Level2: lazy(() => import('./RavanaLevel2')), Level3: lazy(() => import('./RavanaLevel3')), Level4: lazy(() => import('./RavanaLevel4')) },
  'hanuman-lifted-mountain': { Level1: lazy(() => import('./HanumanMountainLevel1')), Level2: lazy(() => import('./HanumanMountainLevel2')), Level3: lazy(() => import('./HanumanMountainLevel3')), Level4: lazy(() => import('./HanumanMountainLevel4')) },
  'bodhi-tree': { Level1: lazy(() => import('./BodhiTreeLevel1')), Level2: lazy(() => import('./BodhiTreeLevel2')), Level3: lazy(() => import('./BodhiTreeLevel3')), Level4: lazy(() => import('./BodhiTreeLevel4')) },
  'noahs-ark': { Level1: lazy(() => import('./NoahsArkLevel1')), Level2: lazy(() => import('./NoahsArkLevel2')), Level3: lazy(() => import('./NoahsArkLevel3')), Level4: lazy(() => import('./NoahsArkLevel4')) },
  'monastery-bells': { Level1: lazy(() => import('./MonasteryBellsLevel1')), Level2: lazy(() => import('./MonasteryBellsLevel2')), Level3: lazy(() => import('./MonasteryBellsLevel3')), Level4: lazy(() => import('./MonasteryBellsLevel4')) },
  'wheel-of-dharma': { Level1: lazy(() => import('./DharmaWheelLevel1')), Level2: lazy(() => import('./DharmaWheelLevel2')), Level3: lazy(() => import('./DharmaWheelLevel3')), Level4: lazy(() => import('./DharmaWheelLevel4')) },
  'angulimala-change': { Level1: lazy(() => import('./AngulimalaLevel1')), Level2: lazy(() => import('./AngulimalaLevel2')), Level3: lazy(() => import('./AngulimalaLevel3')), Level4: lazy(() => import('./AngulimalaLevel4')) },
  'pushpaka-vimana': { Level1: lazy(() => import('./VimanaLevel1')), Level2: lazy(() => import('./VimanaLevel2')), Level3: lazy(() => import('./VimanaLevel3')), Level4: lazy(() => import('./VimanaLevel4')) },
  'agni-science-of-fire': { Level1: lazy(() => import('./AgniLevel1')), Level2: lazy(() => import('./AgniLevel2')), Level3: lazy(() => import('./AgniLevel3')), Level4: lazy(() => import('./AgniLevel4')) },
  'tower-of-babel': { Level1: lazy(() => import('./BabelLevel1')), Level2: lazy(() => import('./BabelLevel2')), Level3: lazy(() => import('./BabelLevel3')), Level4: lazy(() => import('./BabelLevel4')) },
  'al-khwarizmi-algebra': { Level1: lazy(() => import('./AlKhwarizmiLevel1')), Level2: lazy(() => import('./AlKhwarizmiLevel2')), Level3: lazy(() => import('./AlKhwarizmiLevel3')), Level4: lazy(() => import('./AlKhwarizmiLevel4')) },
  'star-of-bethlehem': { Level1: lazy(() => import('./BethlehemStarLevel1')), Level2: lazy(() => import('./BethlehemStarLevel2')), Level3: lazy(() => import('./BethlehemStarLevel3')), Level4: lazy(() => import('./BethlehemStarLevel4')) },
  'parting-red-sea': { Level1: lazy(() => import('./RedSeaLevel1')), Level2: lazy(() => import('./RedSeaLevel2')), Level3: lazy(() => import('./RedSeaLevel3')), Level4: lazy(() => import('./RedSeaLevel4')) },
  'well-of-zamzam': { Level1: lazy(() => import('./ZamzamLevel1')), Level2: lazy(() => import('./ZamzamLevel2')), Level3: lazy(() => import('./ZamzamLevel3')), Level4: lazy(() => import('./ZamzamLevel4')) },
  'muezzins-call': { Level1: lazy(() => import('./MuezzinLevel1')), Level2: lazy(() => import('./MuezzinLevel2')), Level3: lazy(() => import('./MuezzinLevel3')), Level4: lazy(() => import('./MuezzinLevel4')) },
};

export function getLevelComponents(slug: string): LevelComponents {
  return registry[slug] || {};
}
