import { useState, useRef, useCallback } from 'react';
import { Loader2, Sparkles } from 'lucide-react';
import MiniLesson from '../MiniLesson';
import { usePyodide } from '../../contexts/PyodideContext';

export default function KiteFestivalLevel1() {
  const { pyodideRef, load: loadPyodide, ready: pyReady, state: pyState, loadProgress } = usePyodide();
  const loading = pyState === 'loading';

  const miniLessons = [
    {
      title: 'What makes things fly — lift, drag, thrust, and weight',
      concept: `Four forces act on every flying object — a kite, a bird, a plane, a drone:

1. **Weight** (W): gravity pulling down. W = mg (mass × gravitational acceleration)
2. **Lift** (L): the upward force generated by air flowing over a surface. Perpendicular to airflow.
3. **Drag** (D): air resistance opposing motion. Parallel to airflow, opposing direction of travel.
4. **Thrust** (T): the forward force from an engine, propeller, or (for a kite) the string tension + wind.

For steady, level flight: **L = W** and **T = D**

A kite is special because it has no engine. Its "thrust" comes from the wind pushing against its surface. The string provides a backward-and-downward force that, combined with wind force, resolves into lift. Without the string, a kite would tumble away — it needs the string tension to maintain its angle to the wind.

The force balance on a kite:
- Wind creates a total aerodynamic force (combination of lift and drag) on the kite surface
- The string pulls back and down
- Gravity pulls down
- At equilibrium, the kite hangs at a stable angle where all forces balance`,
      analogy: 'A kite is like a person leaning into a strong wind. Your body (kite surface) pushes against the wind, and someone holds your hand from behind (the string). The wind pushes you up and back; the hand pulls you back and down; gravity pulls you down. When all three balance, you lean at a stable angle. Let go of the hand (cut the string), and you tumble.',
      storyConnection: 'At the Guwahati kite festival, hundreds of kites dance over the Brahmaputra. Each kite is a solved physics problem: the flyer adjusts string tension to change the kite\'s angle, which changes the lift-to-drag ratio, which changes altitude and stability. The best flyers intuitively understand force balance without knowing the equations.',
      checkQuestion: 'A kite is flying steadily at 50 meters altitude. The wind suddenly stops. What happens?',
      checkAnswer: 'The aerodynamic force (lift + drag from wind) instantly drops to zero. Only gravity and string tension remain. Gravity pulls the kite down. The string goes slack because there is no longer any horizontal wind force to keep it taut. The kite falls nearly straight down, fluttering, until it lands. Without wind, a kite has no source of lift — it is just a decorated piece of paper.',
      codeIntro: 'Visualize the four forces on a kite and how they balance.',
      code: `import numpy as np
import matplotlib.pyplot as plt

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 6))
fig.patch.set_facecolor('#1f2937')

# --- Force diagram on a kite ---
ax1.set_facecolor('#111827')

# Kite shape
kite_x = [0, -0.8, 0, 0.8, 0]
kite_y = [1.5, 0.5, -0.2, 0.5, 1.5]
ax1.fill(kite_x, kite_y, color='#ef4444', alpha=0.3)
ax1.plot(kite_x, kite_y, color='#ef4444', linewidth=2)

# Force arrows
forces = [
    (0, 0.65, 0, 1.2, '#22c55e', 'Lift'),      # up
    (0, 0.65, 0, -1.0, '#3b82f6', 'Weight'),    # down
    (0, 0.65, -0.8, 0, '#f59e0b', 'Drag'),      # backward
    (0, 0.65, 0.6, -0.5, '#a855f7', 'String\\ntension'), # string
    (0, 0.65, 1.0, 0.3, '#06b6d4', 'Wind\\nforce'),      # wind
]
for x, y, dx, dy, color, label in forces:
    ax1.annotate('', xy=(x+dx*0.8, y+dy*0.8), xytext=(x, y),
                arrowprops=dict(arrowstyle='->', color=color, lw=2.5))
    ax1.text(x+dx*0.9, y+dy*0.9, label, color=color, fontsize=9, fontweight='bold',
             ha='center' if abs(dx) < 0.5 else 'left')

# String
ax1.plot([0, -2], [-0.2, -2], color='#a855f7', linewidth=1.5, linestyle='--')
ax1.plot(-2, -2, 'o', color='white', markersize=6)
ax1.text(-2, -2.3, 'Flyer', color='white', ha='center', fontsize=8)

# Wind arrows (background)
for y_w in [0, 0.5, 1, 1.5, 2]:
    ax1.annotate('', xy=(2, y_w), xytext=(1.2, y_w),
                arrowprops=dict(arrowstyle='->', color='#06b6d4', lw=1, alpha=0.3))
ax1.text(1.6, 2.3, 'Wind →', color='#06b6d4', fontsize=10)

ax1.set_xlim(-3, 3); ax1.set_ylim(-3, 3)
ax1.set_aspect('equal')
ax1.set_title('Forces on a Kite', color='white', fontsize=13)
ax1.set_xticks([]); ax1.set_yticks([])

# --- Effect of string angle on flight ---
ax2.set_facecolor('#111827')
string_angles = np.linspace(20, 80, 100)  # degrees from horizontal
wind_speed = 5  # m/s

# Simplified model: kite angle ≈ string angle
# Lift ∝ sin(angle) × v², Drag ∝ cos(angle) × v²
kite_angles = string_angles * 0.7  # kite angle relative to wind
lift = 0.5 * np.sin(np.radians(kite_angles * 2)) * wind_speed**2
drag = 0.3 * (1 - np.cos(np.radians(kite_angles))) * wind_speed**2
lift_to_drag = lift / np.maximum(drag, 0.1)

ax2.plot(string_angles, lift, color='#22c55e', linewidth=2.5, label='Lift')
ax2.plot(string_angles, drag, color='#ef4444', linewidth=2.5, label='Drag')
ax2.plot(string_angles, lift_to_drag, color='#f59e0b', linewidth=2.5, linestyle='--', label='L/D ratio')

# Mark optimal angle
opt_idx = np.argmax(lift_to_drag)
ax2.axvline(string_angles[opt_idx], color='gray', linestyle=':', alpha=0.3)
ax2.text(string_angles[opt_idx]+1, lift_to_drag.max()*0.9, f'Best angle\\n~{string_angles[opt_idx]:.0f}°',
         color='#f59e0b', fontsize=9)

ax2.set_xlabel('String angle from horizontal (°)', color='white')
ax2.set_ylabel('Force (relative)', color='white')
ax2.set_title('How String Angle Affects Flight', color='white', fontsize=13)
ax2.legend(facecolor='#1f2937', edgecolor='gray', labelcolor='white', fontsize=9)
ax2.tick_params(colors='gray')

plt.tight_layout()
plt.show()

print("Four forces of flight:")
print("  Lift (up) — from air deflection")
print("  Weight (down) — gravity")
print("  Drag (backward) — air resistance")
print("  Thrust (forward) — engine/wind")
print()
print("For a kite: wind provides thrust, string controls angle")
print("Optimal string angle balances lift and drag")`,
      challenge: 'If you double the wind speed, lift increases by 4× (it scales as v²). But drag also increases by 4×. Does the kite fly higher or at the same altitude? What determines the maximum altitude?',
      successHint: 'The four forces of flight apply to everything that flies — kites, birds, planes, rockets, even flying fish. Understanding force balance is the foundation of all aerodynamics.',
    },
    {
      title: 'Bernoulli\'s principle — the physics of lift',
      concept: `In 1738, Daniel Bernoulli discovered that **faster-moving air has lower pressure**:

**P + ½ρv² + ρgh = constant** (along a streamline)

For horizontal flow (ignore gravity): **P₁ + ½ρv₁² = P₂ + ½ρv₂²**

This means: if air speeds up (v increases), pressure drops (P decreases).

How this creates lift on a kite or wing:
1. Wind hits the kite at an angle (the **angle of attack**)
2. Air flowing over the top surface is deflected upward, accelerating
3. Air flowing under the bottom is slowed and compressed
4. Faster air above → lower pressure above
5. Slower air below → higher pressure below
6. Pressure difference × surface area = **lift force**

However, Bernoulli alone doesn't fully explain lift. **Newton's third law** is equally important: the kite deflects air downward, so by Newton's third law, the air pushes the kite upward. Most real lift comes from this momentum transfer, with Bernoulli providing a complementary description.

The lift equation: **L = ½ρv²CₗA**
- ρ = air density (~1.225 kg/m³ at sea level)
- v = airspeed
- Cₗ = lift coefficient (depends on shape and angle of attack)
- A = wing/kite area`,
      analogy: 'Hold a spoon under a running faucet with its curved back facing the water. The water curves around the spoon and, surprisingly, the spoon gets pulled INTO the stream rather than pushed away. This is Bernoulli at work: the fast-moving water creates low pressure on the curved surface, pulling the spoon in. A wing or kite does the same thing with air.',
      storyConnection: 'Every kite at the Guwahati festival rides on Bernoulli\'s principle. The wind hitting the kite\'s angled surface creates a pressure difference: lower pressure on the front/top, higher on the back/bottom. This pressure difference, multiplied over the kite\'s area, is what lifts it into the sky. The larger the kite, the more lift — which is why festival kites can be enormous.',
      checkQuestion: 'An airplane wing is curved on top and flatter on the bottom. Does this mean a plane can\'t fly upside down?',
      checkAnswer: 'Planes CAN and DO fly upside down (aerobatic planes do it regularly). When inverted, the curved surface is on the bottom, which would normally generate downward "lift." But the pilot compensates by increasing the angle of attack — tilting the nose up. At sufficient angle of attack, the momentum deflection (Newton\'s third law) generates enough upward force to keep the plane flying. Bernoulli helps, but angle of attack is the dominant factor.',
      codeIntro: 'Simulate airflow around a kite and visualize the pressure distribution.',
      code: `import numpy as np
import matplotlib.pyplot as plt

fig, axes = plt.subplots(2, 2, figsize=(14, 8))
fig.patch.set_facecolor('#1f2937')

# --- Bernoulli's equation visualization ---
ax = axes[0, 0]; ax.set_facecolor('#111827')
# Venturi effect: narrowing tube speeds up flow, drops pressure
x = np.linspace(0, 10, 200)
tube_top = 1.5 - 0.5 * np.exp(-0.5*((x-5)/1.5)**2)
tube_bot = -1.5 + 0.5 * np.exp(-0.5*((x-5)/1.5)**2)
velocity = 1.5 / (tube_top - tube_bot)  # continuity: v ∝ 1/area
pressure = 1 - 0.5 * velocity**2 / velocity.max()**2  # Bernoulli

ax.fill_between(x, tube_top, 2, color='#374151')
ax.fill_between(x, tube_bot, -2, color='#374151')
ax.plot(x, tube_top, color='white', linewidth=1.5)
ax.plot(x, tube_bot, color='white', linewidth=1.5)

# Streamlines
for y0 in np.linspace(-1.2, 1.2, 8):
    scale = y0 / 1.2 if abs(y0) > 0 else 0
    y_stream = y0 * (tube_top if y0 > 0 else -tube_bot) / 1.5
    ax.plot(x, y_stream, color='#06b6d4', linewidth=0.5, alpha=0.5)

# Flow direction arrows
for xi in [2, 5, 8]:
    ax.annotate('', xy=(xi+0.3, 0), xytext=(xi-0.3, 0),
                arrowprops=dict(arrowstyle='->', color='#06b6d4', lw=1.5))

# Pressure color
ax.text(2, 1.7, 'High P\\nSlow', color='#ef4444', fontsize=8, ha='center')
ax.text(5, 0.8, 'Low P\\nFast', color='#22c55e', fontsize=8, ha='center')
ax.text(8, 1.7, 'High P\\nSlow', color='#ef4444', fontsize=8, ha='center')

ax.set_xlim(0, 10); ax.set_ylim(-2, 2)
ax.set_title('Bernoulli: Fast Flow = Low Pressure', color='white', fontsize=11)
ax.set_xticks([]); ax.set_yticks([])

# --- Lift equation: L vs wind speed ---
ax = axes[0, 1]; ax.set_facecolor('#111827')
v = np.linspace(0, 15, 100)  # m/s
rho = 1.225
Cl = 0.8  # typical kite lift coefficient
areas = [0.5, 1.0, 2.0]  # m²
for A in areas:
    L = 0.5 * rho * v**2 * Cl * A
    ax.plot(v, L, linewidth=2, label=f'Area = {A} m²')

# Mark weight of a kite (~0.2 kg = ~2N)
ax.axhline(2, color='#ef4444', linewidth=1.5, linestyle='--', label='Kite weight (0.2 kg)')
ax.text(1, 2.5, 'Min wind to fly', color='#ef4444', fontsize=8)

ax.set_xlabel('Wind speed (m/s)', color='white')
ax.set_ylabel('Lift force (N)', color='white')
ax.set_title('Lift = ½ρv²CₗA', color='white', fontsize=11)
ax.legend(facecolor='#1f2937', edgecolor='gray', labelcolor='white', fontsize=8)
ax.tick_params(colors='gray')

# --- Angle of attack effect ---
ax = axes[1, 0]; ax.set_facecolor('#111827')
aoa = np.linspace(-5, 25, 100)  # angle of attack
Cl_aoa = 0.1 * aoa  # approximately linear up to stall
Cl_aoa[aoa > 15] = 0.1 * 15 - 0.3 * (aoa[aoa > 15] - 15)**2  # stall
Cd_aoa = 0.02 + 0.005 * aoa**2  # drag increases with AoA²

ax.plot(aoa, Cl_aoa, color='#22c55e', linewidth=2.5, label='Lift coeff (Cₗ)')
ax.plot(aoa, Cd_aoa, color='#ef4444', linewidth=2.5, label='Drag coeff (Cd)')
ax.axvline(15, color='#f59e0b', linewidth=1.5, linestyle='--')
ax.text(15.5, 1.0, 'STALL!\\nLift collapses', color='#f59e0b', fontsize=9)
ax.axhline(0, color='gray', linewidth=0.5, alpha=0.3)

ax.set_xlabel('Angle of attack (°)', color='white')
ax.set_ylabel('Coefficient', color='white')
ax.set_title('Lift & Drag vs Angle of Attack', color='white', fontsize=11)
ax.legend(facecolor='#1f2937', edgecolor='gray', labelcolor='white', fontsize=8)
ax.tick_params(colors='gray')

# --- Kite at different angles ---
ax = axes[1, 1]; ax.set_facecolor('#111827')
for i, angle in enumerate([10, 20, 30, 45]):
    x0 = i * 3
    # Kite surface
    rad = np.radians(angle)
    kx = [x0, x0 + np.cos(rad), x0]
    ky = [0, np.sin(rad), 0.1]
    ax.fill(kx, ky, color='#ef4444', alpha=0.3 + i*0.15)
    ax.plot(kx, ky, color='#ef4444', linewidth=2)

    # Wind arrow
    ax.annotate('', xy=(x0-0.3, 0.3), xytext=(x0-0.8, 0.3),
                arrowprops=dict(arrowstyle='->', color='#06b6d4', lw=1.5))

    # Label
    ax.text(x0 + 0.5, -0.3, f'{angle}°', color='white', ha='center', fontsize=10)

ax.text(5, -0.6, 'Angle of attack →', color='white', ha='center', fontsize=10)
ax.set_xlim(-1.5, 12); ax.set_ylim(-0.8, 1.5)
ax.set_title('Kite at Different Angles of Attack', color='white', fontsize=11)
ax.set_xticks([]); ax.set_yticks([])

plt.tight_layout()
plt.show()

print("Bernoulli's principle: P + ½ρv² = constant")
print("  Faster flow → lower pressure → lift")
print()
print("Lift equation: L = ½ρv²CₗA")
print("  Lift scales as v² (double speed = 4× lift)")
print("  Lift scales linearly with area (bigger kite = more lift)")
print()
print("Critical: angle of attack must be below stall angle")
print("  Too steep → airflow separates → lift collapses → kite falls")`,
      challenge: 'A 1 m² kite weighs 0.2 kg (2N). Using L = ½ρv²CₗA with ρ=1.225, Cₗ=0.8, what minimum wind speed is needed to fly it? What about a 2 m² kite of the same weight?',
      successHint: 'Bernoulli\'s principle and the lift equation govern every flying object. From a festival kite to a Boeing 747, the physics is identical — only the scale changes.',
    },
    {
      title: 'Kite design — shape, surface, and stability',
      concept: `Not all kites are created equal. The design determines how well a kite flies, how stable it is, and what wind conditions it needs.

**Common kite designs**:
- **Diamond (flat kite)**: simplest, needs a tail for stability. Common at Indian festivals.
- **Delta**: triangular, self-stabilizing with a keel. Good in light winds.
- **Box kite**: 3D structure, generates lift from multiple surfaces. Very stable in strong winds.
- **Parafoil**: no rigid frame, inflates like a parachute. Used for kitesurfing, power generation.
- **Fighter kite**: small, maneuverable, single string with adjustable angle. Used in kite-fighting (like in Guwahati).

**Key design factors**:
- **Aspect ratio** = wingspan² / area. High aspect ratio (long, narrow) = efficient lift, less drag.
- **Dihedral angle**: if the wings angle upward in a V shape, the kite self-corrects when tilted (roll stability).
- **Bridle**: the string attachment system. Multiple bridle points allow adjusting the angle of attack.
- **Tail**: adds drag at the bottom, keeping the kite oriented into the wind. Longer tail = more stable but more drag.
- **Keeled vs. flat**: a keel (vertical fin) provides directional stability, like a boat's keel.`,
      analogy: 'Kite design is like bicycle design. A mountain bike (box kite) is stable on rough terrain (strong, gusty wind). A racing bike (fighter kite) is fast and maneuverable but hard to control. A commuter bike (delta kite) is easy to ride in normal conditions. Each design trades stability for maneuverability, or efficiency for simplicity.',
      storyConnection: 'At the Guwahati kite festival, the fighter kites are small and nimble — designed for kite-fighting, where the goal is to cut the opponent\'s string. These kites sacrifice stability for maneuverability: a single bridle point and no tail, controlled entirely by string tension and release. The design embodies a specific engineering trade-off.',
      checkQuestion: 'Why does adding a tail make a kite more stable? What is the tail actually doing?',
      checkAnswer: 'A tail adds drag at the bottom rear of the kite, pulling the bottom down. This keeps the kite oriented with its top forward and into the wind. Without a tail, a flat kite tends to spin because any slight rotation increases lift on one side, creating a torque that amplifies the rotation (positive feedback). The tail\'s drag creates negative feedback: if the kite rotates, the tail drags more on that side, pulling it back. It is a passive stabilization system.',
      codeIntro: 'Compare the flight characteristics of different kite designs.',
      code: `import numpy as np
import matplotlib.pyplot as plt

fig, axes = plt.subplots(2, 2, figsize=(14, 8))
fig.patch.set_facecolor('#1f2937')

# --- Kite design comparison ---
ax = axes[0, 0]; ax.set_facecolor('#111827')

designs = {
    'Diamond': {'stability': 4, 'maneuver': 3, 'light_wind': 5, 'strong_wind': 3, 'ease': 9, 'color': '#ef4444'},
    'Delta': {'stability': 7, 'maneuver': 5, 'light_wind': 8, 'strong_wind': 5, 'ease': 7, 'color': '#3b82f6'},
    'Box': {'stability': 9, 'maneuver': 2, 'light_wind': 3, 'strong_wind': 9, 'ease': 4, 'color': '#22c55e'},
    'Fighter': {'stability': 2, 'maneuver': 9, 'light_wind': 4, 'strong_wind': 4, 'ease': 3, 'color': '#f59e0b'},
    'Parafoil': {'stability': 6, 'maneuver': 7, 'light_wind': 6, 'strong_wind': 7, 'ease': 5, 'color': '#a855f7'},
}

categories = ['stability', 'maneuver', 'light_wind', 'strong_wind', 'ease']
cat_labels = ['Stability', 'Maneuver-\\nability', 'Light\\nwind', 'Strong\\nwind', 'Ease of\\nuse']
N = len(categories)
angles = np.linspace(0, 2*np.pi, N, endpoint=False).tolist()
angles += angles[:1]

for name, data in designs.items():
    values = [data[c] for c in categories] + [data[categories[0]]]
    ax.plot(angles, values, 'o-', linewidth=1.5, label=name, color=data['color'], markersize=4)
    ax.fill(angles, values, alpha=0.05, color=data['color'])

ax.set_xticks(angles[:-1])
ax.set_xticklabels(cat_labels, color='white', fontsize=7)
ax.set_ylim(0, 10)
ax.set_title('Kite Design Comparison', color='white', fontsize=11)
ax.legend(facecolor='#1f2937', edgecolor='gray', labelcolor='white', fontsize=7, loc='upper right', bbox_to_anchor=(1.3, 1))
ax.tick_params(colors='gray')

# This needs to be a polar axes, let's do bar chart instead
ax.clear()
ax.set_facecolor('#111827')
x = np.arange(len(categories))
width = 0.15
for i, (name, data) in enumerate(designs.items()):
    vals = [data[c] for c in categories]
    ax.bar(x + i*width, vals, width, label=name, color=data['color'], alpha=0.7)
ax.set_xticks(x + width*2)
ax.set_xticklabels(cat_labels, color='white', fontsize=7)
ax.set_ylabel('Rating (0-10)', color='white')
ax.set_title('Kite Design Comparison', color='white', fontsize=11)
ax.legend(facecolor='#1f2937', edgecolor='gray', labelcolor='white', fontsize=7)
ax.tick_params(colors='gray')

# --- Aspect ratio effect ---
ax = axes[0, 1]; ax.set_facecolor('#111827')
AR = np.linspace(1, 10, 100)  # aspect ratio
# L/D ratio improves with aspect ratio (induced drag ∝ 1/AR)
Cd_induced = 0.3 / (np.pi * AR * 0.7)  # simplified
Cd_total = 0.02 + Cd_induced
Cl = 0.8
LD = Cl / Cd_total

ax.plot(AR, LD, color='#22c55e', linewidth=2.5)
ax.fill_between(AR, LD, alpha=0.1, color='#22c55e')

# Mark kite types
kite_AR = [(2, 'Diamond', '#ef4444'), (4, 'Delta', '#3b82f6'), (6, 'Box', '#22c55e'), (3, 'Fighter', '#f59e0b')]
for ar, name, c in kite_AR:
    ld_val = 0.8 / (0.02 + 0.3/(np.pi*ar*0.7))
    ax.plot(ar, ld_val, 'o', color=c, markersize=10, zorder=5)
    ax.annotate(name, xy=(ar, ld_val), xytext=(ar+0.5, ld_val+1), color=c, fontsize=8,
                arrowprops=dict(arrowstyle='->', color=c, lw=0.8))

ax.set_xlabel('Aspect ratio (span²/area)', color='white')
ax.set_ylabel('Lift/Drag ratio', color='white')
ax.set_title('Efficiency vs Aspect Ratio', color='white', fontsize=11)
ax.tick_params(colors='gray')

# --- Stability: tail length effect ---
ax = axes[1, 0]; ax.set_facecolor('#111827')
tail_lengths = np.linspace(0, 5, 100)  # relative to kite size
# Stability improves with tail, but drag increases
stability = 1 - np.exp(-tail_lengths * 0.8)
drag_penalty = 1 + 0.1 * tail_lengths**2
performance = stability / drag_penalty

ax.plot(tail_lengths, stability, color='#22c55e', linewidth=2, label='Stability')
ax.plot(tail_lengths, drag_penalty/drag_penalty.max(), color='#ef4444', linewidth=2, label='Drag (normalized)')
ax.plot(tail_lengths, performance/performance.max(), color='#f59e0b', linewidth=2, linestyle='--', label='Net performance')

opt_idx = np.argmax(performance)
ax.axvline(tail_lengths[opt_idx], color='gray', linestyle=':', alpha=0.3)
ax.text(tail_lengths[opt_idx]+0.2, 0.5, f'Optimal: {tail_lengths[opt_idx]:.1f}×', color='gray', fontsize=9)

ax.set_xlabel('Tail length (× kite height)', color='white')
ax.set_ylabel('Relative value', color='white')
ax.set_title('Tail Length: Stability vs Drag Trade-off', color='white', fontsize=11)
ax.legend(facecolor='#1f2937', edgecolor='gray', labelcolor='white', fontsize=8)
ax.tick_params(colors='gray')

# --- Wind speed flight envelope ---
ax = axes[1, 1]; ax.set_facecolor('#111827')
wind = np.linspace(0, 25, 100)
for name, weight, area, Cl_k, c in [('Light (festival)', 0.1, 0.5, 0.7, '#f59e0b'),
                                       ('Medium (delta)', 0.3, 1.0, 0.9, '#3b82f6'),
                                       ('Heavy (box)', 1.0, 2.0, 0.8, '#22c55e')]:
    lift = 0.5 * 1.225 * wind**2 * Cl_k * area
    flyable = lift > weight * 9.81
    ax.fill_between(wind, 0, flyable.astype(float), alpha=0.2, color=c)
    min_wind = wind[np.argmax(flyable)] if flyable.any() else 0
    max_wind = 20  # assumed structural limit
    ax.plot([min_wind, max_wind], [0.5 + 0.3*list(designs.keys()).index(name.split()[0]) if name.split()[0] in designs else 0.5]*2,
            color=c, linewidth=8, alpha=0.6, solid_capstyle='round', label=f'{name}: {min_wind:.0f}-{max_wind} m/s')

ax.set_xlabel('Wind speed (m/s)', color='white')
ax.set_title('Flight Envelope: Flyable Wind Range', color='white', fontsize=11)
ax.legend(facecolor='#1f2937', edgecolor='gray', labelcolor='white', fontsize=8)
ax.tick_params(colors='gray')
ax.set_yticks([])

plt.tight_layout()
plt.show()

print("Kite design principles:")
print("  Higher aspect ratio → better efficiency")
print("  Longer tail → more stability, more drag")
print("  Dihedral angle → self-correcting in gusts")
print("  Fighter kites: no tail, single bridle → maximum maneuverability")
print()
print("Every design is a trade-off:")
print("  Stability ↔ Maneuverability")
print("  Light wind ↔ Strong wind")
print("  Simplicity ↔ Performance")`,
      challenge: 'Design a kite for Guwahati\'s conditions: average wind 3-5 m/s, occasional gusts to 10 m/s. Should it be large or small? High or low aspect ratio? Should it have a tail? Justify each choice with physics.',
      successHint: 'Kite design is engineering at its most intuitive: every flyer experiments with shape, size, tail length, and bridle position. The same trade-offs appear in aircraft design, sail design, and wind turbine blade design.',
    },
    {
      title: 'Wing shapes — from flat plates to airfoils',
      concept: `A kite's surface is basically a flat plate tilted into the wind. Real aircraft wings are much more sophisticated — they use **airfoil** shapes that generate lift more efficiently.

**Flat plate** (kite): works, but creates turbulence on the top surface, limiting lift and causing instability.

**Curved plate** (cambered): the top surface is curved outward. Air flowing over the curve accelerates, creating lower pressure. More lift, less drag than flat plates.

**Airfoil** (wing cross-section): precisely shaped. Key features:
- **Leading edge**: rounded — smoothly splits the airflow
- **Trailing edge**: sharp — clean airflow separation, minimal turbulence
- **Camber**: the asymmetry between top and bottom curves
- **Thickness**: affects structural strength and drag
- **Chord**: the straight-line distance from leading to trailing edge

**NACA airfoils** (National Advisory Committee for Aeronautics, now NASA):
- NACA 2412: 2% max camber at 40% chord, 12% thickness. General aviation workhorse.
- NACA 0012: symmetric (no camber), 12% thick. Used for helicopter rotors.
- The 4-digit code tells you the geometry: 1st = max camber %, 2nd = camber position, 3rd-4th = max thickness %

Birds' wings are natural airfoils — millions of years of evolution optimized them for different flight styles (soaring, hovering, diving, sprinting).`,
      analogy: 'The progression from flat plate to airfoil is like the progression from a raft to a sailboat to a yacht. A raft (flat plate) works — it floats and moves with the wind. But a sailboat (cambered plate) is more efficient, and a yacht (optimized airfoil) extracts maximum energy from the wind with minimum drag. Each step adds sophistication and performance.',
      storyConnection: 'Festival kites at Guwahati use simple flat or slightly bowed surfaces. But the principles that make them fly are the same ones that shape modern aircraft wings. The kite flyer who bows the surface by tightening the cross-spar is creating camber — the same design feature that makes a Boeing 747 wing work.',
      checkQuestion: 'A paper airplane has flat wings. A real airplane has curved airfoil wings. Why does the paper airplane still fly?',
      checkAnswer: 'A flat plate at a positive angle of attack generates lift — just less efficiently than an airfoil. The air below is deflected downward (Newton\'s third law pushes the plate up), and there is some Bernoulli effect as air accelerates over the top. The flat plate just produces more drag and stalls at lower angles than a proper airfoil. Paper airplanes fly because angle of attack matters more than wing shape for generating basic lift.',
      codeIntro: 'Draw and compare airfoil shapes and their lift characteristics.',
      code: `import numpy as np
import matplotlib.pyplot as plt

def naca_4digit(code, n=200):
    """Generate NACA 4-digit airfoil coordinates."""
    m = int(code[0]) / 100  # max camber
    p = int(code[1]) / 10   # max camber position
    t = int(code[2:]) / 100 # thickness

    x = (1 - np.cos(np.linspace(0, np.pi, n))) / 2
    yt = 5*t*(0.2969*np.sqrt(x) - 0.1260*x - 0.3516*x**2 + 0.2843*x**3 - 0.1015*x**4)

    if m == 0:
        yc = np.zeros_like(x)
    else:
        yc = np.where(x < p, m/p**2 * (2*p*x - x**2), m/(1-p)**2 * (1 - 2*p + 2*p*x - x**2))

    xu = x - yt * np.sin(np.arctan(np.gradient(yc, x)))
    yu = yc + yt * np.cos(np.arctan(np.gradient(yc, x)))
    xl = x + yt * np.sin(np.arctan(np.gradient(yc, x)))
    yl = yc - yt * np.cos(np.arctan(np.gradient(yc, x)))
    return xu, yu, xl, yl, x, yc

fig, axes = plt.subplots(2, 2, figsize=(14, 8))
fig.patch.set_facecolor('#1f2937')

# --- Compare airfoil shapes ---
ax = axes[0, 0]; ax.set_facecolor('#111827')
airfoils = [('0012', 'Symmetric', '#3b82f6'), ('2412', 'General purpose', '#22c55e'),
            ('4415', 'High lift', '#f59e0b'), ('6618', 'Very cambered', '#ef4444')]

for i, (code, name, color) in enumerate(airfoils):
    xu, yu, xl, yl, xc, yc = naca_4digit(code)
    offset = -i * 0.35
    ax.fill(np.concatenate([xu, xl[::-1]]), np.concatenate([yu, yl[::-1]]) + offset,
            color=color, alpha=0.3)
    ax.plot(np.concatenate([xu, xl[::-1]]), np.concatenate([yu, yl[::-1]]) + offset,
            color=color, linewidth=1.5)
    ax.text(-0.15, offset, f'NACA {code}\\n{name}', color=color, fontsize=8, va='center')

ax.set_xlim(-0.25, 1.1); ax.set_aspect('equal')
ax.set_title('NACA Airfoil Shapes', color='white', fontsize=11)
ax.set_xticks([]); ax.set_yticks([])

# --- Flat plate vs airfoil lift ---
ax = axes[0, 1]; ax.set_facecolor('#111827')
aoa = np.linspace(-5, 20, 100)

# Flat plate: Cl = 2π sin(α) (thin airfoil theory)
Cl_flat = 2 * np.pi * np.sin(np.radians(aoa)) / 10  # simplified
Cl_flat[aoa > 12] = Cl_flat[aoa == 12][0] - 0.1*(aoa[aoa > 12]-12)**2  # stall

# NACA 2412: higher Cl_max, stalls later
Cl_airfoil = 2 * np.pi * np.sin(np.radians(aoa + 2)) / 9  # +2° offset from camber
Cl_airfoil[aoa > 16] = Cl_airfoil[aoa == 16][0] - 0.08*(aoa[aoa > 16]-16)**2

ax.plot(aoa, Cl_flat, color='#ef4444', linewidth=2.5, label='Flat plate (kite)')
ax.plot(aoa, Cl_airfoil, color='#22c55e', linewidth=2.5, label='NACA 2412 (wing)')
ax.axhline(0, color='gray', linewidth=0.5, alpha=0.3)
ax.axvline(0, color='gray', linewidth=0.5, alpha=0.3)

ax.set_xlabel('Angle of attack (°)', color='white')
ax.set_ylabel('Lift coefficient (Cₗ)', color='white')
ax.set_title('Flat Plate vs Airfoil', color='white', fontsize=11)
ax.legend(facecolor='#1f2937', edgecolor='gray', labelcolor='white', fontsize=9)
ax.tick_params(colors='gray')

# --- Bird wing comparison ---
ax = axes[1, 0]; ax.set_facecolor('#111827')
birds = {
    'Eagle\\n(soaring)': {'span': 2.0, 'area': 0.6, 'AR': 6.7, 'speed': 15, 'color': '#f59e0b'},
    'Sparrow\\n(flapping)': {'span': 0.22, 'area': 0.01, 'AR': 4.8, 'speed': 10, 'color': '#22c55e'},
    'Albatross\\n(gliding)': {'span': 3.4, 'area': 0.6, 'AR': 19.3, 'speed': 20, 'color': '#3b82f6'},
    'Hummingbird\\n(hovering)': {'span': 0.1, 'area': 0.002, 'AR': 5.0, 'speed': 0, 'color': '#ef4444'},
}
names = list(birds.keys())
ARs = [birds[n]['AR'] for n in names]
colors_b = [birds[n]['color'] for n in names]

ax.barh(names, ARs, color=colors_b, height=0.5)
ax.set_xlabel('Aspect ratio', color='white')
ax.set_title('Bird Wing Aspect Ratios', color='white', fontsize=11)
ax.tick_params(colors='gray')
for name, ar in zip(names, ARs):
    ax.text(ar + 0.3, name, f'{ar}', va='center', color='white', fontsize=9)

# --- Pressure distribution on airfoil ---
ax = axes[1, 1]; ax.set_facecolor('#111827')
xu, yu, xl, yl, xc, yc = naca_4digit('2412')
ax.fill(np.concatenate([xu, xl[::-1]]), np.concatenate([yu, yl[::-1]]),
        color='#374151', alpha=0.8)

# Simplified pressure distribution
x_press = np.linspace(0.01, 0.99, 50)
Cp_upper = -2 * (1-x_press) * np.exp(-x_press*3)  # suction (negative)
Cp_lower = 0.5 * (1-x_press)**0.5  # positive pressure

# Draw pressure arrows
for i in range(0, 50, 5):
    xp = x_press[i]
    yp_u = np.interp(xp, xu, yu)
    yp_l = np.interp(xp, xl, yl)
    # Upper: arrows pointing away from surface (suction)
    ax.annotate('', xy=(xp, yp_u - Cp_upper[i]*0.15), xytext=(xp, yp_u),
                arrowprops=dict(arrowstyle='->', color='#3b82f6', lw=1))
    # Lower: arrows pointing into surface (pressure)
    ax.annotate('', xy=(xp, yp_l - Cp_lower[i]*0.1), xytext=(xp, yp_l),
                arrowprops=dict(arrowstyle='->', color='#ef4444', lw=1))

ax.text(0.3, 0.25, 'Low pressure (suction)', color='#3b82f6', fontsize=9)
ax.text(0.3, -0.2, 'High pressure', color='#ef4444', fontsize=9)
ax.annotate('→ Wind', xy=(-0.1, 0.05), color='#06b6d4', fontsize=10)

ax.set_xlim(-0.15, 1.1); ax.set_ylim(-0.3, 0.4)
ax.set_aspect('equal')
ax.set_title('Pressure Distribution on NACA 2412', color='white', fontsize=11)
ax.set_xticks([]); ax.set_yticks([])

plt.tight_layout()
plt.show()

print("Wing shape progression:")
print("  Flat plate → cambered plate → full airfoil")
print("  Each step: more lift, less drag, later stall")
print()
print("NACA 4-digit code:")
print("  2412 = 2% camber at 40% chord, 12% thick")
print("  Most general aviation uses NACA 2412 or similar")
print()
print("Nature got there first:")
print("  Albatross (AR=19): best glider in nature")
print("  Hummingbird (AR=5): hovering specialist")`,
      challenge: 'Using the NACA code system, design an airfoil for maximum lift: high camber (e.g., 6%), positioned forward (e.g., 20% chord), moderate thickness (15%). What is the code? Plot it and compare to NACA 2412.',
      successHint: 'Airfoil design is one of the most refined branches of engineering. The progression from flat kite surface to NACA airfoil mirrors 200 years of aerodynamic research — and birds had it figured out millions of years before we did.',
    },
    {
      title: 'Angle of attack — the critical variable',
      concept: `The **angle of attack** (AoA) is the angle between the wing/kite surface and the incoming airflow. It is the single most important variable in flight.

At low AoA (0-5°): airflow stays attached to the surface, smooth flow, moderate lift
At medium AoA (5-12°): more lift, still attached flow, increasing drag
At high AoA (>12-15°): **stall** — airflow separates from the surface, turbulence erupts, lift collapses suddenly

**Stall** is the most dangerous event in flying:
- Lift drops dramatically (often by 50%+)
- Drag increases sharply
- The aircraft/kite falls
- Recovery requires reducing AoA (pointing the nose down)

For a kite, the flyer controls AoA by adjusting string tension:
- Pull string tight → kite tilts back → higher AoA → more lift (up to stall)
- Release string → kite tilts forward → lower AoA → less lift, but stable
- Pull too hard → AoA exceeds stall → kite flutters and falls

This is why experienced kite flyers use a pump-and-release technique: pull to gain altitude, release to stabilize, pull again. They are managing the angle of attack in real-time.`,
      analogy: 'Angle of attack is like holding your hand out a car window. Flat (0° AoA): smooth airflow, no lift. Tilted slightly (10°): your hand rises — lift! Tilted too much (30°): your hand gets pushed back violently and vibrates — stall! The transition from smooth lift to chaotic stall is abrupt and dramatic, just like an airplane wing.',
      storyConnection: 'In Guwahati\'s kite-fighting competitions, the best flyers dance their kites by rapidly varying the angle of attack — pulling the string to climb steeply, releasing to dive, pulling again to swoop. Each maneuver is a controlled flirtation with stall. Cross the stall angle, and the kite tumbles. Stay just below it, and the kite performs.',
      checkQuestion: 'If a plane is in level flight and the pilot pulls back on the stick (increasing AoA), the plane initially climbs. But if they keep pulling, the plane stalls and descends. Why doesn\'t more AoA always mean more lift?',
      checkAnswer: 'At low AoA, air flows smoothly over the wing (attached flow). Increasing AoA tilts the wing further into the airflow, deflecting more air downward and creating more lift. But beyond the critical angle (~15° for most wings), the air can no longer follow the curved upper surface. It separates, creating a turbulent wake. The turbulence destroys the low-pressure zone on top of the wing, and lift collapses. The wing is still deflecting air, but turbulently and inefficiently.',
      codeIntro: 'Simulate how angle of attack affects lift and model the stall phenomenon.',
      code: `import numpy as np
import matplotlib.pyplot as plt

fig, axes = plt.subplots(2, 2, figsize=(14, 8))
fig.patch.set_facecolor('#1f2937')

# --- Cl vs AoA with stall ---
ax = axes[0, 0]; ax.set_facecolor('#111827')
aoa = np.linspace(-5, 25, 200)

# Pre-stall: linear (thin airfoil theory)
Cl = np.where(aoa <= 14, 0.1 * aoa + 0.2, 0.1*14+0.2 - 0.15*(aoa-14)**1.5)
Cd = 0.02 + 0.005 * aoa**2 + np.where(aoa > 14, 0.05*(aoa-14)**2, 0)

ax.plot(aoa, Cl, color='#22c55e', linewidth=2.5, label='Lift (Cₗ)')
ax.plot(aoa, Cd, color='#ef4444', linewidth=2.5, label='Drag (Cd)')

# Stall region
ax.axvspan(14, 25, alpha=0.1, color='#ef4444')
ax.text(18, 1.2, 'STALL\\nREGION', color='#ef4444', fontsize=11, fontweight='bold', ha='center')
ax.axvline(14, color='#f59e0b', linewidth=2, linestyle='--')
ax.text(14.5, 0.5, 'Critical AoA\\n(~14°)', color='#f59e0b', fontsize=9)

ax.set_xlabel('Angle of attack (°)', color='white')
ax.set_ylabel('Coefficient', color='white')
ax.set_title('Lift & Drag vs Angle of Attack', color='white', fontsize=11)
ax.legend(facecolor='#1f2937', edgecolor='gray', labelcolor='white', fontsize=9)
ax.tick_params(colors='gray')
ax.axhline(0, color='gray', linewidth=0.5, alpha=0.3)

# --- Flow visualization at different AoA ---
ax = axes[0, 1]; ax.set_facecolor('#111827')
for i, (angle, flow_type, y_off) in enumerate([(5, 'Attached', 1.5), (12, 'Partial', 0), (20, 'Separated', -1.5)]):
    # Simple wing
    rad = np.radians(angle)
    wing_x = [0 + i*0.05, np.cos(rad)*0.8, 0 + i*0.05]
    wing_y = [y_off, y_off + np.sin(rad)*0.8, y_off + 0.05]
    ax.fill(wing_x, wing_y, color='#374151')
    ax.plot(wing_x, wing_y, color='white', linewidth=1.5)

    # Streamlines
    for y_s in np.linspace(-0.3, 0.3, 5):
        x_s = np.linspace(-0.5, 1.2, 50)
        if flow_type == 'Attached':
            y_stream = y_off + y_s + 0.1*np.sin(np.pi*x_s)
        elif flow_type == 'Partial':
            turbulence = 0.05 * np.random.randn(50) * (x_s > 0.5)
            y_stream = y_off + y_s + 0.15*np.sin(np.pi*x_s) + turbulence
        else:
            turbulence = 0.15 * np.random.randn(50) * (x_s > 0.3)
            y_stream = y_off + y_s + 0.2*np.sin(np.pi*x_s) + turbulence
        ax.plot(x_s, y_stream, color='#06b6d4', linewidth=0.5, alpha=0.5)

    ax.text(-0.6, y_off, f'{angle}°\\n{flow_type}', color='white', fontsize=8, va='center')

ax.set_xlim(-0.8, 1.5); ax.set_ylim(-2.5, 2.5)
ax.set_title('Airflow at Different Angles', color='white', fontsize=11)
ax.set_xticks([]); ax.set_yticks([])

# --- Kite altitude simulation ---
ax = axes[1, 0]; ax.set_facecolor('#111827')
np.random.seed(42)
t = np.linspace(0, 60, 600)  # seconds
# Simulate string pull/release cycles
pull = np.sin(t * 0.5) > 0  # alternating pull/release
aoa_sim = np.where(pull, 12, 5) + 2*np.random.randn(len(t))
altitude = np.zeros_like(t)
v = 0
for i in range(1, len(t)):
    dt = t[i] - t[i-1]
    a = aoa_sim[i]
    if a < 14:
        lift_acc = 0.1 * a - 0.5  # simplified
    else:
        lift_acc = -2  # stall!
    v += lift_acc * dt
    v *= 0.95  # damping
    altitude[i] = max(0, altitude[i-1] + v * dt)

ax.plot(t, altitude, color='#f59e0b', linewidth=1.5)
ax.fill_between(t, altitude, alpha=0.1, color='#f59e0b')

# Mark pull/release phases
for i in range(len(t)-1):
    if pull[i]:
        ax.axvspan(t[i], t[i+1], alpha=0.03, color='#22c55e')

ax.set_xlabel('Time (seconds)', color='white')
ax.set_ylabel('Altitude (m)', color='white')
ax.set_title('Kite Altitude: Pull-Release Cycling', color='white', fontsize=11)
ax.tick_params(colors='gray')

# --- L/D polar ---
ax = axes[1, 1]; ax.set_facecolor('#111827')
aoa_p = np.linspace(0, 20, 100)
Cl_p = np.where(aoa_p <= 14, 0.1*aoa_p+0.2, 0.1*14+0.2-0.15*(aoa_p-14)**1.5)
Cd_p = 0.02 + 0.005*aoa_p**2 + np.where(aoa_p > 14, 0.05*(aoa_p-14)**2, 0)

ax.plot(Cd_p, Cl_p, color='#a855f7', linewidth=2.5)
# Mark key points
for a in [5, 10, 14, 18]:
    idx = np.argmin(np.abs(aoa_p - a))
    ax.plot(Cd_p[idx], Cl_p[idx], 'o', color='white', markersize=6)
    ax.annotate(f'{a}°', xy=(Cd_p[idx], Cl_p[idx]), xytext=(Cd_p[idx]+0.05, Cl_p[idx]+0.05),
                color='white', fontsize=8)

# Max L/D line from origin
LD = Cl_p / Cd_p
best_idx = np.argmax(LD[:70])
ax.plot([0, Cd_p[best_idx]*2], [0, Cl_p[best_idx]*2], '--', color='#f59e0b', linewidth=1)
ax.text(Cd_p[best_idx]+0.03, Cl_p[best_idx]+0.1, f'Best L/D at {aoa_p[best_idx]:.0f}°',
        color='#f59e0b', fontsize=8)

ax.set_xlabel('Drag coefficient (Cd)', color='white')
ax.set_ylabel('Lift coefficient (Cₗ)', color='white')
ax.set_title('Drag Polar (Cₗ vs Cd)', color='white', fontsize=11)
ax.tick_params(colors='gray')

plt.tight_layout()
plt.show()

print("Angle of attack is THE critical flight parameter:")
print("  Too low: not enough lift, kite sinks")
print("  Just right: maximum lift, stable flight")
print("  Too high: STALL — lift collapses, kite falls")
print()
print("Kite flyers control AoA by string tension:")
print("  Pull = increase AoA = climb")
print("  Release = decrease AoA = stabilize")
print("  Too much pull = stall = tumble")`,
      challenge: 'A kite stalls at 14° AoA. If the wind gusts suddenly increase the effective AoA by 5°, and the kite was already at 11°, it enters stall. How would you design a kite that is resistant to gust-induced stall? (Hint: think about what the dihedral angle and tail do.)',
      successHint: 'Angle of attack is the master variable of flight. Every pilot, kite flyer, and aerodynamic engineer must understand it. Stall is the boundary between controlled flight and disaster — respecting it is the first rule of aviation.',
    },
    {
      title: 'History of flight — from kites to rockets',
      concept: `The kite is one of the oldest flying machines — invented in China around **500 BCE**. It took over 2,400 years to get from kites to powered flight.

**Timeline**:
- **~500 BCE**: Chinese kites (bamboo and silk). Used for measuring distances, signaling, and military reconnaissance.
- **~200 BCE**: Chinese sky lanterns — the first hot air "balloons"
- **1783**: Montgolfier brothers — first manned hot air balloon flight (Paris)
- **1804**: George Cayley — first fixed-wing glider with a modern design (separated lift, drag, and thrust)
- **1853**: Cayley's coachman — first manned glider flight (across a valley in Yorkshire)
- **1891-96**: Otto Lilienthal — over 2,000 glider flights, first systematic aerodynamic data
- **1903**: Wright brothers — first powered, sustained, controlled airplane flight (12 seconds, 37 meters)
- **1927**: Lindbergh — first solo transatlantic flight (New York to Paris, 33.5 hours)
- **1947**: Chuck Yeager — first supersonic flight (Mach 1.06 in the Bell X-1)
- **1957**: Sputnik — first object in orbit
- **1969**: Apollo 11 — first humans on the Moon
- **2020**: Ingenuity — first powered flight on another planet (Mars)

From kite to Mars helicopter in 2,500 years. The physics is the same: deflect air (or exhaust) downward, and the reaction force pushes you up. Only the engineering changes.`,
      analogy: 'The history of flight is like learning to walk. First you crawl (kites — tethered, not free-flying). Then you stand (gliders — free but unpowered). Then you take your first steps (Wright Flyer — powered but barely). Then you run (jet aircraft). Then you leave the ground entirely (rockets to space). Each step builds on all previous ones.',
      storyConnection: 'The kites dancing over the Brahmaputra at Guwahati\'s festival connect directly to a 2,500-year lineage. Chinese kites crossed the Silk Road, influenced Indian kite culture, and eventually inspired European experimenters who turned kite observations into the science of aerodynamics. When a child in Guwahati flies a kite, they are standing at the base of a technology tree that leads to Mars.',
      checkQuestion: 'The Wright brothers flew in 1903. Only 66 years later, humans walked on the Moon. Why was progress so fast?',
      checkAnswer: 'Three accelerating factors: (1) World Wars I and II created enormous military demand for better aircraft, pouring massive resources into aerodynamic research. (2) Each advancement (better engines, materials, instruments) enabled the next — compounding progress. (3) The Cold War space race between the US and USSR turned spaceflight into a national priority with unlimited funding. Without geopolitical competition, the Moon landing might have taken another century. Technology advances fastest when nations compete.',
      codeIntro: 'Visualize the history of flight speed and altitude records.',
      code: `import numpy as np
import matplotlib.pyplot as plt

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 6))
fig.patch.set_facecolor('#1f2937')

# --- Speed records ---
ax1.set_facecolor('#111827')
events = [
    (1903, 15, 'Wright Flyer', '#22c55e'),
    (1927, 200, 'Spirit of St. Louis', '#3b82f6'),
    (1939, 755, 'He 178 (first jet)', '#f59e0b'),
    (1947, 1235, 'Bell X-1 (Mach 1)', '#ef4444'),
    (1958, 3500, 'X-15', '#a855f7'),
    (1961, 28000, 'Vostok 1 (orbit)', '#06b6d4'),
    (1969, 40000, 'Apollo 11 (Moon)', '#fbbf24'),
]

years = [e[0] for e in events]
speeds = [e[1] for e in events]
names = [e[2] for e in events]
colors_e = [e[3] for e in events]

ax1.scatter(years, speeds, c=colors_e, s=100, zorder=5, edgecolors='white', linewidths=0.5)
ax1.plot(years, speeds, color='gray', linewidth=1, linestyle='--', alpha=0.5)

for yr, spd, name, color in events:
    ax1.annotate(name, xy=(yr, spd), xytext=(yr-3, spd*1.5),
                color=color, fontsize=7, arrowprops=dict(arrowstyle='->', color=color, lw=0.8))

ax1.set_xlabel('Year', color='white')
ax1.set_ylabel('Speed (km/h)', color='white')
ax1.set_title('Speed Records in Flight', color='white', fontsize=13)
ax1.set_yscale('log')
ax1.tick_params(colors='gray')

# Mark speed of sound
ax1.axhline(1235, color='#ef4444', linewidth=1, linestyle=':', alpha=0.3)
ax1.text(1905, 1400, 'Speed of sound', color='#ef4444', fontsize=7)

# --- Altitude records ---
ax2.set_facecolor('#111827')
alt_events = [
    (1783, 0.9, 'Montgolfier balloon', '#f59e0b'),
    (1903, 0.003, 'Wright Flyer', '#22c55e'),
    (1935, 22, 'Balloon (stratosphere)', '#3b82f6'),
    (1958, 107, 'X-15', '#a855f7'),
    (1961, 327, 'Vostok 1', '#06b6d4'),
    (1969, 384400, 'Apollo 11', '#fbbf24'),
    (2021, 0.012, 'Ingenuity (Mars!)', '#ef4444'),
]

years_a = [e[0] for e in alt_events if e[0] != 2021]
alts = [e[1] for e in alt_events if e[0] != 2021]
names_a = [e[2] for e in alt_events if e[0] != 2021]
colors_a = [e[3] for e in alt_events if e[0] != 2021]

ax2.scatter(years_a, alts, c=colors_a, s=100, zorder=5, edgecolors='white', linewidths=0.5)
ax2.plot(years_a, alts, color='gray', linewidth=1, linestyle='--', alpha=0.5)

for yr, alt, name, color in alt_events:
    if yr != 2021:
        ax2.annotate(name, xy=(yr, alt), xytext=(yr-8, alt*2),
                    color=color, fontsize=7, arrowprops=dict(arrowstyle='->', color=color, lw=0.8))

ax2.set_xlabel('Year', color='white')
ax2.set_ylabel('Altitude (km)', color='white')
ax2.set_title('Altitude Records', color='white', fontsize=13)
ax2.set_yscale('log')
ax2.tick_params(colors='gray')

# Mark atmosphere boundary
ax2.axhline(100, color='#f59e0b', linewidth=1, linestyle=':', alpha=0.3)
ax2.text(1790, 120, 'Kármán line (space)', color='#f59e0b', fontsize=7)

plt.tight_layout()
plt.show()

print("From kites to the Moon in 2,500 years:")
print("  500 BCE: Chinese kites (bamboo + silk)")
print("  1903: Wright Flyer (12 seconds, 37 meters)")
print("  1969: Apollo 11 (384,400 km to the Moon)")
print("  2021: Ingenuity (first flight on Mars)")
print()
print("The physics is the same: deflect fluid down,")
print("reaction force pushes you up. Newton's third law.")
print("Only the engineering changes.")`,
      challenge: 'Ingenuity flew on Mars where air density is 1% of Earth\'s. Using L = ½ρv²CₗA, if Mars ρ = 0.02 kg/m³ (vs Earth\'s 1.225), how much faster must the rotor spin to generate the same lift? (Hint: lift ∝ ρv², so v must increase by √(1.225/0.02) ≈ 7.8×)',
      successHint: 'The kite is the ancestor of every flying machine. The forces, principles, and trade-offs visible in a simple festival kite are the same ones that sent humans to the Moon and a helicopter to Mars. The distance from Guwahati to the stars is measured in understanding, not miles.',
    },
  ];

  return (
    <div>
      <div className="flex items-center gap-3 mb-6">
        <div className="flex items-center gap-2 bg-emerald-100 dark:bg-emerald-900/30 text-emerald-700 dark:text-emerald-300 px-4 py-2 rounded-full text-sm font-semibold">
          <Sparkles className="w-4 h-4" /> Level 1: Explorer
        </div>
        <span className="text-sm text-gray-500 dark:text-gray-400">No prior physics experience needed</span>
      </div>
      {!pyReady && (
        <div className="mb-8 bg-gray-50 dark:bg-gray-800 rounded-xl p-6 text-center">
          <p className="text-gray-600 dark:text-gray-300 mb-4">These exercises use Python for aerodynamics simulations. Click to start.</p>
          <button onClick={loadPyodide} disabled={loading} className="inline-flex items-center gap-2 bg-emerald-600 hover:bg-emerald-700 disabled:bg-gray-500 text-white px-6 py-3 rounded-full font-semibold transition-colors">
            {loading ? (<><Loader2 className="w-5 h-5 animate-spin" />{loadProgress}</>) : (<><Sparkles className="w-5 h-5" />Load Python</>)}
          </button>
        </div>
      )}
      <div className="space-y-8">
        {miniLessons.map((lesson, i) => (
          <MiniLesson key={i} id={`L1-${i + 1}`} number={i + 1}
            title={lesson.title} concept={lesson.concept} analogy={lesson.analogy}
            storyConnection={lesson.storyConnection} checkQuestion={lesson.checkQuestion}
            checkAnswer={lesson.checkAnswer} codeIntro={lesson.codeIntro}
            code={lesson.code} challenge={lesson.challenge} successHint={lesson.successHint}
            />
        ))}
      </div>
    </div>
  );
}
