import type { ReferenceGuide } from '../reference';

export const guide: ReferenceGuide = {
  slug: 'animal-senses-and-behavior',
  title: 'Animal Senses & Behavior',
  category: 'zoology',
  icon: '🦇',
  tagline: 'How animals see, hear, and sense the world in ways humans cannot.',
  relatedStories: ['girl-who-spoke-to-elephants', 'tigers-whisker', 'river-dolphins-secret', 'owl-wisest', 'dancing-deer-of-loktak-lake', 'peacocks-dance'],
  understand: [
    {
      title: 'Senses Beyond Human Perception',
      beginnerContent:
        'Humans experience the world through five primary senses, but many animals have senses that go far beyond ours. Some snakes have heat-sensing pits that detect infrared radiation, letting them "see" the body heat of prey in total darkness. Sharks can detect the faint electric fields generated by the muscles of a fish buried in sand. Migratory birds sense Earth\'s magnetic field and use it as a compass. Mantis shrimp can see ultraviolet light and have 16 types of color receptors (humans have three). The world as experienced by a bee, a dolphin, or an owl is radically different from what we perceive — their brains process entirely different kinds of information from the environment.',
      intermediateContent:
        'Pit vipers detect infrared using **TRPA1 ion channels** in the pit organ membrane, sensitive to temperature changes as small as **0.003°C** — corresponding to detecting a mouse-sized warm body at 1 metre. The pit has a pinhole-camera design with ~1,800 heat-sensitive neurons, giving spatial resolution of ~5°. Sharks\' **ampullae of Lorenzini** detect electric fields as weak as **5 nV/cm** (5 billionths of a volt per centimetre) — this is equivalent to detecting the voltage from a 1.5V battery with electrodes separated by 3,000 km. The sensory cells contain voltage-gated calcium channels that amplify the signal. Magnetic sense in birds likely relies on **cryptochrome proteins** in the retina: light creates radical pairs whose spin states are influenced by Earth\'s magnetic field (~50 μT), producing a visual "overlay" of the field.',
      advancedContent:
        'The concept of **Umwelt** (von Uexküll, 1909) describes the unique sensory world each species inhabits. Modern neuroethology maps these sensory worlds quantitatively. The electric sense in weakly electric fish (mormyrids, gymnotids) involves active electrolocation: the fish generates an electric field at 20–2,000 Hz via an electric organ and detects distortions caused by nearby objects through ~15,000 tuberous electroreceptors. The computational problem — reconstructing object shape, distance, and material from field distortions — is mathematically equivalent to solving an inverse electromagnetic problem, and the fish\'s brain solves it in real-time using neural circuits in the electrosensory lobe. This inspired algorithms for underwater robot navigation. The **magnetic compass** in birds involves quantum biology: cryptochrome radical pairs exhibit singlet-triplet interconversion rates sensitive to magnetic field orientation, with angular sensitivity enhanced by **hyperfine interactions** with nitrogen nuclei. This makes avian magnetoreception one of the few macroscopic quantum effects in biology.',
      interactive: {
        type: 'matching',
        props: {
          title: 'Match each animal to its superpower sense',
          pairs: [
            ['Pit vipers', 'Infrared heat detection — "see" warm-blooded prey in total darkness'],
            ['Sharks', 'Electroreception — detect electric fields from muscles of hidden prey'],
            ['Migratory birds', 'Magnetoreception — sense Earth\'s magnetic field as a compass'],
            ['Mantis shrimp', 'UV vision with 16 types of color receptors (humans have 3)'],
          ],
        },
      },
    },
    {
      title: 'Echolocation — Seeing with Sound',
      beginnerContent:
        'Bats and dolphins navigate and hunt using echolocation: they emit high-frequency sound pulses and listen for the echoes that bounce back from objects. By analysing the time delay, intensity, and frequency shift of the returning echoes, their brains build a detailed three-dimensional map of their surroundings. The Gangetic river dolphins of the Brahmaputra have taken this to an extreme — they are essentially blind, with tiny eyes that can only detect light and dark. They rely almost entirely on echolocation to navigate the muddy, silt-heavy waters of the river, finding fish and avoiding obstacles using sound alone. Their echolocation is so precise that they can detect a thin wire in murky water.',
      intermediateContent:
        'Echolocation range depends on the equation **d = (v × t) / 2**, where v is sound speed and t is the round-trip time. Sound in air travels at ~343 m/s; in water at ~1,480 m/s. If a bat receives an echo 5.8 ms after calling, the target is 343 × 0.0058 / 2 = **1.0 m** away. Bats emit pulses at 20–200 kHz, with wavelengths of 1.7–17 mm, allowing them to resolve objects as small as a mosquito wing. As a bat closes on prey, it increases pulse rate from ~10/s to over **200/s** (the "terminal buzz"), improving temporal resolution. Dolphins emit broadband clicks at 20–130 kHz with peak energies of **220 dB re 1 μPa** — among the loudest sounds produced by any animal. They detect targets using the time difference of arrival between echoes at their two ears (interaural time difference ~30 μs) and amplitude differences shaped by the fat-filled lower jaw.',
      advancedContent:
        'Bat echolocation involves two neural specialisations that rival radar engineering. **FM bats** (e.g., Myotis) use frequency-modulated sweeps and extract target range from pulse-echo delay using **delay-tuned neurons** in the auditory cortex — each neuron fires maximally at a specific echo delay, creating a topographic map of distance. **CF-FM bats** (e.g., Rhinolophus) use constant-frequency calls and exploit the **Doppler shift** of returning echoes to detect prey wing-beat flutter. They compensate for their own flight speed by adjusting emission frequency so the returning echo always falls in a narrow "acoustic fovea" — a massively over-represented frequency band in the cochlea (30% of hair cells devoted to ±200 Hz around ~83 kHz in R. ferrumequinum). This **Doppler-shift compensation** is neurally analogous to smooth-pursuit eye movements. Bio-sonar research has inspired ultrasonic cane technology for visually impaired people and robotic navigation systems.',
      diagram: 'EcholocationDiagram',
    },
    {
      title: 'Infrasound — The Secret Language of Elephants',
      beginnerContent:
        'Asian elephants, including the herds in Assam\'s Kaziranga National Park, communicate using infrasound — sounds with frequencies below 20 Hz, too low for human ears to hear. These deep rumbles can travel through the ground for up to 10 kilometres, letting elephants coordinate movements, warn of danger, and find mates across vast distances. Elephants detect these vibrations through their feet, which contain special sensory cells called Pacinian corpuscles. They sometimes freeze and lean forward, pressing their feet more firmly into the ground to "listen" better. Scientists studying elephant communication have found that herds separated by many kilometres make coordinated decisions, likely mediated by these long-distance infrasonic calls.',
      intermediateContent:
        'Elephant infrasonic calls range from **14–35 Hz** with sound pressure levels of **90–117 dB at 1 m**. Low frequencies attenuate less in air: attenuation at 20 Hz is only **~0.01 dB/km** (versus ~1 dB/km at 1 kHz), explaining the 10 km range. The calls propagate both through air and as **Rayleigh surface waves** in the ground at ~250 m/s. Elephants detect ground vibrations via Pacinian corpuscles in the dermis of the foot pad (density: ~30 per cm²) and possibly via bone conduction through the leg skeleton. The "freezing" posture increases foot contact area and reduces self-generated noise. Spectrographic analysis reveals at least **30 distinct call types** — contact calls, mating rumbles, distress calls, and "let\'s go" rumbles that initiate group movement. Female estrous calls at ~14 Hz can attract bulls from 4+ km.',
      advancedContent:
        'Elephant seismic communication sits at the intersection of bioacoustics and geophysics. Rayleigh waves generated by elephant vocalizations propagate as **retrograde elliptical particle motion** in the substrate, with displacement amplitudes of ~10 nm detectable by mechanoreceptors tuned to 10–40 Hz. O\'Connell-Rodwell et al. demonstrated that elephants can discriminate between alarm calls from familiar and unfamiliar herds transmitted through the ground alone. The neural processing likely involves **temporal coding** of phase relationships between signals arriving at the two front feet — at a foot separation of ~1.5 m and a wavelength of ~12.5 m (250 m/s ÷ 20 Hz), the maximum interaural phase difference is ~43°, sufficient for directional localization. Research into elephant communication has informed **acoustic monitoring networks** in conservation: arrays of infrasonic microphones can track elephant movements in real-time across reserves, detecting poaching gunshots and distress calls automatically using machine learning classifiers.',
      diagram: 'SineWaveDiagram',
    },
    {
      title: 'Whiskers, Fur, and Touch',
      beginnerContent:
        'A tiger\'s whiskers are not decorative — they are highly sensitive touch sensors called vibrissae. Each whisker is rooted deep in the skin and connected to hundreds of nerve endings. Tigers use them to navigate in the dark, judge whether a gap is wide enough to pass through, and detect the movement of nearby prey through subtle air currents. The whiskers are roughly as wide as the tiger\'s body, serving as a built-in measuring tape. Seals use their whiskers underwater to detect the hydrodynamic trail left by a swimming fish — even minutes after the fish has passed. Rats use their whiskers to build a tactile map of their environment, whisking them back and forth up to 12 times per second.',
      intermediateContent:
        'Each vibrissa sits in a **follicle-sinus complex** — a blood-filled capsule that amplifies mechanical signals. The follicle contains ~100–200 mechanoreceptors (Merkel cells for sustained touch, lanceolate endings for vibration) connected to ~200 myelinated nerve fibres. When the whisker deflects, fluid in the blood sinus transmits pressure changes to these receptors with angular sensitivity of **~0.02°** — comparable to human fingertip sensitivity. Rat whisking follows a stereotyped motor pattern at **5–12 Hz**: protraction by intrinsic muscles and retraction by extrinsic muscles. Each whisker activates a discrete column of neurons in the somatosensory cortex called a **barrel** — the barrel cortex contains a topographic map where each barrel represents one whisker. Harbor seals can track a hydrodynamic trail 30+ seconds old because their whiskers have an undulating surface profile that suppresses self-induced vibration.',
      advancedContent:
        'The rat barrel cortex is one of neuroscience\'s best-studied sensory systems. Each cortical barrel (layer IV) contains ~4,000 neurons receiving thalamocortical input from one whisker\'s representation in the ventral posteromedial (VPM) thalamus. Single-whisker deflection produces a spike in the corresponding barrel within **7–10 ms**. **Active sensing** research shows rats make perceptual decisions within 1–2 whisking cycles (~100 ms) by comparing resonant vibration frequencies — different textures induce different frequency patterns in whiskers of different lengths, like a set of tuned mechanical resonators. This inspired **biomimetic tactile sensors** for robotics: arrays of artificial vibrissae on robot fingers can discriminate surface textures with ~90% accuracy. The mathematical framework uses Euler-Bernoulli beam theory to model whisker bending: **EI(d⁴y/dx⁴) = −μ(d²y/dt²)**, where E is Young\'s modulus, I is area moment of inertia, and μ is linear mass density.',
      interactive: {
        type: 'did-you-know',
        props: {
          facts: [
            'A tiger\'s whiskers are roughly as wide as its body, serving as a built-in measuring tape to judge whether it can fit through a gap.',
            'Seals can detect the hydrodynamic trail of a fish that swam past minutes ago, using just their whiskers.',
            'Rats whisk their whiskers back and forth up to 12 times per second to build a tactile map of their surroundings in the dark.',
          ],
        },
      },
    },
    {
      title: 'Night Vision and UV Vision',
      beginnerContent:
        'Owls are legendary night hunters, and their eyes are masterpieces of low-light engineering. An owl\'s eyes are not spherical like ours — they are tubular, acting like built-in telephoto lenses. Their retinas are packed with rod cells (which detect dim light) and have far fewer cone cells (which detect color). The result: owls can see in light conditions about 100 times dimmer than what humans need. Their eyes are so large relative to their skulls that they cannot rotate in their sockets — which is why owls evolved the ability to rotate their heads up to 270 degrees. On the other end of the spectrum, bees and many birds can see ultraviolet light. Flowers that look plain white to us often have vivid UV patterns — landing strips that guide bees to the nectar.',
      intermediateContent:
        'The sensitivity of rod cells is extraordinary: a single rod can respond to a **single photon** of light. Rods contain the pigment **rhodopsin** — a protein (opsin) bound to a light-sensitive molecule (retinal, derived from vitamin A). When a photon strikes retinal, it isomerises from 11-cis to all-trans form, triggering a G-protein cascade that amplifies the signal 100,000×, closing Na⁺ channels and hyperpolarising the cell. Dark adaptation takes ~30 minutes because rhodopsin must be regenerated. Owl eyes have a **pupil area** ~2.7× larger than human eyes relative to retinal area, collecting 2.7× more photons. Their retinal rod density reaches **1,000,000 rods/mm²** (human: ~150,000/mm²). Bee UV receptors peak at ~340 nm; many flowers have UV-absorbing pigments (flavonoids) concentrated in petal tips, creating "nectar guides" visible only in UV.',
      advancedContent:
        'Vertebrate photoreception involves a remarkable signal cascade: one photon activates one rhodopsin → one rhodopsin activates ~500 transducin (G-protein) molecules → each activates one phosphodiesterase → each PDE hydrolyses ~1,000 cGMP molecules → thousands of Na⁺ channels close. The amplification gain is ~10⁵, making the rod a quantum detector operating near the **shot noise limit**. Neural convergence further improves sensitivity: in cat retina, ~1,500 rods converge onto one ganglion cell, summing signals but reducing spatial resolution — the classic **sensitivity-acuity trade-off**. Birds see UV because they retained a fourth cone type (SWS1, peak ~370 nm) that mammals lost during their nocturnal evolutionary bottleneck. Some birds have **double cones** containing oil droplets that act as long-pass filters, effectively creating 5-dimensional color vision. Computational models of avian tetrachromatic color space suggest birds perceive ~10× more discriminable colors than trichromatic humans.',
      diagram: 'EyeAnatomyDiagram',
    },
    {
      title: 'Migration — Epic Journeys',
      beginnerContent:
        'Some of the most extraordinary animal behaviors involve migration. Arctic terns fly from the Arctic to the Antarctic and back every year — a round trip of about 70,000 kilometres, the longest migration of any animal. Monarch butterflies travel up to 4,500 kilometres from Canada to Mexico, navigating using a time-compensated sun compass in their antennae. Salmon return to the exact stream where they were born, navigating by smell — they can detect their home stream\'s unique chemical signature among millions of litres of ocean water. In Assam, vast flocks of migratory birds arrive at wetlands like Deepor Beel every winter, having flown thousands of kilometres from Central Asia, guided by magnetic sense, star patterns, and landmarks.',
      intermediateContent:
        'Migration navigation uses multiple compass systems. The **sun compass** requires an internal clock to compensate for the sun\'s movement (~15°/hr); in monarchs, this clock resides in the antennae. The **star compass** uses the rotation of star patterns around the celestial pole — young birds learn the pole position during development by watching star rotation. The **magnetic compass** detects the inclination angle of Earth\'s field lines (steep near poles, horizontal at equator), not polarity. Bar-headed geese cross the Himalayas at **9,000 m** where air density is 30% of sea level and O₂ partial pressure is ~6.5 kPa (vs 21 kPa at sea level). Their haemoglobin has a **higher O₂ affinity** (P₅₀ ≈ 35 mmHg vs ~50 mmHg in lowland geese) due to a single amino acid substitution (Pro → Ala at position 119α), allowing efficient O₂ loading at altitude.',
      advancedContent:
        'The molecular basis of monarch butterfly navigation involves a **time-compensated sun compass** encoded in the antennae\'s circadian clock (PER/TIM/CRY proteins). CRY1 in the antennae is a light-sensitive flavoprotein that entrains the clock; CRY2 in the brain acts as a magnetoreceptor. Surgical removal of antennae abolishes compass orientation; transplanting antennae with a phase-shifted clock redirects the butterflies predictably. Salmon olfactory imprinting occurs during the parr-smolt transformation: surges of thyroxine (T₄) and cortisol open a critical period during which dissolved amino acids unique to the natal stream are imprinted onto olfactory receptor neurons expressing specific **V2R receptors**. Years later, upstream-migrating adults match waterborne amino acid profiles against this imprinted template. Satellite tracking reveals that Arctic terns exploit global wind patterns, following a figure-8 route that adds distance but reduces energy expenditure, averaging ~520 km/day — powered by ~60 kJ/day, equivalent to burning 7 g of fat.',
      interactive: {
        type: 'matching',
        props: {
          title: 'Match each animal to its migration record',
          pairs: [
            ['Arctic tern', '70,000 km round trip — Arctic to Antarctic and back, the longest migration'],
            ['Monarch butterfly', '4,500 km from Canada to Mexico, navigating by sun compass in antennae'],
            ['Salmon', 'Returns to its birth stream by smell — detecting unique chemical signatures'],
            ['Bar-headed goose', 'Flies over the Himalayas at 9,000 m altitude on its migration route'],
          ],
        },
      },
    },
    {
      title: 'Camouflage and Mimicry',
      beginnerContent:
        'Camouflage is an evolutionary strategy for avoiding predators or ambushing prey. Chameleons change color using layers of special cells called chromatophores that contain different pigments. Cuttlefish go further — they can match not just the color but the pattern and texture of their surroundings in less than a second, despite being colorblind themselves. Stick insects look indistinguishable from twigs. Leaf-tailed geckos blend perfectly with tree bark. Mimicry is a related strategy: harmless hoverflies mimic the yellow-and-black stripes of wasps to deter predators. The most extreme example may be the mimic octopus, which can impersonate over 15 different species — including lionfish, flatfish, and sea snakes — by changing its shape, color, and movement patterns.',
      intermediateContent:
        'Chameleons change colour not through pigment redistribution but by **tuning photonic crystals**. Their skin contains two layers of iridophore cells packed with guanine nanocrystals arranged in a lattice. By relaxing or tensing the skin, the spacing between crystals changes, shifting reflected wavelengths from blue (close spacing, ~140 nm) to red (wider spacing, ~300+ nm). This is **structural colour** — the same physics as a butterfly wing or an opal. Cuttlefish have three layers: chromatophores (pigment sacs with radial muscles), iridophores (reflective plates), and leucophores (white scatterers). The brain controls ~200,000 chromatophores independently, expanding or contracting each in ~200 ms. **Batesian mimicry** (harmless species mimics harmful one) is frequency-dependent: it works only while mimics remain rare relative to models, because predators learn from experience.',
      advancedContent:
        '**Müllerian mimicry** occurs when multiple harmful species converge on a shared warning pattern, reducing per-species predation cost — as seen in coral snakes and their relatives across the Americas. The theoretical framework uses **signal detection theory**: the predator\'s decision to attack depends on its internal threshold separating "palatable" from "unpalatable" categories. The evolution of mimicry rings can be modelled with **number-dependent selection** (Müllerian) vs. **frequency-dependent selection** (Batesian), and many real systems involve a continuum. Cuttlefish camouflage presents a computational mystery: with colour-blind eyes, they use **luminance contrast** and **spatial frequency** to classify backgrounds into three response categories (uniform, mottle, disruptive) via a decision tree. The neural circuit from optic lobe to chromatophore motor neurons runs through the lateral basal lobes and is remarkably fast (~300 ms for full-body pattern change), suggesting pre-computed motor programs rather than real-time pixel-by-pixel matching.',
      diagram: 'AdaptationDiagram',
    },
    {
      title: 'Remarkable Animal Facts',
      beginnerContent:
        'The animal kingdom is full of abilities that seem almost impossible. Understanding how animals have solved engineering and survival problems often inspires human technology — a field called biomimicry.',
      intermediateContent:
        'The mantis shrimp\'s strike accelerates its club at **10,400 g** (104,000 m/s²) to a speed of **23 m/s** in under 3 ms — powered not by muscle alone but by a **spring-latch mechanism**. The saddle-shaped exoskeletal spring stores elastic energy while a latch holds the appendage in place; releasing the latch converts spring energy to kinetic energy far faster than muscle contraction allows. The resulting cavitation bubble (collapsing at ~4,700°C) delivers a second shock wave. Peregrine falcon stoops use **gravity-assisted acceleration**: starting from ~1,500 m, the bird tucks its wings into a near-vertical dive. Drag force: **F_d = ½ρv²C_dA**, where C_d ≈ 0.04 (extremely low due to tucked posture) and A ≈ 0.01 m². Terminal velocity: ~108 m/s (389 km/h). Special bony tubercles in the nostrils (nasal cone) prevent lung damage from the air pressure spike.',
      advancedContent:
        'Biomimicry is a $1.6 trillion industry. The mantis shrimp\'s impact-resistant club has inspired advanced **composites**: its dactyl club has a layered structure — outer layer of hydroxyapatite crystals (hardness), middle layer of chitin fibres in a **helicoidal (Bouligand) arrangement** that arrests crack propagation by redirecting fracture energy along spiral paths, and inner layer of amorphous mineral (impact absorption). This architecture has been replicated in carbon-fibre laminate designs showing 20% improvement in impact resistance. Octopus arm control poses a unique robotics challenge: with ~300 million neurons (60% in the arms), each arm has ~10⁷ degrees of freedom. Octopus arms solve this dimensionality problem by generating stereotyped **bend propagation waves** that simplify control to 3 parameters (bend point, propagation velocity, and direction). Soft robotics labs have built pneumatic silicone arms mimicking this strategy, achieving dexterous grasping with minimal computational overhead.',
      interactive: {
        type: 'did-you-know',
        props: {
          facts: [
            'A mantis shrimp can punch with the force of a bullet, accelerating its club-like appendage faster than a .22-caliber rifle. The strike is so fast it boils the water around it.',
            'Elephants are one of the few animals that can recognise themselves in a mirror, showing self-awareness. They also mourn their dead, gently touching the bones of deceased family members.',
            'A peregrine falcon can dive at over 390 km/h, making it the fastest animal on Earth. It tucks its wings and plummets toward prey in a manoeuvre called a stoop.',
            'Octopuses have three hearts, blue blood (copper-based instead of iron-based), and can squeeze through any gap larger than their beak — the only hard part of their body.',
            'Pistol shrimp snap their claws so quickly that the resulting bubble reaches temperatures of 4,700 degrees Celsius — nearly as hot as the surface of the Sun — for a fraction of a second.',
          ],
        },
      },
    },
  ]
};
