import type { ReferenceGuide } from '../reference';

export const guide: ReferenceGuide = {
  slug: 'geology-and-earth',
  title: 'Geology & Earth Science',
  category: 'geology',
  icon: '🌍',
  tagline: 'The ground under your feet is moving, mountains are growing, and rocks tell stories.',
  relatedStories: [],
  understand: [
    {
      title: 'The Earth Is an Egg',
      diagram: 'EarthLayersDiagram',
      beginnerContent:
        'If you could slice the Earth in half like a boiled egg, you would see layers.\n\n**The shell = the crust.** This is the thin, solid outer layer where we live. Under the continents, it is 30-70 km thick (continental crust). Under the oceans, it is only 5-10 km thick (oceanic crust). Compared to the whole Earth, the crust is thinner than an eggshell is to an egg.\n\n**The egg white = the mantle.** This is a 2,900 km thick layer of hot, dense rock. It is not liquid, but it is not quite solid either — over millions of years, it flows like extremely thick honey. This slow churning (called **convection**) is what drives the movement of tectonic plates on the surface. The upper mantle reaches temperatures of about 1,000 degrees Celsius; the lower mantle exceeds 3,000 degrees Celsius.\n\n**The yolk = the core.** The outer core (2,200 km thick) is liquid iron and nickel at 4,000-5,000 degrees Celsius. It is this swirling liquid metal that generates Earth\'s magnetic field — the invisible shield that deflects solar radiation and makes compasses work. The inner core (1,200 km radius) is solid iron at over 5,000 degrees Celsius — as hot as the surface of the Sun. It is solid despite the extreme temperature because the pressure at the center of the Earth is over 3.6 million times atmospheric pressure, which forces the atoms to pack tightly into a solid.\n\n**Check yourself:** The inner core is as hot as the surface of the Sun. Why is it solid? (Answer: The immense pressure — 3.6 million atmospheres — forces atoms together so tightly that they cannot flow as a liquid.)',
      intermediateContent:
        'Earth’s internal structure is probed by **seismology**. P-waves travel through both solids and liquids; S-waves only through solids. A seismometer on the far side of the Earth from an earthquake detects P-waves but not S-waves in a "shadow zone" between 104° and 140° angular distance, proving the outer core is liquid. Deeper analysis reveals velocity discontinuities: the **Mohorovičić discontinuity (Moho)** at 5–70 km depth marks the crust–mantle boundary (P-wave velocity jumps from ~6.5 to ~8 km/s); the **Gutenberg discontinuity** at 2,900 km marks the mantle–core boundary (P-wave velocity drops from ~13.7 to ~8 km/s as the medium changes from solid to liquid). The inner core was discovered by **Inge Lehmann** in 1936 from faint P-wave reflections within the shadow zone.',
      advancedContent:
        'Modern seismic tomography constructs 3D maps of Earth’s interior velocity structure from thousands of earthquake recordings, revealing mantle plumes (rising columns of hot material) and subducted slabs (cold, dense remnants of oceanic crust sinking to the core–mantle boundary). The **D″ layer** at the base of the mantle shows ultra-low velocity zones (ULVZs) interpreted as partial melt or iron-enriched silicates. Earth’s **magnetic field** is generated by the geodynamo — convection of liquid iron in the outer core, modelled by solving the magnetohydrodynamic (MHD) equations. The field reverses polarity at irregular intervals (averaging ~300,000 years); the last reversal (Brunhes–Matuyama) was 780,000 years ago. **Paleomagnetism** — the record of ancient field orientation locked into cooling lava — provided some of the strongest evidence for continental drift and sea-floor spreading.',
    },
    {
      title: 'Tectonic Plates — The Ground Is Moving Under Your Feet',
      diagram: 'PlateBoundaryDiagram',
      beginnerContent:
        'The Earth\'s crust is not a single unbroken shell. It is cracked into about **15 major tectonic plates** that float on the semi-liquid mantle below, like crackers floating on soup. These plates are in constant motion — typically 2-10 centimetres per year, roughly the speed your fingernails grow.\n\nThat sounds slow, but over millions of years it reshapes the world. 200 million years ago, all the continents were joined in a single supercontinent called **Pangaea**. Tectonic movement broke it apart and pushed the pieces to where they are today. South America and Africa were once joined — which is why their coastlines fit together like puzzle pieces and why you find identical fossils on both continents.\n\nPlates move because of **convection currents** in the mantle. Hot rock rises from near the core, flows sideways under the crust, cools, and sinks back down. This circulation drags the plates along.\n\nWhere plates meet, three things can happen:\n- **Divergent boundary** — plates pull apart, magma rises to fill the gap (mid-ocean ridges, like the Mid-Atlantic Ridge)\n- **Convergent boundary** — plates push together, one slides under the other (subduction), creating mountains and deep ocean trenches\n- **Transform boundary** — plates slide past each other sideways (like the San Andreas Fault in California)\n\n**Try this:** Take two sheets of paper and lay them flat on a table touching edge to edge. Now slowly push them together. Watch how they buckle upward — that is exactly how mountains form at convergent boundaries.\n\n**Check yourself:** If India is moving north at about 5 cm per year, how far will it have traveled in 1 million years? (Answer: 5 cm x 1,000,000 = 5,000,000 cm = 50 km — enough to significantly change the geography.)',
    },
    {
      title: 'Mountains Are Still Growing',
      diagram: 'GeoMountainGrowthDiagram',
      beginnerContent:
        'The Himalayas — the tallest mountain range on Earth — are still growing. Mount Everest gains about **1 centimetre per year** because the Indian tectonic plate is still crashing into the Eurasian plate at about 5 cm per year.\n\nThis collision started about 50 million years ago when the Indian subcontinent, which had been drifting north after breaking away from Africa, slammed into Asia. The force was (and is) enormous — enough to crumple the Earth\'s crust upward like a car bonnet in a head-on collision.\n\nBut mountains do not grow forever. **Erosion** fights back. Wind, water, ice, and gravity constantly wear down mountains. The Appalachian Mountains in eastern North America were once as tall as the Himalayas — about 450 million years ago. After hundreds of millions of years of erosion with no new tectonic uplift, they have been worn down to gentle, rounded hills.\n\nThe height of a mountain at any moment is the balance between:\n- **Tectonic uplift** (pushing up) — active at convergent plate boundaries\n- **Erosion** (wearing down) — happening everywhere, all the time\n- **Isostatic adjustment** — the crust floats on the mantle like an iceberg in water. As erosion removes material from the top, the mountain rises slightly, like a ship rising as you unload cargo. This means mountains erode more slowly than you might expect.\n\n**Did you know?** The tallest mountain from base to peak is not Everest. Mauna Kea in Hawaii rises 10,203 metres from its base on the ocean floor to its summit — about 1,355 metres taller than Everest. But because most of it is underwater, its peak is only 4,207 metres above sea level.\n\n**Check yourself:** If Everest gains 1 cm per year from tectonic uplift but loses 0.5 cm per year to erosion, how much taller will it be in 10,000 years? (Answer: net gain = 0.5 cm/year x 10,000 = 5,000 cm = 50 metres — still growing, but slowly.)',
      interactive: {
        type: 'did-you-know',
        props: {
          facts: [
            'The Himalayas are so massive that they affect weather patterns across all of Asia — they block cold Arctic air from reaching India and force monsoon winds upward, creating heavy rains.',
            'India was once an island continent near Antarctica. It broke away about 130 million years ago and drifted north at an unusually fast 15 cm/year before colliding with Asia.',
            'The summit of Everest contains limestone with marine fossils — the rock that forms the top of the world was once at the bottom of an ancient sea called the Tethys.',
          ],
        },
      },
    },
    {
      title: 'Volcanoes — Pressure Cookers Underground',
      diagram: 'GeoVolcanoDiagram',
      beginnerContent:
        '**Analogy:** Imagine shaking a bottle of fizzy drink. The gas dissolved in the liquid is under pressure. Open the cap and — WHOOSH — the gas expands violently and forces liquid out of the bottle. A volcanic eruption works on the same principle.\n\nDeep underground, rock is so hot that it melts into **magma** — a thick, glowing liquid containing dissolved gases (mainly water vapor, CO2, and sulfur dioxide). As magma rises toward the surface, pressure decreases. The dissolved gases start to expand — forming bubbles, just like in the fizzy drink. When the magma reaches the surface (now called **lava**), the gas expands explosively, shattering rock and hurling material into the air.\n\nNot all volcanoes erupt violently. It depends on the **viscosity** (thickness) of the magma:\n- **Low viscosity** (runny, like honey) — gas escapes easily, lava flows gently. Example: Hawaiian volcanoes, which produce spectacular lava fountains but rarely kill people.\n- **High viscosity** (thick, like peanut butter) — gas gets trapped, pressure builds, and eruptions are explosive. Example: Mount St. Helens (1980), which blew its entire north face off in a lateral blast.\n\nMost volcanoes sit along tectonic plate boundaries. The Pacific "Ring of Fire" — a horseshoe-shaped zone around the Pacific Ocean — contains 75% of the world\'s active volcanoes because multiple plates are converging and subducting there.\n\n**Check yourself:** Why is a volcano with thick, sticky magma more dangerous than one with runny magma? (Answer: Thick magma traps gas. The pressure builds until it exceeds the strength of the overlying rock, causing a violent explosion. Runny magma lets gas escape continuously, preventing pressure buildup.)',
    },
    {
      title: 'Earthquakes — When Plates Get Stuck Then Snap',
      beginnerContent:
        '**Analogy:** Bend a plastic ruler slowly. It bends and bends, storing energy. Then — SNAP — it breaks, and the energy is released all at once. Earthquakes work the same way.\n\nAt tectonic plate boundaries, enormous plates push against each other. Friction locks them in place — they cannot slide freely. Stress builds up over years, decades, or centuries. Eventually, the stress exceeds the friction holding them, and the plates suddenly lurch — sometimes by several metres in seconds. The stored energy radiates outward as **seismic waves** that shake the ground. This is an earthquake.\n\nThe point underground where the rock actually breaks is the **focus** (or hypocenter). The point on the surface directly above is the **epicenter** — this is what news reports give as the earthquake\'s location.\n\nEarthquakes produce two main types of waves:\n- **P-waves (Primary)** — compression waves that travel fastest (6-8 km/s through rock). They push and pull the ground in the direction they travel, like sound waves. They can travel through solids and liquids.\n- **S-waves (Secondary)** — shear waves that arrive after P-waves (3.5-4.5 km/s). They shake the ground side to side or up and down. They cannot travel through liquids — which is how we know the outer core is liquid (S-waves disappear when they hit it).\n\nEarthquake magnitude is measured on the **Richter scale** (or more precisely, the moment magnitude scale). Each whole number increase represents roughly **32 times** more energy. A magnitude 7 earthquake releases about 32 times more energy than a magnitude 6, and about 1,000 times more than a magnitude 5.\n\n**Check yourself:** How do we know Earth\'s outer core is liquid? (Answer: S-waves from earthquakes cannot travel through liquids. Seismometers on the opposite side of the Earth from an earthquake detect P-waves but not S-waves — the missing S-waves reveal a liquid layer in between.)',
      diagram: 'SeismicWavesDiagram',
    },
    {
      title: 'Rocks Tell Stories — Three Types of Rock',
      diagram: 'RockCycleDiagram',
      beginnerContent:
        'Every rock on Earth belongs to one of three families, and each family tells you something about the rock\'s history:\n\n**Igneous rocks** form when magma or lava cools and solidifies. "Igneous" means "born from fire." If the magma cools slowly underground, large crystals have time to grow — producing rocks like **granite** (the speckled rock used in kitchen countertops). If lava cools quickly at the surface, tiny crystals form — producing rocks like **basalt** (the dark rock of ocean floors and Hawaiian volcanoes). If lava cools extremely fast (like being ejected into air), you get **obsidian** — volcanic glass with no crystals at all.\n\n**Sedimentary rocks** form when layers of sediment (sand, mud, shells, dead organisms) accumulate and are compressed over millions of years. They are like geological history books — each layer records a different time period. **Sandstone** is compressed sand. **Limestone** is compressed seashells and coral. **Shale** is compressed mud. Fossils are almost always found in sedimentary rock.\n\n**Metamorphic rocks** form when existing rocks are transformed by extreme heat and pressure — "metamorphic" means "changed in form." Limestone becomes **marble**. Shale becomes **slate**. Sandstone becomes **quartzite**. The heat and pressure reorganize the minerals without melting the rock completely.\n\nThese three types cycle through each other over millions of years — the **rock cycle**. Igneous rock erodes into sediment, which becomes sedimentary rock, which gets pushed deep underground and transformed into metamorphic rock, which melts into magma, which cools into igneous rock again.\n\n**Check yourself:** You find a rock with visible layers and a fossil seashell embedded in it. What type of rock is it? (Answer: Sedimentary — the layers and fossil are dead giveaways. Fossils do not survive in igneous or metamorphic rock because the heat would destroy them.)',
      interactive: {
        type: 'matching',
        props: {
          title: 'Match each rock type to its formation process',
          pairs: [
            ['Igneous (e.g., granite, basalt)', 'Formed when magma or lava cools and solidifies'],
            ['Sedimentary (e.g., sandstone, limestone)', 'Formed from compressed layers of sediment over millions of years'],
            ['Metamorphic (e.g., marble, slate)', 'Formed when existing rock is transformed by extreme heat and pressure'],
          ],
        },
      },
    },
    {
      title: 'Fossils — Nature\'s Time Capsules',
      diagram: 'GeoFossilDiagram',
      beginnerContent:
        'A fossil is the preserved remains or traces of a living thing from the past. Most fossils are found in **sedimentary rock** because the gentle process of burial in sediment protects organisms from decay. (Igneous and metamorphic processes destroy organic remains.)\n\nHere is how most fossils form:\n1. An organism dies and is quickly buried by sediment (sand, mud, volcanic ash)\n2. Soft tissues decay, but hard parts (bones, shells, teeth) remain\n3. Over millions of years, minerals in groundwater slowly **replace** the original bone or shell molecule by molecule — turning it to stone while preserving the shape. This is **petrification** (literally "turning to stone")\n4. Tectonic forces and erosion eventually bring the fossil back to the surface\n\nNot all fossils are bones. **Trace fossils** record behavior: footprints, burrows, bite marks, and even fossilized dinosaur dung (called **coprolites** — yes, scientists study ancient poop to learn what dinosaurs ate).\n\nThe oldest fossils are about **3.5 billion years old** — single-celled organisms called stromatolites, found in ancient Australian rocks. The youngest fossils are just a few thousand years old. Together, they form a record of life on Earth spanning most of its 4.5-billion-year history.\n\n**Try this:** Next time you see a piece of limestone (many buildings and footpaths use it), look closely. You may spot tiny shell fragments or even complete fossils embedded in the stone — the remains of sea creatures from millions of years ago, now part of your sidewalk.\n\n**Check yourself:** Why are fossils almost never found in igneous rock? (Answer: Igneous rock forms from molten magma/lava at temperatures of 700-1,200 degrees Celsius — any organic remains would be completely destroyed.)',
    },
    {
      title: 'Erosion — Water Is Patient and Powerful',
      diagram: 'GeoErosionProcessDiagram',
      beginnerContent:
        'The Grand Canyon is 1,600 metres deep, 29 kilometres wide, and 446 kilometres long. It was carved almost entirely by water — the Colorado River — over about 5-6 million years. Water is patient.\n\n**Erosion** is the process by which rock and soil are worn away and transported by natural forces. The main agents are:\n\n**Water** — The most powerful erosion agent. Rainwater dissolves CO2 from the air, forming weak carbonic acid that slowly dissolves limestone and other rocks (this is how caves form). Rivers physically abrade their beds with the sediment they carry — sand and gravel act like natural sandpaper. Coastal waves pound cliffs with enormous force.\n\n**Ice** — Water seeps into cracks in rock, freezes, and expands by 9%. This **frost wedging** gradually splits rock apart. Glaciers — rivers of ice — scrape and gouge the landscape as they flow, carving U-shaped valleys and transporting boulders hundreds of kilometres.\n\n**Wind** — In deserts, wind-blown sand acts like a natural sandblaster, sculpting rocks into dramatic shapes. Wind also carries away topsoil, which can cause agricultural disasters (like the 1930s Dust Bowl in the USA).\n\n**Gravity** — The silent eroder. Rockfalls, landslides, and the slow creep of soil downhill are all gravity-driven erosion. Gravity ensures that any material loosened by water, ice, or wind moves downhill.\n\n**Biological erosion** — Plant roots grow into cracks and gradually pry rock apart. Burrowing animals mix and loosen soil. Lichens produce acids that dissolve rock surfaces.\n\nErosion is why no landscape is permanent. Given enough time, water and gravity will level any mountain. The question is always: is the mountain being pushed up faster than it is being worn down?\n\n**Check yourself:** The Himalayas are only 50 million years old but are the tallest mountains on Earth. The Appalachians are 480 million years old but are much shorter. Why? (Answer: The Himalayas are still being pushed up by active tectonic collision faster than erosion wears them down. The Appalachians have had no active uplift for hundreds of millions of years, so erosion has had free reign.)',
    },
    {
      title: 'Freeze-Thaw Weathering',
      diagram: 'FreezeTnawDiagram',
      beginnerContent:
        'Water is one of the very few substances that **expands when it freezes** — by about 9% in ' +
        'volume. This seemingly small fact is one of the most powerful forces shaping landscapes on ' +
        'Earth. The process is called **freeze-thaw weathering** (also known as frost wedging or ' +
        'frost shattering), and it can split solid rock apart.\n\n' +
        'Here is how it works. During the day, rainwater or snowmelt seeps into tiny cracks, joints, ' +
        'and pores in rock. At night, when the temperature drops below 0°C, the water freezes. As it ' +
        'turns to ice, it expands with enormous force — up to **207 MPa** (about 2,000 times ' +
        'atmospheric pressure). This expansion pushes the crack walls apart, widening the crack ' +
        'slightly. When the ice melts the next day, water flows deeper into the now-larger crack. ' +
        'The next freeze widens it further. Over hundreds and thousands of cycles, solid rock is ' +
        'gradually **pried apart** into smaller and smaller pieces.\n\n' +
        'Freeze-thaw weathering is most active in regions where temperatures regularly cross the ' +
        '**freezing point** — mountain environments, high latitudes, and continental interiors with ' +
        'cold winters. In the Himalayas, freeze-thaw is a major cause of rockfalls and the scree ' +
        'slopes you see below steep cliffs. In cities, freeze-thaw damages roads (creating potholes), ' +
        'cracks building foundations, and breaks apart concrete structures.\n\n' +
        'The talus slopes (piles of angular rock fragments) at the base of mountain cliffs are largely ' +
        'the product of centuries of freeze-thaw weathering. Each fragment was once part of the cliff ' +
        'face, loosened by the patient, relentless action of freezing water.',
      intermediateContent:
        'The pressure generated by freezing water depends on the confinement of the ice. In a fully ' +
        'enclosed cavity, the theoretical maximum pressure is **207 MPa** at -22°C (the pressure ' +
        'melting point of ice at that temperature). The **tensile strength** of common rocks: granite ' +
        '~10-20 MPa, sandstone ~4-10 MPa, limestone ~5-15 MPa — all far below the maximum ice pressure, ' +
        'explaining why freeze-thaw is so effective. The rate of weathering depends on: (1) **frequency** ' +
        'of freeze-thaw cycles (not just cold temperatures — a constant -20°C does nothing), (2) ' +
        '**water availability** (dry rock cannot freeze-thaw), (3) **rock porosity** (more pores = more ' +
        'water entry points), (4) **crack density** (pre-existing fractures accelerate the process). ' +
        'Alpine environments may experience 200+ freeze-thaw cycles per year near the 0°C isotherm.',
      advancedContent:
        'The ice segregation model (Walder and Hallet, 1985) shows that maximum frost damage occurs ' +
        'not at the freezing front but in a **frozen fringe** behind it, where thin films of unfrozen ' +
        'water migrate toward growing ice lenses via cryosuction (thermodynamic pressure gradients). ' +
        'The critical temperature range for maximum damage is -3°C to -8°C, not colder, because ' +
        'cryosuction requires partially unfrozen pore water. Frost susceptibility of rocks is quantified ' +
        'by the **saturation coefficient** S_cr: rocks with S > S_cr (~0.80-0.91) are vulnerable. ' +
        'Periglacial geomorphology studies landforms shaped by freeze-thaw: patterned ground, solifluction ' +
        'lobes, pingos, and thermokarst. Climate change is shifting freeze-thaw zones poleward and upward, ' +
        'destabilizing permafrost regions and increasing rockfall hazards in alpine environments.',
    },
  ],
};
