import Header from '../components/Header';
import Footer from '../components/Footer';
import { Shield } from 'lucide-react';

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-white dark:bg-gray-900 transition-colors">
      <Header />
      <section className="pt-32 pb-20 px-4 sm:px-6 lg:px-8">
        <div className="max-w-4xl mx-auto">
          <div className="flex items-center gap-4 mb-8">
            <Shield className="w-12 h-12 text-sky-600" />
            <h1 className="text-4xl font-bold text-gray-900 dark:text-white">Privacy Policy</h1>
          </div>
          <p className="text-gray-600 dark:text-gray-400 mb-8">Last Updated: March 26, 2026</p>

          <div className="prose prose-lg dark:prose-invert max-w-none">
            <section className="mb-8">
              <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-4">1. Who We Are</h2>
              <p className="text-gray-600 dark:text-gray-300 mb-4">
                TigmaMinds Academy ("we," "our," or "us") is an education technology platform that teaches science,
                programming, AI, and robotics to students through illustrated stories rooted in Northeast India.
                We are based in Guwahati, Assam, India.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-4">2. What We Collect</h2>
              <h3 className="text-xl font-semibold text-gray-900 dark:text-white mb-3">2.1 Information You Provide</h3>
              <ul className="list-disc pl-6 text-gray-600 dark:text-gray-300 space-y-2 mb-4">
                <li><strong>Account information:</strong> Name, email address, and password when you create an account</li>
                <li><strong>Profile information:</strong> Grade level, school name, and subjects of interest (optional)</li>
                <li><strong>Contact form submissions:</strong> Name, email, and message content when you reach out to us</li>
                <li><strong>Application information:</strong> Details you provide when applying to our programs</li>
              </ul>

              <h3 className="text-xl font-semibold text-gray-900 dark:text-white mb-3 mt-6">2.2 Information Generated by Your Use</h3>
              <ul className="list-disc pl-6 text-gray-600 dark:text-gray-300 space-y-2 mb-4">
                <li><strong>Learning progress:</strong> Which lessons you've completed, which levels you've reached, and quiz/activity results</li>
                <li><strong>Code you write:</strong> Python code executed in the browser via Pyodide runs entirely on your device and is not sent to our servers</li>
                <li><strong>Theme preference:</strong> Light or dark mode, stored in your browser's localStorage</li>
              </ul>

              <h3 className="text-xl font-semibold text-gray-900 dark:text-white mb-3 mt-6">2.3 What We Do Not Collect</h3>
              <ul className="list-disc pl-6 text-gray-600 dark:text-gray-300 space-y-2 mb-4">
                <li>We do not run advertising or tracking scripts</li>
                <li>We do not use Google Analytics or any third-party analytics service</li>
                <li>We do not sell, rent, or trade your data to anyone</li>
                <li>We do not use cookies for advertising or cross-site tracking</li>
              </ul>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-4">3. How We Use Your Information</h2>
              <ul className="list-disc pl-6 text-gray-600 dark:text-gray-300 space-y-2 mb-4">
                <li>To create and manage your account</li>
                <li>To track your learning progress so you can pick up where you left off</li>
                <li>To respond to your questions and support requests</li>
                <li>To evaluate applications for our school and bootcamp programs</li>
                <li>To improve our lessons and platform based on aggregate usage patterns</li>
              </ul>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-4">4. How Code Execution Works</h2>
              <p className="text-gray-600 dark:text-gray-300 mb-4">
                Our lessons include interactive Python coding powered by Pyodide, which runs Python entirely in your
                web browser. Your code never leaves your device. No code you write is transmitted to our servers,
                stored in our database, or visible to anyone else. The computational output (charts, results) is
                generated locally on your machine.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-4">5. Cookies and Local Storage</h2>
              <p className="text-gray-600 dark:text-gray-300 mb-4">
                We use minimal browser storage:
              </p>
              <ul className="list-disc pl-6 text-gray-600 dark:text-gray-300 space-y-2 mb-4">
                <li><strong>Authentication cookie:</strong> A session cookie to keep you logged in. It is deleted when you log out or your session expires.</li>
                <li><strong>Theme preference:</strong> Stored in localStorage to remember your light/dark mode choice. This never leaves your browser.</li>
                <li><strong>Learning progress:</strong> Stored in our database (linked to your account) so your progress persists across devices.</li>
              </ul>
              <p className="text-gray-600 dark:text-gray-300 mb-4">
                We do not use any third-party cookies. We do not use cookies for advertising, analytics, or tracking.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-4">6. Data Sharing</h2>
              <p className="text-gray-600 dark:text-gray-300 mb-4">
                We share your personal information only in these limited circumstances:
              </p>
              <ul className="list-disc pl-6 text-gray-600 dark:text-gray-300 space-y-2 mb-4">
                <li><strong>With your school:</strong> If you are enrolled through a school program, we share your progress data with your teacher or school administrator</li>
                <li><strong>Infrastructure providers:</strong> Our hosting provider stores encrypted data on our behalf. They do not access or use your information.</li>
                <li><strong>Legal requirements:</strong> If required by law, court order, or government authority</li>
              </ul>
              <p className="text-gray-600 dark:text-gray-300 mb-4">
                We never sell your data. We never share it with advertisers. We never use it for purposes unrelated to your education.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-4">7. Children's Privacy</h2>
              <p className="text-gray-600 dark:text-gray-300 mb-4">
                Our platform is designed for students, including children. We take special care with minors' data:
              </p>
              <ul className="list-disc pl-6 text-gray-600 dark:text-gray-300 space-y-2 mb-4">
                <li>Students under 13 require parental or guardian consent to create an account</li>
                <li>We collect only what is necessary for the educational experience</li>
                <li>We never display a child's real name, photo, or identifying information publicly</li>
                <li>Parents or guardians can request access to, correction of, or deletion of their child's data at any time</li>
              </ul>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-4">8. Data Security</h2>
              <p className="text-gray-600 dark:text-gray-300 mb-4">
                We protect your data with encryption in transit (HTTPS) and at rest. Passwords are hashed and never
                stored in plain text. Access to production data is restricted to authorized personnel only. While no
                system is perfectly secure, we take reasonable measures to protect your information.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-4">9. Your Rights</h2>
              <p className="text-gray-600 dark:text-gray-300 mb-4">
                You can:
              </p>
              <ul className="list-disc pl-6 text-gray-600 dark:text-gray-300 space-y-2 mb-4">
                <li><strong>Access:</strong> Request a copy of the data we hold about you</li>
                <li><strong>Correct:</strong> Update inaccurate information in your account settings</li>
                <li><strong>Delete:</strong> Request deletion of your account and all associated data</li>
                <li><strong>Export:</strong> Request your learning progress data in a portable format</li>
              </ul>
              <p className="text-gray-600 dark:text-gray-300 mb-4">
                To exercise these rights, email us at hello@tigmaminds.academy.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-4">10. Data Retention</h2>
              <p className="text-gray-600 dark:text-gray-300 mb-4">
                We keep your account and progress data for as long as your account is active. If you delete your
                account, we remove your personal data within 30 days. Anonymized, aggregate data (e.g., "42% of
                students completed Level 3") may be retained indefinitely to improve our curriculum.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-4">11. Changes to This Policy</h2>
              <p className="text-gray-600 dark:text-gray-300 mb-4">
                If we make material changes, we will update the date at the top of this page and notify logged-in
                users. We will not retroactively weaken the privacy protections described here without your explicit consent.
              </p>
            </section>

            <section className="mb-8">
              <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-4">12. Contact Us</h2>
              <div className="bg-gray-50 dark:bg-gray-800 p-6 rounded-lg">
                <p className="text-gray-900 dark:text-white font-semibold mb-2">TigmaMinds Academy</p>
                <p className="text-gray-600 dark:text-gray-300">5, Bonbononi Path, Bongaon, Beltola</p>
                <p className="text-gray-600 dark:text-gray-300">Guwahati, Assam 781028, India</p>
                <p className="text-gray-600 dark:text-gray-300 mt-2">Email: hello@tigmaminds.academy</p>
              </div>
            </section>
          </div>
        </div>
      </section>
      <Footer />
    </div>
  );
}
