INSERT INTO public.lessons (id, slug, title, stem_title, is_demo) VALUES
  (1, 'orange-sunsets-assam', 'Why Assam''s Sunsets Are Orange', 'Atmospheric Optics & Scattering', true),
  (2, 'fishermans-daughter-storm', 'The Fisherman''s Daughter and the Storm', 'Ocean Science & Storm Formation', true),
  (3, 'snow-leopards-promise', 'The Snow Leopard''s Promise', 'Altitude & Mountain Physics', true),
  (4, 'map-makers-granddaughter', 'The Map Maker''s Granddaughter', 'Cartography & GIS', true),
  (5, 'old-banyan-trees-stories', 'The Old Banyan Tree''s Stories', 'Tree Biology & Longevity', true),
  (6, 'tigers-whisker', 'The Tiger''s Whisker', 'Animal Anatomy & Sensory Systems', false),
  (7, 'basket-weavers-song', 'The Basket Weaver''s Song', 'Mathematics of Weaving & Patterns', false),
  (8, 'honey-hunters-lesson', 'The Honey Hunter''s Lesson', 'Entomology & Bee Biology', true),
  (9, 'bamboo-taught-wind', 'How the Bamboo Taught the Wind to Dance', 'Resonance & Harmonics', false),
  (10, 'woodpeckers-drum', 'The Woodpecker''s Drum', 'Biomechanics & Skull Design', true),
  (11, 'girl-who-spoke-to-elephants', 'The Girl Who Spoke to Elephants', 'AI & Wildlife Tracking', true),
  (12, 'firefly-festival-of-majuli', 'The Firefly Festival of Majuli', 'LEDs, Circuits & Bioluminescence', true),
  (13, 'river-dolphins-secret', 'The River Dolphin''s Secret', 'Sonar Sensors & Arduino', false),
  (14, 'boy-who-built-a-library', 'The Boy Who Built a Library', 'Web Development & Databases', false),
  (15, 'dragonfly-and-the-paddy-field', 'The Dragonfly and the Paddy Field', 'Drones & Computer Vision', false),
  (16, 'why-the-muga-silk-is-golden', 'Why the Muga Silk Is Golden', 'Biology & Materials Science', false),
  (17, 'tejimola-the-girl-who-became-a-plant', 'Tejimola — The Girl Who Became a Plant', 'Plant Biology & Genetics', false),
  (18, 'golden-deer-of-kamakhya', 'The Golden Deer of Kamakhya', 'Optics & Light', false),
  (19, 'boy-who-talked-to-clouds', 'The Boy Who Talked to Clouds', 'Meteorology & Climate', false),
  (20, 'how-majuli-island-was-born', 'How Majuli Island Was Born', 'Geography & River Dynamics', false),
  (21, 'bamboo-flute-of-nagaland', 'The Bamboo Flute of Nagaland', 'Acoustics & Sound', false),
  (22, 'dancing-deer-of-loktak-lake', 'The Dancing Deer of Loktak Lake', 'Ecology & Conservation', false),
  (23, 'bridge-that-grew', 'The Bridge That Grew', 'Bio-engineering & Structures', false),
  (24, 'the-little-boat', 'The Little Boat on the Brahmaputra', 'Fluid Dynamics & Buoyancy', false),
  (25, 'the-hornbills-crown', 'The Hornbill''s Crown', 'Ornithology & Animal Behavior', false),
  (26, 'why-fish-jump', 'Why Fish Jump in the Barak River', 'Fish Biology & Aquatic Ecosystems', false),
  (27, 'tortoise-and-hare', 'The Tortoise and the Hare of Pobitora', 'Speed, Acceleration & Biomechanics', false),
  (28, 'red-panda-mask', 'How the Red Panda Got Its Mask', 'Evolution & Camouflage', false),
  (29, 'clouded-leopard', 'The Boy Who Befriended a Clouded Leopard', 'Animal Conservation & Tracking', false),
  (30, 'peacocks-dance', 'Why Peacocks Dance Before Rain', 'Animal Communication & Signaling', false),
  (31, 'elephant-mud-bath', 'The Little Elephant''s First Mud Bath', 'Thermoregulation & Animal Behavior', false),
  (32, 'brave-mithun', 'The Brave Mithun of Arunachal', 'Domestication & Selective Breeding', false),
  (33, 'cuckoo-calls-dawn', 'Why the Cuckoo Calls at Dawn', 'Circadian Rhythms & Biological Clocks', false),
  (34, 'orchid-colors', 'How the Orchid Got Its Colors', 'Plant Pigments & Pollination', false),
  (35, 'pitcher-plant', 'How the Pitcher Plant Learned to Catch', 'Carnivorous Plants & Adaptation', false),
  (36, 'bamboo-grows-fast', 'Why Bamboo Grows So Fast', 'Plant Growth Hormones & Cell Biology', false),
  (37, 'sal-tree', 'Why the Sal Tree Never Bends', 'Wood Science & Material Strength', false),
  (38, 'tiny-frog', 'The Tiny Frog of the Rainforest', 'Amphibian Biology & Size Extremes', false),
  (39, 'the-girl-who-painted-rain', 'The Girl Who Painted Rain', 'Color Science & Pigments', false),
  (40, 'cloud-weaver-of-tawang', 'The Cloud Weaver of Tawang', 'Textiles & Weaving Technology', false),
  (41, 'the-magic-japi-hat', 'The Magic Japi Hat', 'Geometry & Traditional Design', false),
  (42, 'star-fell-deepor', 'The Star That Fell Into Deepor Beel', 'Astronomy & Meteorites', false),
  (43, 'kite-festival', 'The Kite Festival of Guwahati', 'Aerodynamics & Flight', false),
  (44, 'grandmothers-pitha', 'Grandmother''s Pitha Stories', 'Food Science & Chemistry', false),
  (45, 'lost-temple', 'The Lost Temple of Madan Kamdev', 'Archaeology & Dating Methods', false),
  (46, 'seven-sisters', 'How the Seven Sisters Became States', 'Geography & Maps', false),
  (47, 'little-potter', 'The Little Potter of Dhubri', 'Ceramics & Material Science', false),
  (48, 'monkey-bridge', 'The Monkey Bridge of Namdapha', 'Primatology & Forest Canopy', false),
  (49, 'boy-counted-butterflies', 'The Boy Who Counted Butterflies', 'Data Collection & Citizen Science', false),
  (50, 'monsoon-home', 'How the Monsoon Found Its Way Home', 'Climate Patterns & Jet Streams', false),
  (51, 'grandmother-remembered', 'The Grandmother Who Remembered Everything', 'Memory & Neuroscience', false),
  (52, 'singing-bamboo', 'The Singing Bamboo of Mizoram', 'Resonance & Harmonics', false),
  (53, 'festival-lights', 'The Festival of Lights on the River', 'Energy & Light Technology', false),
  (54, 'little-train', 'The Little Train of the Hills', 'Mechanical Engineering & Railways', false),
  (55, 'postman-hills', 'The Postman of the Hills', 'Logistics & Optimization', false),
  (56, 'night-market-imphal', 'The Night Market of Imphal', 'Supply Chains & Market Economics', false),
  (57, 'turtle-mountain', 'The Turtle Who Carried a Mountain', 'Geology & Plate Tectonics', false),
  (58, 'rainbow-fish', 'The Rainbow Fish of Umiam Lake', 'Optics of Water & Iridescence', false),
  (59, 'holi-tea-gardens', 'The Colors of Holi in the Tea Gardens', 'Chemistry of Colors & Dyes', false),
  (60, 'kaziranga-grass', 'How the Kaziranga Grass Grows Tall', 'Grassland Ecology & Fire Cycles', false),
  (61, 'banyan-tree', 'The Old Banyan Tree''s Stories', 'Tree Biology & Longevity', false),
  (62, 'basket-weaver', 'The Basket Weaver''s Song', 'Mathematics of Weaving & Patterns', false),
  (63, 'seed-keeper', 'The Seed Keeper of Nagaland', 'Seed Banks & Genetic Preservation', false),
  (64, 'cloud-namer', 'The Child Who Named the Clouds', 'Classification & Taxonomy', false),
  (65, 'kingfisher-blue', 'Why the Kingfisher Has a Blue Coat', 'Structural Color & Nanostructures', false),
  (66, 'owl-wisest', 'Why the Owl Is the Wisest', 'Owl Adaptations & Night Vision', false),
  (67, 'night-jasmine', 'Why the Night Jasmine Blooms After Dark', 'Circadian Rhythms in Plants', false),
  (68, 'woodpecker-drum', 'The Woodpecker''s Drum', 'Biomechanics & Skull Design', false),
  (69, 'music-dimasa', 'How Music Came to the Dimasa Kingdom', 'Music Theory & Vibrations', false),
  (70, 'silk-route', 'The Silk Route of the Caterpillars', 'Trade Routes & Economic Geography', false),
  (71, 'girl-grew-forest', 'The Girl Who Grew a Forest', 'Reforestation & Carbon Sequestration', false),
  (72, 'firewalker', 'The Firewalker''s Daughter', 'Heat Transfer & Thermal Physics', false),
  (73, 'frogs-sing-rain', 'Why Frogs Sing After Rain', 'Acoustics & Animal Communication', false),
  (74, 'eri-silk', 'How the Eri Silk Moth Found Peace', 'Silk Biology & Ethics', false),
  (75, 'river-braid', 'Why Rivers Braid Near the Sea', 'River Geomorphology', false),
  (76, 'lotus-float', 'How the Lotus Learned to Float', 'Buoyancy & Plant Adaptations', false),
  (77, 'first-rice', 'How the First Rice Was Planted', 'Agriculture & Crop Origins', false),
  (78, 'dhol-drum', 'How the Dhol Drum Got Its Thunder', 'Percussion Physics & Vibration', false),
  (79, 'little-chef', 'The Little Chef of Jorhat', 'Food Chemistry & Cooking Science', false),
  (80, 'flying-squirrel', 'The Flying Squirrel of Hollongapar', 'Gliding & Aerodynamics', false),
  (81, 'fireflies-dont-burn', 'Why Fireflies Don''t Burn', 'Bioluminescence Chemistry', false),
  (82, 'seed-travel', 'The Seed That Traveled a Thousand Miles', 'Seed Dispersal Mechanisms', false),
  (83, 'siang-river', 'How the Siang River Carved Its Path', 'Geological Erosion', false),
  (84, 'takin-face', 'How the Takin Got Its Funny Face', 'Genetics & Morphology', false),
  (85, 'talking-parrot-hajo', 'The Talking Parrot of Hajo', 'Language & Communication', false),
  (86, 'secret-garden-loktak', 'The Secret Garden of Loktak Lake', 'Aquatic Botany', false),
  (87, 'stars-ziro-valley', 'Why Stars Are Brighter in Ziro Valley', 'Light Pollution & Astronomy', true),
  (88, 'mishing-fish', 'How the Mishing People Learned to Fish', 'Fishing Technology', false),
  (89, 'coconut-jackfruit', 'The Coconut That Wanted to Be a Jackfruit', 'Genetics & Species Identity', false),
  (90, 'paper-umbrella', 'The Paper Umbrella of Sualkuchi', 'Paper Engineering', false),
  (91, 'witch-doctor', 'The Witch Doctor''s Apprentice', 'Medicinal Plants', false),
  (92, 'turtle-slow', 'Why Turtles Are Slow on Land', 'Evolution & Body Plans', false),
  (93, 'market-day-tura', 'The Market Day Surprise', 'Economics & Trade', false),
  (94, 'elephant-corridor', 'The Elephant Corridor', 'Wildlife Corridors', false),
  (95, 'golden-hilsa', 'The Old Fisherman and the Golden Hilsa', 'Sustainable Fishing', false),
  (96, 'cloud-refused-rain', 'The Cloud That Refused to Rain', 'Cloud Seeding & Weather', false),
  (97, 'friendship-bridge', 'The Friendship Bridge', 'Bridge Engineering', false),
  (98, 'mountain-echoes', 'Why Mountains Have Echoes', 'Sound Reflection', false),
  (99, 'dancer-floating-market', 'The Dancer of the Floating Market', 'Floating Market Economics', false),
  (100, 'ferrymans-riddle', 'The Ferryman''s Riddle', 'Fluid Mechanics', false),
  (101, 'wild-orchids-trees', 'Why Wild Orchids Grow on Trees', 'Epiphytes & Symbiosis', false),
  (102, 'guwahati-name', 'How Guwahati Got Its Name', 'Etymology & Urban Geography', false),
  (103, 'story-garden', 'The Story Garden', 'Storytelling & Narrative', false),
  (104, 'little-monk-tawang', 'The Little Monk of Tawang', 'Mountain Ecology & High-Altitude Environments', false),
  (105, 'moonlit-boat-race', 'The Moonlit Boat Race of Majuli', 'Fluid Dynamics & Boat Design', false),
  (106, 'little-river-joined', 'The Little River That Joined the Big One', 'River Hydrology & Confluences', false),
  (107, 'haflong-blue-mountains', 'Why the Mountains of Haflong Turn Blue', 'Atmospheric Optics & Rayleigh Scattering', false),
  (108, 'girl-python', 'The Girl Who Made Friends with a Python', 'Reptile Biology & Coexistence', false),
  (109, 'kite-eagle-dimapur', 'The Kite and the Eagle Over Dimapur', 'Aerodynamics & Flight', false),
  (110, 'boy-raced-brahmaputra', 'The Boy Who Raced the Brahmaputra', 'Biomechanics & River Physics', false)
ON CONFLICT (id) DO UPDATE SET slug = EXCLUDED.slug, title = EXCLUDED.title, stem_title = EXCLUDED.stem_title, is_demo = EXCLUDED.is_demo;
-- Mythology stories
INSERT INTO public.lessons (id, slug, title, stem_title, is_demo) VALUES
  (111, 'churning-of-the-ocean', 'The Churning of the Ocean', 'Chemistry & Fluid Dynamics', true),
  (112, 'sand-mandala', 'The Sand Mandala', 'Geometry, Symmetry & Fractals', true),
  (113, 'david-and-goliath', 'David and Goliath — The Physics of the Sling', 'Projectile Motion & Biomechanics', true),
  (114, 'geometry-of-alhambra', 'The Geometry of the Alhambra', 'Symmetry, Tessellations & Group Theory', true)
ON CONFLICT (id) DO UPDATE SET slug = EXCLUDED.slug, title = EXCLUDED.title, stem_title = EXCLUDED.stem_title, is_demo = EXCLUDED.is_demo;


-- Mythology stories batch 2-3 (IDs 115-130)
INSERT INTO public.lessons (id, slug, title, stem_title, is_demo) VALUES
  (115, 'hanuman-lifted-mountain', 'Why Hanuman Lifted a Mountain', 'Geology & Botany', true),
  (116, 'ravanas-ten-heads', 'Ravana\''s Ten Heads', 'Neuroscience & Parallel Computing', true),
  (117, 'bodhi-tree', 'The Bodhi Tree That Never Dies', 'Plant Biology & Cloning', true),
  (118, 'noahs-ark', 'Noah\''s Ark — Floating a Zoo', 'Naval Architecture & Biodiversity', true),
  (119, 'the-astrolabe', 'The Astrolabe \u2014 Mapping the Sky in Your Hand', 'Astronomy & Instrument Design', true),
  (120, 'pushpaka-vimana', 'The Pushpaka Vimana', 'Aerodynamics & Flight', true),
  (121, 'agni-science-of-fire', 'Agni \u2014 The Science of Fire', 'Combustion Chemistry & Thermodynamics', true),
  (122, 'wheel-of-dharma', 'The Wheel of Dharma', 'Rotational Physics & Engineering', true),
  (123, 'monastery-bells', 'The Monastery Bells of Tawang', 'Acoustics & Wave Physics', true),
  (124, 'angulimala-change', 'Angulimala and the Power of Change', 'Neuroplasticity & Psychology', true),
  (125, 'star-of-bethlehem', 'The Star of Bethlehem', 'Astronomy & Celestial Navigation', true),
  (126, 'parting-red-sea', 'The Parting of the Red Sea', 'Tidal Physics & Fluid Dynamics', true),
  (127, 'tower-of-babel', 'The Tower of Babel', 'Structural Engineering & Linguistics', true),
  (128, 'al-khwarizmi-algebra', 'Al-Khwarizmi and the Language of Algebra', 'Algebra & Algorithm Design', true),
  (129, 'well-of-zamzam', 'The Well of Zamzam', 'Hydrology & Groundwater', true),
  (130, 'muezzins-call', 'The Muezzin\u2019s Call', 'Architectural Acoustics', true)
ON CONFLICT (id) DO UPDATE SET slug = EXCLUDED.slug, title = EXCLUDED.title, stem_title = EXCLUDED.stem_title, is_demo = EXCLUDED.is_demo;


-- All complete NE India stories (batch update)
INSERT INTO public.lessons (id, slug, title, stem_title, is_demo) VALUES
  (1, 'orange-sunsets-assam', 'Why Assam''s Sunsets Are Orange', 'Atmospheric Optics & Scattering', true),
  (2, 'fishermans-daughter-storm', 'The Fisherman''s Daughter and the Storm', 'Ocean Science & Storm Formation', true),
  (3, 'snow-leopards-promise', 'The Snow Leopard''s Promise', 'Altitude & Mountain Physics', true),
  (4, 'map-makers-granddaughter', 'The Map Maker''s Granddaughter', 'Cartography & GIS', true),
  (5, 'old-banyan-trees-stories', 'The Old Banyan Tree''s Stories', 'Tree Biology & Longevity', true),
  (7, 'basket-weavers-song', 'The Basket Weaver''s Song', 'Mathematics of Weaving & Patterns', true),
  (8, 'honey-hunters-lesson', 'The Honey Hunter''s Lesson', 'Entomology & Bee Biology', true),
  (9, 'bamboo-taught-wind', 'How the Bamboo Taught the Wind to Dance', 'Resonance & Harmonics', true),
  (10, 'woodpeckers-drum', 'The Woodpecker''s Drum', 'Biomechanics & Skull Design', true),
  (11, 'girl-who-spoke-to-elephants', 'The Girl Who Spoke to Elephants', 'AI & Wildlife Tracking', true),
  (12, 'firefly-festival-of-majuli', 'The Firefly Festival of Majuli', 'LEDs, Circuits & Bioluminescence', true),
  (13, 'river-dolphins-secret', 'The River Dolphin''s Secret', 'Sonar Sensors & Arduino', true),
  (16, 'why-the-muga-silk-is-golden', 'Why the Muga Silk Is Golden', 'Biology & Materials Science', true),
  (17, 'tejimola-the-girl-who-became-a-plant', 'Tejimola — The Girl Who Became a Plant', 'Plant Biology & Genetics', true),
  (19, 'boy-who-talked-to-clouds', 'The Boy Who Talked to Clouds', 'Meteorology & Climate', true),
  (20, 'how-majuli-island-was-born', 'How Majuli Island Was Born', 'Geography & River Dynamics', true),
  (21, 'bamboo-flute-of-nagaland', 'The Bamboo Flute of Nagaland', 'Acoustics & Sound', true),
  (22, 'dancing-deer-of-loktak-lake', 'The Dancing Deer of Loktak Lake', 'Ecology & Conservation', true),
  (23, 'bridge-that-grew', 'The Bridge That Grew', 'Bio-engineering & Structures', true),
  (24, 'the-little-boat', 'The Little Boat on the Brahmaputra', 'Fluid Dynamics & Buoyancy', true),
  (25, 'the-hornbills-crown', 'The Hornbill''s Crown', 'Ornithology & Animal Behavior', true),
  (26, 'why-fish-jump', 'Why Fish Jump in the Barak River', 'Fish Biology & Aquatic Ecosystems', true),
  (27, 'tortoise-and-hare', 'The Tortoise and the Hare of Pobitora', 'Speed, Acceleration & Biomechanics', true),
  (28, 'red-panda-mask', 'How the Red Panda Got Its Mask', 'Evolution & Camouflage', true),
  (29, 'clouded-leopard', 'The Boy Who Befriended a Clouded Leopard', 'Animal Conservation & Tracking', true),
  (31, 'elephant-mud-bath', 'The Little Elephant''s First Mud Bath', 'Thermoregulation & Animal Behavior', true),
  (34, 'orchid-colors', 'How the Orchid Got Its Colors', 'Plant Pigments & Pollination', true),
  (35, 'pitcher-plant', 'How the Pitcher Plant Learned to Catch', 'Carnivorous Plants & Adaptation', true),
  (38, 'tiny-frog', 'The Tiny Frog of the Rainforest', 'Amphibian Biology & Size Extremes', true),
  (41, 'the-magic-japi-hat', 'The Magic Japi Hat', 'Geometry & Traditional Design', true),
  (42, 'star-fell-deepor', 'The Star That Fell Into Deepor Beel', 'Astronomy & Meteorites', true),
  (43, 'kite-festival', 'The Kite Festival of Guwahati', 'Aerodynamics & Flight', true),
  (50, 'monsoon-home', 'How the Monsoon Found Its Way Home', 'Climate Patterns & Jet Streams', true),
  (54, 'little-train', 'The Little Train of the Hills', 'Mechanical Engineering & Railways', true),
  (58, 'rainbow-fish', 'The Rainbow Fish of Umiam Lake', 'Optics of Water & Iridescence', true),
  (63, 'seed-keeper', 'The Seed Keeper of Nagaland', 'Seed Banks & Genetic Preservation', true),
  (71, 'girl-grew-forest', 'The Girl Who Grew a Forest', 'Reforestation & Carbon Sequestration', true),
  (87, 'stars-ziro-valley', 'Why Stars Are Brighter in Ziro Valley', 'Light Pollution & Astronomy', true),
  (95, 'golden-hilsa', 'The Old Fisherman and the Golden Hilsa', 'Sustainable Fishing', true),
  (96, 'cloud-refused-rain', 'The Cloud That Refused to Rain', 'Cloud Seeding & Weather', true),
  -- Northeast State lessons (Mizoram, Manipur, Tripura, Nagaland, Sikkim)
  (131, 'cheraw-bamboo-dance', 'The Bamboo Dance of Mizoram', 'Periodic Motion & Rhythm Physics', false),
  (132, 'mautam-bamboo-famine', 'The Mautam — When Bamboo Flowers and Famine Follows', 'Ecology & Population Dynamics', false),
  (133, 'iron-smiths-lushai', 'The Iron Smiths of the Lushai Hills', 'Metallurgy & Chemistry of Iron', false),
  (134, 'hawk-blue-mountain', 'The Hawk of the Blue Mountain', 'Aerodynamics & Soaring Flight', false),
  (135, 'orchids-phawngpui', 'The Orchids of Phawngpui', 'Pollination Biology & Coevolution', false),
  (136, 'kangla-fort-manipur', 'The Fortress of Kangla', 'Hydraulic Engineering & Fortification', false),
  (137, 'thang-ta-manipur', 'The Sword and the Spear of Manipur', 'Rotational Dynamics & Biomechanics', false),
  (138, 'ras-lila-manipur', 'The Ras Lila of Manipur', 'Circular Motion & Orbital Mechanics', false),
  (139, 'ima-keithel-market', 'The Mothers'' Market of Imphal', 'Economics & Market Dynamics', false),
  (140, 'polo-manipur', 'The Birthplace of Polo', 'Momentum, Collisions & Projectile Motion', false),
  (141, 'neermahal-water-palace', 'The Water Palace of Tripura', 'Structural Engineering & Hydrostatics', false),
  (142, 'fourteen-gods-tripura', 'The Festival of Fourteen Gods', 'Astronomy & Lunar Cycles', false),
  (143, 'rubber-tripura', 'The Rubber Trees of Tripura', 'Polymer Chemistry & Materials Science', false),
  (144, 'cane-weavers-tripura', 'The Cane Weavers of Tripura', 'Symmetry, Tessellations & Algorithmic Thinking', false),
  (145, 'tripura-sundari-temple', 'The Temple on the Turtle''s Back', 'Geology & Plate Tectonics', false),
  (146, 'dzukou-valley-lily', 'The Lily of Dzükou Valley', 'Alpine Botany & Plant Adaptation', false),
  (147, 'stone-pulling-nagaland', 'The Stone Pullers of Nagaland', 'Simple Machines & Mechanical Advantage', false),
  (148, 'hornbill-flight-nagaland', 'The Great Hornbill''s Helmet', 'Materials Science & Impact Engineering', false),
  (149, 'naga-dao-metallurgy', 'The Naga Dao', 'Metallurgy & Edge Engineering', false),
  (150, 'kanchenjunga-five-treasures', 'The Five Treasures of Kanchenjunga', 'Glaciology & Climate Science', false),
  (151, 'red-panda-sikkim', 'The Red Panda of the Rhododendron Forest', 'Thermoregulation & Heat Transfer', false),
  (152, 'cardamom-hills-sikkim', 'The Cardamom Hills of Sikkim', 'Organic Chemistry & Essential Oils', false),
  (153, 'prayer-flags-sikkim', 'The Prayer Flags of Sikkim', 'Materials Degradation & Textile Science', false)
ON CONFLICT (id) DO UPDATE SET slug = EXCLUDED.slug, title = EXCLUDED.title, stem_title = EXCLUDED.stem_title, is_demo = EXCLUDED.is_demo;
