import ts from 'typescript';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const DATA = path.join(ROOT, 'src', 'data');
const OUT = path.join(DATA, 'lessons');

// Source files holding Lesson[] arrays, with the exported array identifier.
const SOURCES = [
  { file: 'lessons.ts', exportName: 'lessons' },
  { file: 'lessons-mythology.ts', exportName: 'mythologyLessons' },
  { file: 'lessons-history.ts', exportName: 'historyLessons' },
  { file: 'lessons-regional.ts', exportName: 'regionalLessons' },
  { file: 'lessons-ne-states.ts', exportName: 'neStatesLessons' },
];

// The Lucide icons that lesson files reference (from the original import lines).
const LUCIDE_ICONS = new Set([
  'Cpu', 'Lightbulb', 'Bot', 'Code2', 'Rocket', 'Sparkles', 'Leaf', 'Sun',
  'Cloud', 'Mountain', 'Music', 'TreePine', 'Construction', 'Code',
]);

fs.mkdirSync(OUT, { recursive: true });

const allSlugs = [];
const order = []; // preserve global ordering across all source files

for (const { file, exportName } of SOURCES) {
  const full = path.join(DATA, file);
  const text = fs.readFileSync(full, 'utf8');
  const sf = ts.createSourceFile(file, text, ts.ScriptTarget.Latest, true);

  // Find: export const <exportName> ... = [ ... ]
  let arrayLiteral = null;
  const visit = (node) => {
    if (arrayLiteral) return;
    if (ts.isVariableStatement(node)) {
      for (const decl of node.declarationList.declarations) {
        if (ts.isIdentifier(decl.name) && decl.name.text === exportName &&
            decl.initializer && ts.isArrayLiteralExpression(decl.initializer)) {
          arrayLiteral = decl.initializer;
          return;
        }
      }
    }
    ts.forEachChild(node, visit);
  };
  visit(sf);

  if (!arrayLiteral) {
    console.error(`!! Could not find array '${exportName}' in ${file}`);
    process.exit(1);
  }

  let count = 0;
  for (const el of arrayLiteral.elements) {
    if (!ts.isObjectLiteralExpression(el)) {
      console.error(`!! Non-object element in ${file} at pos ${el.getStart()}`);
      process.exit(1);
    }
    // Extract slug from the object literal.
    let slug = null;
    for (const prop of el.properties) {
      if (ts.isPropertyAssignment(prop) && prop.name &&
          ((ts.isIdentifier(prop.name) && prop.name.text === 'slug') ||
           (ts.isStringLiteral(prop.name) && prop.name.text === 'slug'))) {
        if (ts.isStringLiteral(prop.initializer)) slug = prop.initializer.text;
      }
    }
    if (!slug) {
      console.error(`!! Lesson without slug in ${file} near:`, el.getText(sf).slice(0, 120));
      process.exit(1);
    }
    if (allSlugs.includes(slug)) {
      console.error(`!! DUPLICATE slug across files: ${slug} (in ${file})`);
      process.exit(1);
    }

    // Emit the object literal source text VERBATIM (preserves template literals,
    // escapes, icon identifiers, formatting).
    const objText = el.getText(sf);

    // Which Lucide icons does this lesson reference?
    const usedIcons = [...LUCIDE_ICONS].filter((ic) =>
      new RegExp(`\\b${ic}\\b`).test(objText)
    ).sort();

    const importLine = usedIcons.length
      ? `import { ${usedIcons.join(', ')} } from 'lucide-react';\n`
      : '';

    const out =
      importLine +
      `import type { Lesson } from '../lesson-types';\n\n` +
      `export const lesson: Lesson = ${objText};\n`;

    fs.writeFileSync(path.join(OUT, `${slug}.ts`), out);
    allSlugs.push(slug);
    order.push(slug);
    count++;
  }
  console.log(`${file}: split ${count} lessons`);
}

// Registry: lazy importer per slug + ordered slug list for prev/next & full loads.
const registryLines = order
  .map((s) => `  ${JSON.stringify(s)}: () => import(${JSON.stringify('./' + s)}),`)
  .join('\n');

const registry =
  `import type { Lesson } from '../lesson-types';\n\n` +
  `// AUTO-GENERATED by scripts/split-lessons.mjs — do not edit by hand.\n` +
  `// One dynamic importer per lesson so each lesson's content is its own chunk.\n\n` +
  `export const LESSON_SLUGS: string[] = [\n` +
  order.map((s) => `  ${JSON.stringify(s)},`).join('\n') +
  `\n];\n\n` +
  `const loaders: Record<string, () => Promise<{ lesson: Lesson }>> = {\n` +
  registryLines +
  `\n};\n\n` +
  `export async function loadLesson(slug: string): Promise<Lesson | undefined> {\n` +
  `  const loader = loaders[slug];\n` +
  `  if (!loader) return undefined;\n` +
  `  return (await loader()).lesson;\n` +
  `}\n\n` +
  `export function hasLesson(slug: string): boolean {\n` +
  `  return slug in loaders;\n` +
  `}\n`;

fs.writeFileSync(path.join(OUT, 'registry.ts'), registry);
console.log(`\nTotal: ${allSlugs.length} lessons split`);
console.log(`Registry written: src/data/lessons/registry.ts`);
