/**
 * Lightweight lessons metadata for list/card views.
 * Generated by scripts/build-lessons-meta.ts at prebuild time.
 *
 * Importing this file does NOT pull in the full lessons module
 * (story content, level0-4, quizzes, etc.). Use this for /lessons,
 * /plan, /, /programs, /capstone, /certificate, related-story cards.
 *
 * For full lesson data on detail pages, import { getLessonBySlug }
 * from './lessons' directly.
 */

import {
  Cpu, Lightbulb, Bot, Code2, Rocket, Sparkles, Leaf, Sun, Cloud, Mountain,
  Music, TreePine, Construction, Compass, BookOpen, Ship, FlaskConical, Cog,
  Atom, Droplets, Flame, Waves, Globe, Zap, Factory, Radio, Microscope, Brain,
  Satellite, Wind, Hammer, Crown, Plane, Volume2, Building2, HelpCircle,
  type LucideIcon,
} from 'lucide-react';
import metaJson from './lessons-meta.json';
import type { Subject, Skill, SkillTag, Tradition, LessonOrigin } from './lesson-types';

const ICON_MAP: Record<string, LucideIcon> = {
  Cpu, Lightbulb, Bot, Code2, Rocket, Sparkles, Leaf, Sun, Cloud, Mountain,
  Music, TreePine, Construction, Compass, BookOpen, Ship, FlaskConical, Cog,
  Atom, Droplets, Flame, Waves, Globe, Zap, Factory, Radio, Microscope, Brain,
  Satellite, Wind, Hammer, Crown, Plane, Volume2, Building2,
};

export interface LessonMeta {
  id: number;
  slug: string;
  storyTitle: string;
  tagline: string;
  illustration?: string;
  stemTitle: string;
  stemDescription: string;
  stemColor: string;
  stemIcon: LucideIcon;
  stemSkills: string[];
  projectTitle?: string;
  projectDescription?: string;
  projectSteps?: string[];
  subjects: Subject[];
  toolSkills: Skill[];
  skillTags: SkillTag[];
  estimatedHours: number;
  track?: string;
  tradition?: Tradition;
  origin?: LessonOrigin;
  hasLevel0: boolean;
}

interface RawMeta extends Omit<LessonMeta, 'stemIcon'> {
  stemIcon: string;
}

export const lessonsMeta: LessonMeta[] = (metaJson as RawMeta[]).map((m) => ({
  ...m,
  stemIcon: ICON_MAP[m.stemIcon] || HelpCircle,
}));

export function getLessonMetaBySlug(slug: string): LessonMeta | undefined {
  return lessonsMeta.find((l) => l.slug === slug);
}
